#
#
#  #############################################################
#  ##                                                         ##
#  ##  compopt.make  --  optimized compile of TINKER modules  ##
#  ##        (Intel Fortran Compiler for Linux Version)       ##
#  ##                                                         ##
#  #############################################################
#
#
ifort -c -fast -w active.f
ifort -c -fast -w alchemy.f
ifort -c -fast -w analysis.f
ifort -c -fast -w analyze.f
ifort -c -fast -w angles.f
ifort -c -fast -w anneal.f
ifort -c -fast -w archive.f
ifort -c -fast -w attach.f
ifort -c -fast -w basefile.f
ifort -c -fast -w beeman.f
ifort -c -fast -w bicubic.f
ifort -c -fast -w bitors.f
ifort -c -fast -w bonds.f
ifort -c -fast -w born.f
ifort -c -fast -w bounds.f
ifort -c -fast -w bspline.f
ifort -c -fast -w calendar.f
ifort -c -fast -w center.f
ifort -c -fast -w chkpole.f
ifort -c -fast -w chkring.f
ifort -c -fast -w chkxyz.f
ifort -c -fast -w cholesky.f
ifort -c -fast -w clock.f
ifort -c -fast -w cluster.f
ifort -c -fast -w column.f
ifort -c -fast -w command.f
ifort -c -fast -w connect.f
ifort -c -fast -w connolly.f
ifort -c -fast -w control.f
ifort -c -fast -w correlate.f
ifort -c -fast -w crystal.f
ifort -c -fast -w cspline.f
ifort -c -fast -w cutoffs.f
ifort -c -fast -w deflate.f
ifort -c -fast -w delete.f
ifort -c -fast -w diagq.f
ifort -c -fast -w diffeq.f
ifort -c -fast -w diffuse.f
ifort -c -fast -w distgeom.f
ifort -c -fast -w document.f
ifort -c -fast -w dynamic.f
ifort -c -fast -w eangang.f
ifort -c -fast -w eangang1.f
ifort -c -fast -w eangang2.f
ifort -c -fast -w eangang3.f
ifort -c -fast -w eangle.f
ifort -c -fast -w eangle1.f
ifort -c -fast -w eangle2.f
ifort -c -fast -w eangle3.f
ifort -c -fast -w ebond.f
ifort -c -fast -w ebond1.f
ifort -c -fast -w ebond2.f
ifort -c -fast -w ebond3.f
ifort -c -fast -w ebuck.f
ifort -c -fast -w ebuck1.f
ifort -c -fast -w ebuck2.f
ifort -c -fast -w ebuck3.f
ifort -c -fast -w echarge.f
ifort -c -fast -w echarge1.f
ifort -c -fast -w echarge2.f
ifort -c -fast -w echarge3.f
ifort -c -fast -w echgdpl.f
ifort -c -fast -w echgdpl1.f
ifort -c -fast -w echgdpl2.f
ifort -c -fast -w echgdpl3.f
ifort -c -fast -w edipole.f
ifort -c -fast -w edipole1.f
ifort -c -fast -w edipole2.f
ifort -c -fast -w edipole3.f
ifort -c -fast -w egauss.f
ifort -c -fast -w egauss1.f
ifort -c -fast -w egauss2.f
ifort -c -fast -w egauss3.f
ifort -c -fast -w egeom.f
ifort -c -fast -w egeom1.f
ifort -c -fast -w egeom2.f
ifort -c -fast -w egeom3.f
ifort -c -fast -w ehal.f
ifort -c -fast -w ehal1.f
ifort -c -fast -w ehal2.f
ifort -c -fast -w ehal3.f
ifort -c -fast -w eimprop.f
ifort -c -fast -w eimprop1.f
ifort -c -fast -w eimprop2.f
ifort -c -fast -w eimprop3.f
ifort -c -fast -w eimptor.f
ifort -c -fast -w eimptor1.f
ifort -c -fast -w eimptor2.f
ifort -c -fast -w eimptor3.f
ifort -c -fast -w elj.f
ifort -c -fast -w elj1.f
ifort -c -fast -w elj2.f
ifort -c -fast -w elj3.f
ifort -c -fast -w embed.f
ifort -c -fast -w emetal.f
ifort -c -fast -w emetal1.f
ifort -c -fast -w emetal2.f
ifort -c -fast -w emetal3.f
ifort -c -fast -w emm3hb.f
ifort -c -fast -w emm3hb1.f
ifort -c -fast -w emm3hb2.f
ifort -c -fast -w emm3hb3.f
ifort -c -fast -w empole.f
ifort -c -fast -w empole1.f
ifort -c -fast -w empole2.f
ifort -c -fast -w empole3.f
ifort -c -fast -w energy.f
ifort -c -fast -w eopbend.f
ifort -c -fast -w eopbend1.f
ifort -c -fast -w eopbend2.f
ifort -c -fast -w eopbend3.f
ifort -c -fast -w eopdist.f
ifort -c -fast -w eopdist1.f
ifort -c -fast -w eopdist2.f
ifort -c -fast -w eopdist3.f
ifort -c -fast -w epitors.f
ifort -c -fast -w epitors1.f
ifort -c -fast -w epitors2.f
ifort -c -fast -w epitors3.f
ifort -c -fast -w erf.f
ifort -c -fast -w erxnfld.f
ifort -c -fast -w erxnfld1.f
ifort -c -fast -w erxnfld2.f
ifort -c -fast -w erxnfld3.f
ifort -c -fast -w esolv.f
ifort -c -fast -w esolv1.f
ifort -c -fast -w esolv2.f
ifort -c -fast -w esolv3.f
ifort -c -fast -w estrbnd.f
ifort -c -fast -w estrbnd1.f
ifort -c -fast -w estrbnd2.f
ifort -c -fast -w estrbnd3.f
ifort -c -fast -w estrtor.f
ifort -c -fast -w estrtor1.f
ifort -c -fast -w estrtor2.f
ifort -c -fast -w estrtor3.f
ifort -c -fast -w etors.f
ifort -c -fast -w etors1.f
ifort -c -fast -w etors2.f
ifort -c -fast -w etors3.f
ifort -c -fast -w etortor.f
ifort -c -fast -w etortor1.f
ifort -c -fast -w etortor2.f
ifort -c -fast -w etortor3.f
ifort -c -fast -w eurey.f
ifort -c -fast -w eurey1.f
ifort -c -fast -w eurey2.f
ifort -c -fast -w eurey3.f
ifort -c -fast -w extra.f
ifort -c -fast -w extra1.f
ifort -c -fast -w extra2.f
ifort -c -fast -w extra3.f
ifort -c -fast -w fatal.f
ifort -c -fast -w fft3d.f
ifort -c -fast -w fftpack.f
ifort -c -fast -w field.f
ifort -c -fast -w final.f
ifort -c -fast -w flatten.f
ifort -c -fast -w freeunit.f
ifort -c -fast -w gda.f
ifort -c -fast -w geometry.f
ifort -c -fast -w getime.f
ifort -c -fast -w getint.f
ifort -c -fast -w getkey.f
ifort -c -fast -w getmol2.f
ifort -c -fast -w getnumb.f
ifort -c -fast -w getpdb.f
ifort -c -fast -w getprm.f
ifort -c -fast -w getref.f
ifort -c -fast -w getstring.f
ifort -c -fast -w gettext.f
ifort -c -fast -w getword.f
ifort -c -fast -w getxyz.f
ifort -c -fast -w gradient.f
ifort -c -fast -w gradrgd.f
ifort -c -fast -w gradrot.f
ifort -c -fast -w groups.f
ifort -c -fast -w grpline.f
ifort -c -fast -w gyrate.f
ifort -c -fast -w hessian.f
ifort -c -fast -w hessrgd.f
ifort -c -fast -w hessrot.f
ifort -c -fast -w hybrid.f
ifort -c -fast -w image.f
ifort -c -fast -w impose.f
ifort -c -fast -w induce.f
ifort -c -fast -w inertia.f
ifort -c -fast -w initial.f
ifort -c -fast -w initprm.f
ifort -c -fast -w initres.f
ifort -c -fast -w initrot.f
ifort -c -fast -w insert.f
ifort -c -fast -w intedit.f
ifort -c -fast -w intxyz.f
ifort -c -fast -w invbeta.f
ifort -c -fast -w invert.f
ifort -c -fast -w jacobi.f
ifort -c -fast -w kangang.f
ifort -c -fast -w kangle.f
ifort -c -fast -w katom.f
ifort -c -fast -w kbond.f
ifort -c -fast -w kcharge.f
ifort -c -fast -w kdipole.f
ifort -c -fast -w kewald.f
ifort -c -fast -w kgeom.f
ifort -c -fast -w kimprop.f
ifort -c -fast -w kimptor.f
ifort -c -fast -w kinetic.f
ifort -c -fast -w kmetal.f
ifort -c -fast -w kmpole.f
ifort -c -fast -w kopbend.f
ifort -c -fast -w kopdist.f
ifort -c -fast -w korbit.f
ifort -c -fast -w kpitors.f
ifort -c -fast -w kpolar.f
ifort -c -fast -w ksolv.f
ifort -c -fast -w kstrbnd.f
ifort -c -fast -w kstrtor.f
ifort -c -fast -w ktors.f
ifort -c -fast -w ktortor.f
ifort -c -fast -w kurey.f
ifort -c -fast -w kvdw.f
ifort -c -fast -w lattice.f
ifort -c -fast -w lbfgs.f
ifort -c -fast -w lights.f
ifort -c -fast -w makeint.f
ifort -c -fast -w makepdb.f
ifort -c -fast -w makeref.f
ifort -c -fast -w makexyz.f
ifort -c -fast -w maxwell.f
ifort -c -fast -w mdinit.f
ifort -c -fast -w mdrest.f
ifort -c -fast -w mdsave.f
ifort -c -fast -w mdstat.f
ifort -c -fast -w mechanic.f
ifort -c -fast -w merge.f
ifort -c -fast -w minimize.f
ifort -c -fast -w minirot.f
ifort -c -fast -w minrigid.f
ifort -c -fast -w molecule.f
ifort -c -fast -w moments.f
ifort -c -fast -w monte.f
ifort -c -fast -w mutate.f
ifort -c -fast -w nblist.f
ifort -c -fast -w newton.f
ifort -c -fast -w newtrot.f
ifort -c -fast -w nextarg.f
ifort -c -fast -w nexttext.f
ifort -c -fast -w nspline.f
ifort -c -fast -w nucleic.f
ifort -c -fast -w number.f
ifort -c -fast -w numeral.f
ifort -c -fast -w numgrad.f
ifort -c -fast -w ocvm.f
ifort -c -fast -w openend.f
ifort -c -fast -w optimize.f
ifort -c -fast -w optirot.f
ifort -c -fast -w optrigid.f
ifort -c -fast -w optsave.f
ifort -c -fast -w orbital.f
ifort -c -fast -w orient.f
ifort -c -fast -w orthog.f
ifort -c -fast -w overlap.f
ifort -c -fast -w path.f
ifort -c -fast -w pdbxyz.f
ifort -c -fast -w piscf.f
ifort -c -fast -w pmepol.f
ifort -c -fast -w pmpb.f
ifort -c -fast -w polarize.f
ifort -c -fast -w poledit.f
ifort -c -fast -w polymer.f
ifort -c -fast -w potential.f
ifort -c -fast -w precise.f
ifort -c -fast -w pressure.f
ifort -c -fast -w prmedit.f
ifort -c -fast -w prmkey.f
ifort -c -fast -w promo.f
ifort -c -fast -w protein.f
ifort -c -fast -w prtdyn.f
ifort -c -fast -w prterr.f
ifort -c -fast -w prtint.f
ifort -c -fast -w prtmol2.f
ifort -c -fast -w prtpdb.f
ifort -c -fast -w prtprm.f
ifort -c -fast -w prtseq.f
ifort -c -fast -w prtxyz.f
ifort -c -fast -w pss.f
ifort -c -fast -w pssrigid.f
ifort -c -fast -w pssrot.f
ifort -c -fast -w quatfit.f
ifort -c -fast -w radial.f
ifort -c -fast -w random.f
ifort -c -fast -w rattle.f
ifort -c -fast -w readdyn.f
ifort -c -fast -w readgau.f
ifort -c -fast -w readint.f
ifort -c -fast -w readmol2.f
ifort -c -fast -w readpdb.f
ifort -c -fast -w readprm.f
ifort -c -fast -w readseq.f
ifort -c -fast -w readxyz.f
ifort -c -fast -w replica.f
ifort -c -fast -w rgdstep.f
ifort -c -fast -w rings.f
ifort -c -fast -w rmsfit.f
ifort -c -fast -w rotlist.f
ifort -c -fast -w rotpole.f
ifort -c -fast -w saddle.f
ifort -c -fast -w scan.f
ifort -c -fast -w sdstep.f
ifort -c -fast -w search.f
ifort -c -fast -w server.f
ifort -c -fast -w setime.f
ifort -c -fast -w shakeup.f
ifort -c -fast -w sigmoid.f
ifort -c -fast -w sktstuff.f
ifort -c -fast -w sniffer.f
ifort -c -fast -w sort.f
ifort -c -fast -w spacefill.f
ifort -c -fast -w spectrum.f
ifort -c -fast -w square.f
ifort -c -fast -w suffix.f
ifort -c -fast -w superpose.f
ifort -c -fast -w surface.f
ifort -c -fast -w surfatom.f
ifort -c -fast -w switch.f
ifort -c -fast -w sybylxyz.f
ifort -c -fast -w temper.f
ifort -c -fast -w testgrad.f
ifort -c -fast -w testhess.f
ifort -c -fast -w testpair.f
ifort -c -fast -w testrot.f
ifort -c -fast -w timer.f
ifort -c -fast -w timerot.f
ifort -c -fast -w tncg.f
ifort -c -fast -w torphase.f
ifort -c -fast -w torque.f
ifort -c -fast -w torsions.f
ifort -c -fast -w trimtext.f
ifort -c -fast -w unitcell.f
ifort -c -fast -w valence.f
ifort -c -fast -w verlet.f
ifort -c -fast -w version.f
ifort -c -fast -w vibbig.f
ifort -c -fast -w vibrate.f
ifort -c -fast -w vibrot.f
ifort -c -fast -w volume.f
ifort -c -fast -w xtalfit.f
ifort -c -fast -w xtalmin.f
ifort -c -fast -w xyzatm.f
ifort -c -fast -w xyzedit.f
ifort -c -fast -w xyzint.f
ifort -c -fast -w xyzpdb.f
ifort -c -fast -w xyzsybyl.f
ifort -c -fast -w zatom.f
