#
#
#  ###################################################################
#  ##                                                               ##
#  ##  compile.make  --  compile all the TINKER modules for OpenMP  ##
#  ##          (Intel Fortran Compiler for Linux Version)           ##
#  ##                                                               ##
#  ###################################################################
#
#
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar active.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar alchemy.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar analysis.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar analyze.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar angles.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar anneal.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar archive.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar attach.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar basefile.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar beeman.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar bicubic.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar bitors.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar bonds.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar born.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar bounds.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar bspline.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar calendar.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar center.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar chkpole.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar chkring.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar chkxyz.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar cholesky.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar clock.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar cluster.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar column.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar command.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar connect.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar connolly.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar control.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar correlate.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar crystal.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar cspline.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar cutoffs.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar deflate.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar delete.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar diagq.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar diffeq.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar diffuse.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar distgeom.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar document.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar dynamic.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eangang.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eangang1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eangang2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eangang3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eangle.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eangle1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eangle2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eangle3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ebond.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ebond1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ebond2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ebond3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ebuck.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ebuck1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ebuck2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ebuck3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar echarge.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar echarge1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar echarge2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar echarge3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar echgdpl.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar echgdpl1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar echgdpl2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar echgdpl3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar edipole.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar edipole1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar edipole2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar edipole3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar egauss.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar egauss1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar egauss2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar egauss3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar egeom.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar egeom1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar egeom2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar egeom3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ehal.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ehal1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ehal2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ehal3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eimprop.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eimprop1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eimprop2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eimprop3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eimptor.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eimptor1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eimptor2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eimptor3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar elj.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar elj1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar elj2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar elj3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar embed.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar emetal.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar emetal1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar emetal2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar emetal3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar emm3hb.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar emm3hb1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar emm3hb2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar emm3hb3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar empole.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar empole1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar empole2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar empole3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar energy.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eopbend.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eopbend1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eopbend2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eopbend3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eopdist.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eopdist1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eopdist2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eopdist3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar epitors.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar epitors1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar epitors2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar epitors3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar erf.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar erxnfld.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar erxnfld1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar erxnfld2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar erxnfld3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar esolv.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar esolv1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar esolv2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar esolv3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar estrbnd.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar estrbnd1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar estrbnd2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar estrbnd3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar estrtor.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar estrtor1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar estrtor2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar estrtor3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar etors.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar etors1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar etors2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar etors3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar etortor.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar etortor1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar etortor2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar etortor3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eurey.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eurey1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eurey2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar eurey3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar evcorr.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar extra.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar extra1.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar extra2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar extra3.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar fatal.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar fft3d.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar fftpack.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar field.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar final.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar flatten.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar freeunit.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar gda.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar geometry.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar getime.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar getint.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar getkey.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar getmol2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar getnumb.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar getpdb.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar getprm.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar getref.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar getstring.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar gettext.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar getword.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar getxyz.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar gradient.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar gradrgd.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar gradrot.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar groups.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar grpline.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar gyrate.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar hessian.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar hessrgd.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar hessrot.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar hybrid.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar image.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar impose.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar induce.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar inertia.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar initial.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar initprm.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar initres.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar initrot.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar insert.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar intedit.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar intxyz.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar invbeta.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar invert.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar jacobi.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kangang.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kangle.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar katom.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kbond.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kcharge.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kdipole.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kewald.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kgeom.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kimprop.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kimptor.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kinetic.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kmetal.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kmpole.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kopbend.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kopdist.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar korbit.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kpitors.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kpolar.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ksolv.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kstrbnd.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kstrtor.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ktors.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ktortor.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kurey.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar kvdw.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar lattice.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar lbfgs.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar lights.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar makeint.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar makepdb.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar makeref.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar makexyz.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar maxwell.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar mdinit.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar mdrest.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar mdsave.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar mdstat.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar mechanic.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar merge.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar minimize.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar minirot.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar minrigid.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar molecule.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar moments.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar monte.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar mutate.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar nblist.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar newton.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar newtrot.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar nextarg.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar nexttext.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar nspline.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar nucleic.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar number.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar numeral.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar numgrad.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar ocvm.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar openend.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar optimize.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar optirot.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar optrigid.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar optsave.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar orbital.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar orient.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar orthog.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar overlap.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar path.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar pdbxyz.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar piscf.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar pmestuff.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar pmpb.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar polarize.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar poledit.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar polymer.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar potential.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar precise.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar pressure.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar prmedit.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar prmkey.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar promo.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar protein.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar prtdyn.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar prterr.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar prtint.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar prtmol2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar prtpdb.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar prtprm.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar prtseq.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar prtxyz.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar pss.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar pssrigid.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar pssrot.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar quatfit.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar radial.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar random.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar rattle.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar readdyn.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar readgau.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar readint.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar readmol2.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar readpdb.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar readprm.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar readseq.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar readxyz.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar replica.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar rgdstep.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar rings.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar rmsfit.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar rotlist.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar rotpole.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar saddle.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar scan.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar sdstep.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar search.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar server.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar setime.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar shakeup.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar sigmoid.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar sktstuff.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar sniffer.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar sort.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar spacefill.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar spectrum.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar square.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar suffix.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar superpose.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar surface.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar surfatom.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar switch.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar sybylxyz.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar temper.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar testgrad.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar testhess.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar testpair.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar testrot.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar timer.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar timerot.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar tncg.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar torphase.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar torque.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar torsions.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar trimtext.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar unitcell.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar valence.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar verlet.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar version.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar vibbig.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar vibrate.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar vibrot.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar volume.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar xtalfit.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar xtalmin.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar xyzatm.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar xyzedit.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar xyzint.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar xyzpdb.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar xyzsybyl.f
ifort -c -O3 -xHost -align all -assume cc_omp -no-prec-div -fno-omit-frame-pointer -openmp -recursive -auto-scalar zatom.f
