#
#
#  #################################################################
#  ##                                                             ##
#  ##  compopt.make  --  optimized compile of the TINKER modules  ##
#  ##          (Intel Fortran Compiler for Linux Version)         ##
#  ##                                                             ##
#  #################################################################
#
#
ifort -c -fast active.f
ifort -c -fast alchemy.f
ifort -c -fast analysis.f
ifort -c -fast analyze.f
ifort -c -fast angles.f
ifort -c -fast anneal.f
ifort -c -fast archive.f
ifort -c -fast attach.f
ifort -c -fast basefile.f
ifort -c -fast beeman.f
ifort -c -fast bicubic.f
ifort -c -fast bitors.f
ifort -c -fast bonds.f
ifort -c -fast born.f
ifort -c -fast bounds.f
ifort -c -fast bussi.f
ifort -c -fast calendar.f
ifort -c -fast center.f
ifort -c -fast chkpole.f
ifort -c -fast chkring.f
ifort -c -fast chkxyz.f
ifort -c -fast cholesky.f
ifort -c -fast clock.f
ifort -c -fast cluster.f
ifort -c -fast column.f
ifort -c -fast command.f
ifort -c -fast connect.f
ifort -c -fast connolly.f
ifort -c -fast control.f
ifort -c -fast correlate.f
ifort -c -fast crystal.f
ifort -c -fast cspline.f
ifort -c -fast cutoffs.f
ifort -c -fast deflate.f
ifort -c -fast delete.f
ifort -c -fast diagq.f
ifort -c -fast diffeq.f
ifort -c -fast diffuse.f
ifort -c -fast distgeom.f
ifort -c -fast document.f
ifort -c -fast dynamic.f
ifort -c -fast eangang.f
ifort -c -fast eangang1.f
ifort -c -fast eangang2.f
ifort -c -fast eangang3.f
ifort -c -fast eangle.f
ifort -c -fast eangle1.f
ifort -c -fast eangle2.f
ifort -c -fast eangle3.f
ifort -c -fast ebond.f
ifort -c -fast ebond1.f
ifort -c -fast ebond2.f
ifort -c -fast ebond3.f
ifort -c -fast ebuck.f
ifort -c -fast ebuck1.f
ifort -c -fast ebuck2.f
ifort -c -fast ebuck3.f
ifort -c -fast echarge.f
ifort -c -fast echarge1.f
ifort -c -fast echarge2.f
ifort -c -fast echarge3.f
ifort -c -fast echgdpl.f
ifort -c -fast echgdpl1.f
ifort -c -fast echgdpl2.f
ifort -c -fast echgdpl3.f
ifort -c -fast edipole.f
ifort -c -fast edipole1.f
ifort -c -fast edipole2.f
ifort -c -fast edipole3.f
ifort -c -fast egauss.f
ifort -c -fast egauss1.f
ifort -c -fast egauss2.f
ifort -c -fast egauss3.f
ifort -c -fast egeom.f
ifort -c -fast egeom1.f
ifort -c -fast egeom2.f
ifort -c -fast egeom3.f
ifort -c -fast ehal.f
ifort -c -fast ehal1.f
ifort -c -fast ehal2.f
ifort -c -fast ehal3.f
ifort -c -fast eimprop.f
ifort -c -fast eimprop1.f
ifort -c -fast eimprop2.f
ifort -c -fast eimprop3.f
ifort -c -fast eimptor.f
ifort -c -fast eimptor1.f
ifort -c -fast eimptor2.f
ifort -c -fast eimptor3.f
ifort -c -fast elj.f
ifort -c -fast elj1.f
ifort -c -fast elj2.f
ifort -c -fast elj3.f
ifort -c -fast embed.f
ifort -c -fast emetal.f
ifort -c -fast emetal1.f
ifort -c -fast emetal2.f
ifort -c -fast emetal3.f
ifort -c -fast emm3hb.f
ifort -c -fast emm3hb1.f
ifort -c -fast emm3hb2.f
ifort -c -fast emm3hb3.f
ifort -c -fast empole.f
ifort -c -fast empole1.f
ifort -c -fast empole2.f
ifort -c -fast empole3.f
ifort -c -fast energy.f
ifort -c -fast eopbend.f
ifort -c -fast eopbend1.f
ifort -c -fast eopbend2.f
ifort -c -fast eopbend3.f
ifort -c -fast eopdist.f
ifort -c -fast eopdist1.f
ifort -c -fast eopdist2.f
ifort -c -fast eopdist3.f
ifort -c -fast epitors.f
ifort -c -fast epitors1.f
ifort -c -fast epitors2.f
ifort -c -fast epitors3.f
ifort -c -fast erf.f
ifort -c -fast erxnfld.f
ifort -c -fast erxnfld1.f
ifort -c -fast erxnfld2.f
ifort -c -fast erxnfld3.f
ifort -c -fast esolv.f
ifort -c -fast esolv1.f
ifort -c -fast esolv2.f
ifort -c -fast esolv3.f
ifort -c -fast estrbnd.f
ifort -c -fast estrbnd1.f
ifort -c -fast estrbnd2.f
ifort -c -fast estrbnd3.f
ifort -c -fast estrtor.f
ifort -c -fast estrtor1.f
ifort -c -fast estrtor2.f
ifort -c -fast estrtor3.f
ifort -c -fast etors.f
ifort -c -fast etors1.f
ifort -c -fast etors2.f
ifort -c -fast etors3.f
ifort -c -fast etortor.f
ifort -c -fast etortor1.f
ifort -c -fast etortor2.f
ifort -c -fast etortor3.f
ifort -c -fast eurey.f
ifort -c -fast eurey1.f
ifort -c -fast eurey2.f
ifort -c -fast eurey3.f
ifort -c -fast evcorr.f
ifort -c -fast extra.f
ifort -c -fast extra1.f
ifort -c -fast extra2.f
ifort -c -fast extra3.f
ifort -c -fast fatal.f
ifort -c -fast fft3d.f
ifort -c -fast fftpack.f
ifort -c -fast field.f
ifort -c -fast final.f
ifort -c -fast flatten.f
ifort -c -fast freeunit.f
ifort -c -fast gda.f
ifort -c -fast geometry.f
ifort -c -fast getint.f
ifort -c -fast getkey.f
ifort -c -fast getmol2.f
ifort -c -fast getnumb.f
ifort -c -fast getpdb.f
ifort -c -fast getprm.f
ifort -c -fast getref.f
ifort -c -fast getstring.f
ifort -c -fast gettext.f
ifort -c -fast getword.f
ifort -c -fast getxyz.f
ifort -c -fast ghmcstep.f
ifort -c -fast gradient.f
ifort -c -fast gradrgd.f
ifort -c -fast gradrot.f
ifort -c -fast groups.f
ifort -c -fast grpline.f
ifort -c -fast gyrate.f
ifort -c -fast hessian.f
ifort -c -fast hessrgd.f
ifort -c -fast hessrot.f
ifort -c -fast hybrid.f
ifort -c -fast image.f
ifort -c -fast impose.f
ifort -c -fast induce.f
ifort -c -fast inertia.f
ifort -c -fast initial.f
ifort -c -fast initprm.f
ifort -c -fast initres.f
ifort -c -fast initrot.f
ifort -c -fast insert.f
ifort -c -fast intedit.f
ifort -c -fast intxyz.f
ifort -c -fast invbeta.f
ifort -c -fast invert.f
ifort -c -fast jacobi.f
ifort -c -fast kangang.f
ifort -c -fast kangle.f
ifort -c -fast katom.f
ifort -c -fast kbond.f
ifort -c -fast kcharge.f
ifort -c -fast kdipole.f
ifort -c -fast kewald.f
ifort -c -fast kgeom.f
ifort -c -fast kimprop.f
ifort -c -fast kimptor.f
ifort -c -fast kinetic.f
ifort -c -fast kmetal.f
ifort -c -fast kmpole.f
ifort -c -fast kopbend.f
ifort -c -fast kopdist.f
ifort -c -fast korbit.f
ifort -c -fast kpitors.f
ifort -c -fast kpolar.f
ifort -c -fast ksolv.f
ifort -c -fast kstrbnd.f
ifort -c -fast kstrtor.f
ifort -c -fast ktors.f
ifort -c -fast ktortor.f
ifort -c -fast kurey.f
ifort -c -fast kvdw.f
ifort -c -fast lattice.f
ifort -c -fast lbfgs.f
ifort -c -fast lights.f
ifort -c -fast makeint.f
ifort -c -fast makeref.f
ifort -c -fast makexyz.f
ifort -c -fast maxwell.f
ifort -c -fast mdinit.f
ifort -c -fast mdrest.f
ifort -c -fast mdsave.f
ifort -c -fast mdstat.f
ifort -c -fast mechanic.f
ifort -c -fast merge.f
ifort -c -fast minimize.f
ifort -c -fast minirot.f
ifort -c -fast minrigid.f
ifort -c -fast molecule.f
ifort -c -fast moments.f
ifort -c -fast monte.f
ifort -c -fast mutate.f
ifort -c -fast nblist.f
ifort -c -fast newton.f
ifort -c -fast newtrot.f
ifort -c -fast nextarg.f
ifort -c -fast nexttext.f
ifort -c -fast nose.f
ifort -c -fast nspline.f
ifort -c -fast nucleic.f
ifort -c -fast number.f
ifort -c -fast numeral.f
ifort -c -fast numgrad.f
ifort -c -fast ocvm.f
ifort -c -fast openend.f
ifort -c -fast optimize.f
ifort -c -fast optirot.f
ifort -c -fast optrigid.f
ifort -c -fast optsave.f
ifort -c -fast orbital.f
ifort -c -fast orient.f
ifort -c -fast orthog.f
ifort -c -fast overlap.f
ifort -c -fast path.f
ifort -c -fast pdbxyz.f
ifort -c -fast picalc.f
ifort -c -fast pmestuff.f
ifort -c -fast pmpb.f
ifort -c -fast polarize.f
ifort -c -fast poledit.f
ifort -c -fast polymer.f
ifort -c -fast potential.f
ifort -c -fast precise.f
ifort -c -fast pressure.f
ifort -c -fast prmedit.f
ifort -c -fast prmkey.f
ifort -c -fast promo.f
ifort -c -fast protein.f
ifort -c -fast prtdyn.f
ifort -c -fast prterr.f
ifort -c -fast prtint.f
ifort -c -fast prtmol2.f
ifort -c -fast prtpdb.f
ifort -c -fast prtprm.f
ifort -c -fast prtseq.f
ifort -c -fast prtxyz.f
ifort -c -fast pss.f
ifort -c -fast pssrigid.f
ifort -c -fast pssrot.f
ifort -c -fast quatfit.f
ifort -c -fast radial.f
ifort -c -fast random.f
ifort -c -fast rattle.f
ifort -c -fast readdyn.f
ifort -c -fast readgau.f
ifort -c -fast readint.f
ifort -c -fast readmol2.f
ifort -c -fast readpdb.f
ifort -c -fast readprm.f
ifort -c -fast readseq.f
ifort -c -fast readxyz.f
ifort -c -fast replica.f
ifort -c -fast respa.f
ifort -c -fast rgdstep.f
ifort -c -fast rings.f
ifort -c -fast rmsfit.f
ifort -c -fast rotlist.f
ifort -c -fast rotpole.f
ifort -c -fast saddle.f
ifort -c -fast scan.f
ifort -c -fast sdstep.f
ifort -c -fast search.f
ifort -c -fast server.f
ifort -c -fast shakeup.f
ifort -c -fast sigmoid.f
ifort -c -fast sktstuff.f
ifort -c -fast sniffer.f
ifort -c -fast sort.f
ifort -c -fast spacefill.f
ifort -c -fast spectrum.f
ifort -c -fast square.f
ifort -c -fast suffix.f
ifort -c -fast superpose.f
ifort -c -fast surface.f
ifort -c -fast surfatom.f
ifort -c -fast switch.f
ifort -c -fast sybylxyz.f
ifort -c -fast temper.f
ifort -c -fast testgrad.f
ifort -c -fast testhess.f
ifort -c -fast testpair.f
ifort -c -fast testrot.f
ifort -c -fast timer.f
ifort -c -fast timerot.f
ifort -c -fast tncg.f
ifort -c -fast torphase.f
ifort -c -fast torque.f
ifort -c -fast torsfit.f
ifort -c -fast torsions.f
ifort -c -fast trimtext.f
ifort -c -fast unitcell.f
ifort -c -fast valence.f
ifort -c -fast verlet.f
ifort -c -fast version.f
ifort -c -fast vibbig.f
ifort -c -fast vibrate.f
ifort -c -fast vibrot.f
ifort -c -fast volume.f
ifort -c -fast xtalfit.f
ifort -c -fast xtalmin.f
ifort -c -fast xyzatm.f
ifort -c -fast xyzedit.f
ifort -c -fast xyzint.f
ifort -c -fast xyzpdb.f
ifort -c -fast xyzsybyl.f
ifort -c -fast zatom.f
