#pragma once

#include "macro.hh"

namespace tinker { namespace dlmda {
extern int& elmdaexp;
extern int& elmdainvn;
extern int& emdtexp;
extern int& epdtexp;
extern int& evdtexp;
extern int& plmdaexp;
extern int& plmdainvn;
extern int& vlmdaexp;
extern int& vlmdainvn;
extern double& d2edl2;
extern double& d2eldlmda2;
extern double& d2emdl2;
extern double& d2epdl2;
extern double& d2evdl2;
extern double& d2pldlmda2;
extern double& d2vldlmda2;
extern double& dedl;
extern double& deldlmda;
extern double& demdl;
extern double& depdl;
extern double& devdl;
extern double& dpldlmda;
extern double& dvldlmda;
extern double& elmdainveps;
extern double& plmdainveps;
extern double& qntelmda0;
extern double& qntelmda1;
extern double& qntplmda0;
extern double& qntplmda1;
extern double& qntvlmda0;
extern double& qntvlmda1;
extern double& relstg1lmda0;
extern double& relstg1lmda1;
extern double& relstg2lmda0;
extern double& relstg2lmda1;
extern double& vlmdainveps;
extern double (&demvirdl)[3][3];
extern double (&depvirdl)[3][3];
extern double (&devvirdl)[3][3];
extern double (&dvirdl)[3][3];
extern double*& abflxorig;
extern double*& aflxorig;
extern double*& bdplorig;
extern double*& bflxorig;
extern double*& dfmdl;
extern double*& dfpdl;
extern double*& dfsumdl;
extern double*& dfvdl;
extern double*& lcmp;
extern double*& lcphi;
extern double*& lfmp;
extern double*& lfphi;
extern double*& lqgrid;
extern double*& pchg0orig;
extern double*& pchgorig;
extern double*& pcoreorig;
extern double*& polarityorig;
extern double*& poleorig;
extern double*& pval0orig;
extern double*& pvalorig;
extern int& relstagemix;
extern int& use_dlmda;
extern int& use_ele4f;
extern int& use_ele4i;
extern int& use_elmdamap;
extern int& use_emdt;
extern int& use_epdt;
extern int& use_evdt;
extern int& use_meta;
extern int& use_metadyn;
extern int& use_ost;
extern int& use_ostdyn;
extern int& use_plmda;
extern int& use_plmdamap;
extern int& use_pol4f;
extern int& use_pol4i;
extern int& use_relstage;
extern int& use_ti;
extern int& use_vdw4f;
extern int& use_vdw4i;
extern int& use_vlmdamap;
extern int*& douindorig;
extern char (&elmdamap)[3];
extern char (&plmdamap)[3];
extern char (&vlmdamap)[3];
extern char (&lmdaengymode)[4];
extern char (&lmdasampmode)[4];
extern char (&relstage)[4];

#ifdef TINKER_FORTRAN_MODULE_CPP
extern "C" int TINKER_MOD(dlmda, elmdaexp);
extern "C" int TINKER_MOD(dlmda, elmdainvn);
extern "C" int TINKER_MOD(dlmda, emdtexp);
extern "C" int TINKER_MOD(dlmda, epdtexp);
extern "C" int TINKER_MOD(dlmda, evdtexp);
extern "C" int TINKER_MOD(dlmda, plmdaexp);
extern "C" int TINKER_MOD(dlmda, plmdainvn);
extern "C" int TINKER_MOD(dlmda, vlmdaexp);
extern "C" int TINKER_MOD(dlmda, vlmdainvn);
extern "C" double TINKER_MOD(dlmda, d2edl2);
extern "C" double TINKER_MOD(dlmda, d2eldlmda2);
extern "C" double TINKER_MOD(dlmda, d2emdl2);
extern "C" double TINKER_MOD(dlmda, d2epdl2);
extern "C" double TINKER_MOD(dlmda, d2evdl2);
extern "C" double TINKER_MOD(dlmda, d2pldlmda2);
extern "C" double TINKER_MOD(dlmda, d2vldlmda2);
extern "C" double TINKER_MOD(dlmda, dedl);
extern "C" double TINKER_MOD(dlmda, deldlmda);
extern "C" double TINKER_MOD(dlmda, demdl);
extern "C" double TINKER_MOD(dlmda, depdl);
extern "C" double TINKER_MOD(dlmda, devdl);
extern "C" double TINKER_MOD(dlmda, dpldlmda);
extern "C" double TINKER_MOD(dlmda, dvldlmda);
extern "C" double TINKER_MOD(dlmda, elmdainveps);
extern "C" double TINKER_MOD(dlmda, plmdainveps);
extern "C" double TINKER_MOD(dlmda, qntelmda0);
extern "C" double TINKER_MOD(dlmda, qntelmda1);
extern "C" double TINKER_MOD(dlmda, qntplmda0);
extern "C" double TINKER_MOD(dlmda, qntplmda1);
extern "C" double TINKER_MOD(dlmda, qntvlmda0);
extern "C" double TINKER_MOD(dlmda, qntvlmda1);
extern "C" double TINKER_MOD(dlmda, relstg1lmda0);
extern "C" double TINKER_MOD(dlmda, relstg1lmda1);
extern "C" double TINKER_MOD(dlmda, relstg2lmda0);
extern "C" double TINKER_MOD(dlmda, relstg2lmda1);
extern "C" double TINKER_MOD(dlmda, vlmdainveps);
extern "C" double TINKER_MOD(dlmda, demvirdl)[3][3];
extern "C" double TINKER_MOD(dlmda, depvirdl)[3][3];
extern "C" double TINKER_MOD(dlmda, devvirdl)[3][3];
extern "C" double TINKER_MOD(dlmda, dvirdl)[3][3];
extern "C" double* TINKER_MOD(dlmda, abflxorig);
extern "C" double* TINKER_MOD(dlmda, aflxorig);
extern "C" double* TINKER_MOD(dlmda, bdplorig);
extern "C" double* TINKER_MOD(dlmda, bflxorig);
extern "C" double* TINKER_MOD(dlmda, dfmdl);
extern "C" double* TINKER_MOD(dlmda, dfpdl);
extern "C" double* TINKER_MOD(dlmda, dfsumdl);
extern "C" double* TINKER_MOD(dlmda, dfvdl);
extern "C" double* TINKER_MOD(dlmda, lcmp);
extern "C" double* TINKER_MOD(dlmda, lcphi);
extern "C" double* TINKER_MOD(dlmda, lfmp);
extern "C" double* TINKER_MOD(dlmda, lfphi);
extern "C" double* TINKER_MOD(dlmda, lqgrid);
extern "C" double* TINKER_MOD(dlmda, pchg0orig);
extern "C" double* TINKER_MOD(dlmda, pchgorig);
extern "C" double* TINKER_MOD(dlmda, pcoreorig);
extern "C" double* TINKER_MOD(dlmda, polarityorig);
extern "C" double* TINKER_MOD(dlmda, poleorig);
extern "C" double* TINKER_MOD(dlmda, pval0orig);
extern "C" double* TINKER_MOD(dlmda, pvalorig);
extern "C" int TINKER_MOD(dlmda, relstagemix);
extern "C" int TINKER_MOD(dlmda, use_dlmda);
extern "C" int TINKER_MOD(dlmda, use_ele4f);
extern "C" int TINKER_MOD(dlmda, use_ele4i);
extern "C" int TINKER_MOD(dlmda, use_elmdamap);
extern "C" int TINKER_MOD(dlmda, use_emdt);
extern "C" int TINKER_MOD(dlmda, use_epdt);
extern "C" int TINKER_MOD(dlmda, use_evdt);
extern "C" int TINKER_MOD(dlmda, use_meta);
extern "C" int TINKER_MOD(dlmda, use_metadyn);
extern "C" int TINKER_MOD(dlmda, use_ost);
extern "C" int TINKER_MOD(dlmda, use_ostdyn);
extern "C" int TINKER_MOD(dlmda, use_plmda);
extern "C" int TINKER_MOD(dlmda, use_plmdamap);
extern "C" int TINKER_MOD(dlmda, use_pol4f);
extern "C" int TINKER_MOD(dlmda, use_pol4i);
extern "C" int TINKER_MOD(dlmda, use_relstage);
extern "C" int TINKER_MOD(dlmda, use_ti);
extern "C" int TINKER_MOD(dlmda, use_vdw4f);
extern "C" int TINKER_MOD(dlmda, use_vdw4i);
extern "C" int TINKER_MOD(dlmda, use_vlmdamap);
extern "C" int* TINKER_MOD(dlmda, douindorig);
extern "C" char TINKER_MOD(dlmda, elmdamap)[3];
extern "C" char TINKER_MOD(dlmda, plmdamap)[3];
extern "C" char TINKER_MOD(dlmda, vlmdamap)[3];
extern "C" char TINKER_MOD(dlmda, lmdaengymode)[4];
extern "C" char TINKER_MOD(dlmda, lmdasampmode)[4];
extern "C" char TINKER_MOD(dlmda, relstage)[4];

int& elmdaexp = TINKER_MOD(dlmda, elmdaexp);
int& elmdainvn = TINKER_MOD(dlmda, elmdainvn);
int& emdtexp = TINKER_MOD(dlmda, emdtexp);
int& epdtexp = TINKER_MOD(dlmda, epdtexp);
int& evdtexp = TINKER_MOD(dlmda, evdtexp);
int& plmdaexp = TINKER_MOD(dlmda, plmdaexp);
int& plmdainvn = TINKER_MOD(dlmda, plmdainvn);
int& vlmdaexp = TINKER_MOD(dlmda, vlmdaexp);
int& vlmdainvn = TINKER_MOD(dlmda, vlmdainvn);
double& d2edl2 = TINKER_MOD(dlmda, d2edl2);
double& d2eldlmda2 = TINKER_MOD(dlmda, d2eldlmda2);
double& d2emdl2 = TINKER_MOD(dlmda, d2emdl2);
double& d2epdl2 = TINKER_MOD(dlmda, d2epdl2);
double& d2evdl2 = TINKER_MOD(dlmda, d2evdl2);
double& d2pldlmda2 = TINKER_MOD(dlmda, d2pldlmda2);
double& d2vldlmda2 = TINKER_MOD(dlmda, d2vldlmda2);
double& dedl = TINKER_MOD(dlmda, dedl);
double& deldlmda = TINKER_MOD(dlmda, deldlmda);
double& demdl = TINKER_MOD(dlmda, demdl);
double& depdl = TINKER_MOD(dlmda, depdl);
double& devdl = TINKER_MOD(dlmda, devdl);
double& dpldlmda = TINKER_MOD(dlmda, dpldlmda);
double& dvldlmda = TINKER_MOD(dlmda, dvldlmda);
double& elmdainveps = TINKER_MOD(dlmda, elmdainveps);
double& plmdainveps = TINKER_MOD(dlmda, plmdainveps);
double& qntelmda0 = TINKER_MOD(dlmda, qntelmda0);
double& qntelmda1 = TINKER_MOD(dlmda, qntelmda1);
double& qntplmda0 = TINKER_MOD(dlmda, qntplmda0);
double& qntplmda1 = TINKER_MOD(dlmda, qntplmda1);
double& qntvlmda0 = TINKER_MOD(dlmda, qntvlmda0);
double& qntvlmda1 = TINKER_MOD(dlmda, qntvlmda1);
double& relstg1lmda0 = TINKER_MOD(dlmda, relstg1lmda0);
double& relstg1lmda1 = TINKER_MOD(dlmda, relstg1lmda1);
double& relstg2lmda0 = TINKER_MOD(dlmda, relstg2lmda0);
double& relstg2lmda1 = TINKER_MOD(dlmda, relstg2lmda1);
double& vlmdainveps = TINKER_MOD(dlmda, vlmdainveps);
double (&demvirdl)[3][3] = TINKER_MOD(dlmda, demvirdl);
double (&depvirdl)[3][3] = TINKER_MOD(dlmda, depvirdl);
double (&devvirdl)[3][3] = TINKER_MOD(dlmda, devvirdl);
double (&dvirdl)[3][3] = TINKER_MOD(dlmda, dvirdl);
double*& abflxorig = TINKER_MOD(dlmda, abflxorig);
double*& aflxorig = TINKER_MOD(dlmda, aflxorig);
double*& bdplorig = TINKER_MOD(dlmda, bdplorig);
double*& bflxorig = TINKER_MOD(dlmda, bflxorig);
double*& dfmdl = TINKER_MOD(dlmda, dfmdl);
double*& dfpdl = TINKER_MOD(dlmda, dfpdl);
double*& dfsumdl = TINKER_MOD(dlmda, dfsumdl);
double*& dfvdl = TINKER_MOD(dlmda, dfvdl);
double*& lcmp = TINKER_MOD(dlmda, lcmp);
double*& lcphi = TINKER_MOD(dlmda, lcphi);
double*& lfmp = TINKER_MOD(dlmda, lfmp);
double*& lfphi = TINKER_MOD(dlmda, lfphi);
double*& lqgrid = TINKER_MOD(dlmda, lqgrid);
double*& pchg0orig = TINKER_MOD(dlmda, pchg0orig);
double*& pchgorig = TINKER_MOD(dlmda, pchgorig);
double*& pcoreorig = TINKER_MOD(dlmda, pcoreorig);
double*& polarityorig = TINKER_MOD(dlmda, polarityorig);
double*& poleorig = TINKER_MOD(dlmda, poleorig);
double*& pval0orig = TINKER_MOD(dlmda, pval0orig);
double*& pvalorig = TINKER_MOD(dlmda, pvalorig);
int& relstagemix = TINKER_MOD(dlmda, relstagemix);
int& use_dlmda = TINKER_MOD(dlmda, use_dlmda);
int& use_ele4f = TINKER_MOD(dlmda, use_ele4f);
int& use_ele4i = TINKER_MOD(dlmda, use_ele4i);
int& use_elmdamap = TINKER_MOD(dlmda, use_elmdamap);
int& use_emdt = TINKER_MOD(dlmda, use_emdt);
int& use_epdt = TINKER_MOD(dlmda, use_epdt);
int& use_evdt = TINKER_MOD(dlmda, use_evdt);
int& use_meta = TINKER_MOD(dlmda, use_meta);
int& use_metadyn = TINKER_MOD(dlmda, use_metadyn);
int& use_ost = TINKER_MOD(dlmda, use_ost);
int& use_ostdyn = TINKER_MOD(dlmda, use_ostdyn);
int& use_plmda = TINKER_MOD(dlmda, use_plmda);
int& use_plmdamap = TINKER_MOD(dlmda, use_plmdamap);
int& use_pol4f = TINKER_MOD(dlmda, use_pol4f);
int& use_pol4i = TINKER_MOD(dlmda, use_pol4i);
int& use_relstage = TINKER_MOD(dlmda, use_relstage);
int& use_ti = TINKER_MOD(dlmda, use_ti);
int& use_vdw4f = TINKER_MOD(dlmda, use_vdw4f);
int& use_vdw4i = TINKER_MOD(dlmda, use_vdw4i);
int& use_vlmdamap = TINKER_MOD(dlmda, use_vlmdamap);
int*& douindorig = TINKER_MOD(dlmda, douindorig);
char (&elmdamap)[3] = TINKER_MOD(dlmda, elmdamap);
char (&plmdamap)[3] = TINKER_MOD(dlmda, plmdamap);
char (&vlmdamap)[3] = TINKER_MOD(dlmda, vlmdamap);
char (&lmdaengymode)[4] = TINKER_MOD(dlmda, lmdaengymode);
char (&lmdasampmode)[4] = TINKER_MOD(dlmda, lmdasampmode);
char (&relstage)[4] = TINKER_MOD(dlmda, relstage);
#endif
} }
