#pragma once

#include "macro.hh"

namespace tinker { namespace dlmda {
extern int& emdtexp;
extern int& epdtexp;
extern int& evdtexp;
extern double& d2edl2;
extern double& d2eldlmda2;
extern double& d2emdl2;
extern double& d2epdl2;
extern double& d2evdl2;
extern double& d2pldlmda2;
extern double& d2vldlmda2;
extern double& dedl;
extern double& deldlmda;
extern double& demdl;
extern double& depdl;
extern double& devdl;
extern double& dpldlmda;
extern double& dvldlmda;
extern double& plambda;
extern double (&demvirdl)[3][3];
extern double (&depvirdl)[3][3];
extern double (&devvirdl)[3][3];
extern double (&dvirdl)[3][3];
extern double*& abflxorig;
extern double*& aflxorig;
extern double*& bdplorig;
extern double*& bflxorig;
extern double*& dfmdl;
extern double*& dfpdl;
extern double*& dfsumdl;
extern double*& dfvdl;
extern double*& lcmp;
extern double*& lcphi;
extern double*& lfmp;
extern double*& lfphi;
extern double*& lqgrid;
extern double*& pchg0orig;
extern double*& pchgorig;
extern double*& pcoreorig;
extern double*& polarityorig;
extern double*& poleorig;
extern double*& pval0orig;
extern double*& pvalorig;
extern int& use_dlmda;
extern int& use_emdt;
extern int& use_epdt;
extern int& use_evdt;
extern int& use_plmda;
extern int*& douindorig;

#ifdef TINKER_FORTRAN_MODULE_CPP
extern "C" int TINKER_MOD(dlmda, emdtexp);
extern "C" int TINKER_MOD(dlmda, epdtexp);
extern "C" int TINKER_MOD(dlmda, evdtexp);
extern "C" double TINKER_MOD(dlmda, d2edl2);
extern "C" double TINKER_MOD(dlmda, d2eldlmda2);
extern "C" double TINKER_MOD(dlmda, d2emdl2);
extern "C" double TINKER_MOD(dlmda, d2epdl2);
extern "C" double TINKER_MOD(dlmda, d2evdl2);
extern "C" double TINKER_MOD(dlmda, d2pldlmda2);
extern "C" double TINKER_MOD(dlmda, d2vldlmda2);
extern "C" double TINKER_MOD(dlmda, dedl);
extern "C" double TINKER_MOD(dlmda, deldlmda);
extern "C" double TINKER_MOD(dlmda, demdl);
extern "C" double TINKER_MOD(dlmda, depdl);
extern "C" double TINKER_MOD(dlmda, devdl);
extern "C" double TINKER_MOD(dlmda, dpldlmda);
extern "C" double TINKER_MOD(dlmda, dvldlmda);
extern "C" double TINKER_MOD(dlmda, plambda);
extern "C" double TINKER_MOD(dlmda, demvirdl)[3][3];
extern "C" double TINKER_MOD(dlmda, depvirdl)[3][3];
extern "C" double TINKER_MOD(dlmda, devvirdl)[3][3];
extern "C" double TINKER_MOD(dlmda, dvirdl)[3][3];
extern "C" double* TINKER_MOD(dlmda, abflxorig);
extern "C" double* TINKER_MOD(dlmda, aflxorig);
extern "C" double* TINKER_MOD(dlmda, bdplorig);
extern "C" double* TINKER_MOD(dlmda, bflxorig);
extern "C" double* TINKER_MOD(dlmda, dfmdl);
extern "C" double* TINKER_MOD(dlmda, dfpdl);
extern "C" double* TINKER_MOD(dlmda, dfsumdl);
extern "C" double* TINKER_MOD(dlmda, dfvdl);
extern "C" double* TINKER_MOD(dlmda, lcmp);
extern "C" double* TINKER_MOD(dlmda, lcphi);
extern "C" double* TINKER_MOD(dlmda, lfmp);
extern "C" double* TINKER_MOD(dlmda, lfphi);
extern "C" double* TINKER_MOD(dlmda, lqgrid);
extern "C" double* TINKER_MOD(dlmda, pchg0orig);
extern "C" double* TINKER_MOD(dlmda, pchgorig);
extern "C" double* TINKER_MOD(dlmda, pcoreorig);
extern "C" double* TINKER_MOD(dlmda, polarityorig);
extern "C" double* TINKER_MOD(dlmda, poleorig);
extern "C" double* TINKER_MOD(dlmda, pval0orig);
extern "C" double* TINKER_MOD(dlmda, pvalorig);
extern "C" int TINKER_MOD(dlmda, use_dlmda);
extern "C" int TINKER_MOD(dlmda, use_emdt);
extern "C" int TINKER_MOD(dlmda, use_epdt);
extern "C" int TINKER_MOD(dlmda, use_evdt);
extern "C" int TINKER_MOD(dlmda, use_plmda);
extern "C" int* TINKER_MOD(dlmda, douindorig);

int& emdtexp = TINKER_MOD(dlmda, emdtexp);
int& epdtexp = TINKER_MOD(dlmda, epdtexp);
int& evdtexp = TINKER_MOD(dlmda, evdtexp);
double& d2edl2 = TINKER_MOD(dlmda, d2edl2);
double& d2eldlmda2 = TINKER_MOD(dlmda, d2eldlmda2);
double& d2emdl2 = TINKER_MOD(dlmda, d2emdl2);
double& d2epdl2 = TINKER_MOD(dlmda, d2epdl2);
double& d2evdl2 = TINKER_MOD(dlmda, d2evdl2);
double& d2pldlmda2 = TINKER_MOD(dlmda, d2pldlmda2);
double& d2vldlmda2 = TINKER_MOD(dlmda, d2vldlmda2);
double& dedl = TINKER_MOD(dlmda, dedl);
double& deldlmda = TINKER_MOD(dlmda, deldlmda);
double& demdl = TINKER_MOD(dlmda, demdl);
double& depdl = TINKER_MOD(dlmda, depdl);
double& devdl = TINKER_MOD(dlmda, devdl);
double& dpldlmda = TINKER_MOD(dlmda, dpldlmda);
double& dvldlmda = TINKER_MOD(dlmda, dvldlmda);
double& plambda = TINKER_MOD(dlmda, plambda);
double (&demvirdl)[3][3] = TINKER_MOD(dlmda, demvirdl);
double (&depvirdl)[3][3] = TINKER_MOD(dlmda, depvirdl);
double (&devvirdl)[3][3] = TINKER_MOD(dlmda, devvirdl);
double (&dvirdl)[3][3] = TINKER_MOD(dlmda, dvirdl);
double*& abflxorig = TINKER_MOD(dlmda, abflxorig);
double*& aflxorig = TINKER_MOD(dlmda, aflxorig);
double*& bdplorig = TINKER_MOD(dlmda, bdplorig);
double*& bflxorig = TINKER_MOD(dlmda, bflxorig);
double*& dfmdl = TINKER_MOD(dlmda, dfmdl);
double*& dfpdl = TINKER_MOD(dlmda, dfpdl);
double*& dfsumdl = TINKER_MOD(dlmda, dfsumdl);
double*& dfvdl = TINKER_MOD(dlmda, dfvdl);
double*& lcmp = TINKER_MOD(dlmda, lcmp);
double*& lcphi = TINKER_MOD(dlmda, lcphi);
double*& lfmp = TINKER_MOD(dlmda, lfmp);
double*& lfphi = TINKER_MOD(dlmda, lfphi);
double*& lqgrid = TINKER_MOD(dlmda, lqgrid);
double*& pchg0orig = TINKER_MOD(dlmda, pchg0orig);
double*& pchgorig = TINKER_MOD(dlmda, pchgorig);
double*& pcoreorig = TINKER_MOD(dlmda, pcoreorig);
double*& polarityorig = TINKER_MOD(dlmda, polarityorig);
double*& poleorig = TINKER_MOD(dlmda, poleorig);
double*& pval0orig = TINKER_MOD(dlmda, pval0orig);
double*& pvalorig = TINKER_MOD(dlmda, pvalorig);
int& use_dlmda = TINKER_MOD(dlmda, use_dlmda);
int& use_emdt = TINKER_MOD(dlmda, use_emdt);
int& use_epdt = TINKER_MOD(dlmda, use_epdt);
int& use_evdt = TINKER_MOD(dlmda, use_evdt);
int& use_plmda = TINKER_MOD(dlmda, use_plmda);
int*& douindorig = TINKER_MOD(dlmda, douindorig);
#endif
} }
