#pragma once

#include "macro.hh"

namespace tinker { namespace dlmda {
extern int& elmdaapmn;
extern int& elmdaexp;
extern int& elmdainvn;
extern int& emdtexp;
extern int& epdtexp;
extern int& erelst0;
extern int& erelst1;
extern int& evdtexp;
extern int& lmdaintv;
extern int& lmdanpa;
extern int& lmdanpb;
extern int& lmdanpc;
extern int& lmdastep;
extern int& nlmda;
extern int& nlmdahist;
extern int& nlmdasave;
const int nrelsub = 5;
extern int& plmdaapmn;
extern int& plmdaexp;
extern int& plmdainvn;
extern int& prelst0;
extern int& prelst1;
const int rellig1 = 1;
const int rellig2 = 2;
const int relnone = 3;
extern int& sizelmdahist;
extern int& vlmdaapmn;
extern int& vlmdaexp;
extern int& vlmdainvn;
extern int& vrelst0;
extern int& vrelst1;
extern int*& lmdaihist;
extern double& d2edl2;
extern double& d2eldlmda2;
extern double& d2emdl2;
extern double& d2epdl2;
extern double& d2evdl2;
extern double& d2pldlmda2;
extern double& d2vldlmda2;
extern double& dedl;
extern double& dedlavg;
extern double& dedlstd;
extern double& deffdl;
extern double& deldlmda;
extern double& demdl;
extern double& depdl;
extern double& devdl;
extern double& dpldlmda;
extern double& dvldlmda;
extern double& elmdaapmrho;
extern double& elmdainveps;
extern double& lmdaavg;
extern double& lmdaddgdl;
extern double& lmdadeltag;
extern double& lmdadfdl;
extern double& lmdadt;
extern double& lmdafric;
extern double& lmdamass;
extern double& lmdaparatio;
extern double& lmdapbratio;
extern double& lmdapcratio;
extern double& lmdastd;
extern double& lmdathalpha;
extern double& lmdatheta;
extern double& lmdavbias;
extern double& lmdavtheta;
extern double& plmdaapmrho;
extern double& plmdainveps;
extern double& qntelmda0;
extern double& qntelmda1;
extern double& qntplmda0;
extern double& qntplmda1;
extern double& qntvlmda0;
extern double& qntvlmda1;
extern double& vlmdaapmrho;
extern double& vlmdainveps;
extern double& wlmda;
extern double& wlmda2;
extern double (&demvirdl)[3][3];
extern double (&depvirdl)[3][3];
extern double (&devvirdl)[3][3];
extern double (&dvirdl)[3][3];
extern double*& bdplorig;
extern double*& bflxorig;
extern double*& lmdafhist;
extern double*& lmdaflist;
extern double*& lmdafmean;
extern double*& lmdafsum;
extern double*& lmdafwt;
extern double*& lmdalhist;
extern double*& lmdallist;
extern double*& pchg0orig;
extern double*& pchgorig;
extern double*& pcoreorig;
extern double*& polarityorig;
extern double*& pval0orig;
extern double*& pvalorig;
extern double*& abflxorig;
extern double*& aflxorig;
extern double*& dfmdl;
extern double*& dfpdl;
extern double*& dfsumdl;
extern double*& dfvdl;
extern double*& lcmp;
extern double*& lcphi;
extern double*& lfmp;
extern double*& lfphi;
extern double*& poleorig;
extern double*& lqgrid;
extern int& lmdatrial;
extern int& use_abf;
extern int& use_abfdyn;
extern int& use_dlmda;
extern int& use_edlmda;
extern int& use_elmdamap;
extern int& use_emdt;
extern int& use_epdt;
extern int& use_evdt;
extern int& use_mainlmda;
extern int& use_meta;
extern int& use_metadyn;
extern int& use_ost;
extern int& use_ostdyn;
extern int& use_pdlmda;
extern int& use_plmda;
extern int& use_plmdamap;
extern int& use_relstage;
extern int& use_ti;
extern int& use_vdlmda;
extern int& use_vlmdamap;
extern int*& douindorig;
extern char (&elmdamap)[3];
extern char (&plmdamap)[3];
extern char (&vlmdamap)[3];
extern char (&lmdathmap)[3];
extern char (&lmdaengymode)[4];
extern char (&lmdasampmode)[4];
extern char (&relstage)[4];
extern char (&lmdasavefile)[240];

#ifdef TINKER_FORTRAN_MODULE_CPP
extern "C" int TINKER_MOD(dlmda, elmdaapmn);
extern "C" int TINKER_MOD(dlmda, elmdaexp);
extern "C" int TINKER_MOD(dlmda, elmdainvn);
extern "C" int TINKER_MOD(dlmda, emdtexp);
extern "C" int TINKER_MOD(dlmda, epdtexp);
extern "C" int TINKER_MOD(dlmda, erelst0);
extern "C" int TINKER_MOD(dlmda, erelst1);
extern "C" int TINKER_MOD(dlmda, evdtexp);
extern "C" int TINKER_MOD(dlmda, lmdaintv);
extern "C" int TINKER_MOD(dlmda, lmdanpa);
extern "C" int TINKER_MOD(dlmda, lmdanpb);
extern "C" int TINKER_MOD(dlmda, lmdanpc);
extern "C" int TINKER_MOD(dlmda, lmdastep);
extern "C" int TINKER_MOD(dlmda, nlmda);
extern "C" int TINKER_MOD(dlmda, nlmdahist);
extern "C" int TINKER_MOD(dlmda, nlmdasave);
extern "C" int TINKER_MOD(dlmda, plmdaapmn);
extern "C" int TINKER_MOD(dlmda, plmdaexp);
extern "C" int TINKER_MOD(dlmda, plmdainvn);
extern "C" int TINKER_MOD(dlmda, prelst0);
extern "C" int TINKER_MOD(dlmda, prelst1);
extern "C" int TINKER_MOD(dlmda, sizelmdahist);
extern "C" int TINKER_MOD(dlmda, vlmdaapmn);
extern "C" int TINKER_MOD(dlmda, vlmdaexp);
extern "C" int TINKER_MOD(dlmda, vlmdainvn);
extern "C" int TINKER_MOD(dlmda, vrelst0);
extern "C" int TINKER_MOD(dlmda, vrelst1);
extern "C" int* TINKER_MOD(dlmda, lmdaihist);
extern "C" double TINKER_MOD(dlmda, d2edl2);
extern "C" double TINKER_MOD(dlmda, d2eldlmda2);
extern "C" double TINKER_MOD(dlmda, d2emdl2);
extern "C" double TINKER_MOD(dlmda, d2epdl2);
extern "C" double TINKER_MOD(dlmda, d2evdl2);
extern "C" double TINKER_MOD(dlmda, d2pldlmda2);
extern "C" double TINKER_MOD(dlmda, d2vldlmda2);
extern "C" double TINKER_MOD(dlmda, dedl);
extern "C" double TINKER_MOD(dlmda, dedlavg);
extern "C" double TINKER_MOD(dlmda, dedlstd);
extern "C" double TINKER_MOD(dlmda, deffdl);
extern "C" double TINKER_MOD(dlmda, deldlmda);
extern "C" double TINKER_MOD(dlmda, demdl);
extern "C" double TINKER_MOD(dlmda, depdl);
extern "C" double TINKER_MOD(dlmda, devdl);
extern "C" double TINKER_MOD(dlmda, dpldlmda);
extern "C" double TINKER_MOD(dlmda, dvldlmda);
extern "C" double TINKER_MOD(dlmda, elmdaapmrho);
extern "C" double TINKER_MOD(dlmda, elmdainveps);
extern "C" double TINKER_MOD(dlmda, lmdaavg);
extern "C" double TINKER_MOD(dlmda, lmdaddgdl);
extern "C" double TINKER_MOD(dlmda, lmdadeltag);
extern "C" double TINKER_MOD(dlmda, lmdadfdl);
extern "C" double TINKER_MOD(dlmda, lmdadt);
extern "C" double TINKER_MOD(dlmda, lmdafric);
extern "C" double TINKER_MOD(dlmda, lmdamass);
extern "C" double TINKER_MOD(dlmda, lmdaparatio);
extern "C" double TINKER_MOD(dlmda, lmdapbratio);
extern "C" double TINKER_MOD(dlmda, lmdapcratio);
extern "C" double TINKER_MOD(dlmda, lmdastd);
extern "C" double TINKER_MOD(dlmda, lmdathalpha);
extern "C" double TINKER_MOD(dlmda, lmdatheta);
extern "C" double TINKER_MOD(dlmda, lmdavbias);
extern "C" double TINKER_MOD(dlmda, lmdavtheta);
extern "C" double TINKER_MOD(dlmda, plmdaapmrho);
extern "C" double TINKER_MOD(dlmda, plmdainveps);
extern "C" double TINKER_MOD(dlmda, qntelmda0);
extern "C" double TINKER_MOD(dlmda, qntelmda1);
extern "C" double TINKER_MOD(dlmda, qntplmda0);
extern "C" double TINKER_MOD(dlmda, qntplmda1);
extern "C" double TINKER_MOD(dlmda, qntvlmda0);
extern "C" double TINKER_MOD(dlmda, qntvlmda1);
extern "C" double TINKER_MOD(dlmda, vlmdaapmrho);
extern "C" double TINKER_MOD(dlmda, vlmdainveps);
extern "C" double TINKER_MOD(dlmda, wlmda);
extern "C" double TINKER_MOD(dlmda, wlmda2);
extern "C" double TINKER_MOD(dlmda, demvirdl)[3][3];
extern "C" double TINKER_MOD(dlmda, depvirdl)[3][3];
extern "C" double TINKER_MOD(dlmda, devvirdl)[3][3];
extern "C" double TINKER_MOD(dlmda, dvirdl)[3][3];
extern "C" double* TINKER_MOD(dlmda, bdplorig);
extern "C" double* TINKER_MOD(dlmda, bflxorig);
extern "C" double* TINKER_MOD(dlmda, lmdafhist);
extern "C" double* TINKER_MOD(dlmda, lmdaflist);
extern "C" double* TINKER_MOD(dlmda, lmdafmean);
extern "C" double* TINKER_MOD(dlmda, lmdafsum);
extern "C" double* TINKER_MOD(dlmda, lmdafwt);
extern "C" double* TINKER_MOD(dlmda, lmdalhist);
extern "C" double* TINKER_MOD(dlmda, lmdallist);
extern "C" double* TINKER_MOD(dlmda, pchg0orig);
extern "C" double* TINKER_MOD(dlmda, pchgorig);
extern "C" double* TINKER_MOD(dlmda, pcoreorig);
extern "C" double* TINKER_MOD(dlmda, polarityorig);
extern "C" double* TINKER_MOD(dlmda, pval0orig);
extern "C" double* TINKER_MOD(dlmda, pvalorig);
extern "C" double* TINKER_MOD(dlmda, abflxorig);
extern "C" double* TINKER_MOD(dlmda, aflxorig);
extern "C" double* TINKER_MOD(dlmda, dfmdl);
extern "C" double* TINKER_MOD(dlmda, dfpdl);
extern "C" double* TINKER_MOD(dlmda, dfsumdl);
extern "C" double* TINKER_MOD(dlmda, dfvdl);
extern "C" double* TINKER_MOD(dlmda, lcmp);
extern "C" double* TINKER_MOD(dlmda, lcphi);
extern "C" double* TINKER_MOD(dlmda, lfmp);
extern "C" double* TINKER_MOD(dlmda, lfphi);
extern "C" double* TINKER_MOD(dlmda, poleorig);
extern "C" double* TINKER_MOD(dlmda, lqgrid);
extern "C" int TINKER_MOD(dlmda, lmdatrial);
extern "C" int TINKER_MOD(dlmda, use_abf);
extern "C" int TINKER_MOD(dlmda, use_abfdyn);
extern "C" int TINKER_MOD(dlmda, use_dlmda);
extern "C" int TINKER_MOD(dlmda, use_edlmda);
extern "C" int TINKER_MOD(dlmda, use_elmdamap);
extern "C" int TINKER_MOD(dlmda, use_emdt);
extern "C" int TINKER_MOD(dlmda, use_epdt);
extern "C" int TINKER_MOD(dlmda, use_evdt);
extern "C" int TINKER_MOD(dlmda, use_mainlmda);
extern "C" int TINKER_MOD(dlmda, use_meta);
extern "C" int TINKER_MOD(dlmda, use_metadyn);
extern "C" int TINKER_MOD(dlmda, use_ost);
extern "C" int TINKER_MOD(dlmda, use_ostdyn);
extern "C" int TINKER_MOD(dlmda, use_pdlmda);
extern "C" int TINKER_MOD(dlmda, use_plmda);
extern "C" int TINKER_MOD(dlmda, use_plmdamap);
extern "C" int TINKER_MOD(dlmda, use_relstage);
extern "C" int TINKER_MOD(dlmda, use_ti);
extern "C" int TINKER_MOD(dlmda, use_vdlmda);
extern "C" int TINKER_MOD(dlmda, use_vlmdamap);
extern "C" int* TINKER_MOD(dlmda, douindorig);
extern "C" char TINKER_MOD(dlmda, elmdamap)[3];
extern "C" char TINKER_MOD(dlmda, plmdamap)[3];
extern "C" char TINKER_MOD(dlmda, vlmdamap)[3];
extern "C" char TINKER_MOD(dlmda, lmdathmap)[3];
extern "C" char TINKER_MOD(dlmda, lmdaengymode)[4];
extern "C" char TINKER_MOD(dlmda, lmdasampmode)[4];
extern "C" char TINKER_MOD(dlmda, relstage)[4];
extern "C" char TINKER_MOD(dlmda, lmdasavefile)[240];

int& elmdaapmn = TINKER_MOD(dlmda, elmdaapmn);
int& elmdaexp = TINKER_MOD(dlmda, elmdaexp);
int& elmdainvn = TINKER_MOD(dlmda, elmdainvn);
int& emdtexp = TINKER_MOD(dlmda, emdtexp);
int& epdtexp = TINKER_MOD(dlmda, epdtexp);
int& erelst0 = TINKER_MOD(dlmda, erelst0);
int& erelst1 = TINKER_MOD(dlmda, erelst1);
int& evdtexp = TINKER_MOD(dlmda, evdtexp);
int& lmdaintv = TINKER_MOD(dlmda, lmdaintv);
int& lmdanpa = TINKER_MOD(dlmda, lmdanpa);
int& lmdanpb = TINKER_MOD(dlmda, lmdanpb);
int& lmdanpc = TINKER_MOD(dlmda, lmdanpc);
int& lmdastep = TINKER_MOD(dlmda, lmdastep);
int& nlmda = TINKER_MOD(dlmda, nlmda);
int& nlmdahist = TINKER_MOD(dlmda, nlmdahist);
int& nlmdasave = TINKER_MOD(dlmda, nlmdasave);
int& plmdaapmn = TINKER_MOD(dlmda, plmdaapmn);
int& plmdaexp = TINKER_MOD(dlmda, plmdaexp);
int& plmdainvn = TINKER_MOD(dlmda, plmdainvn);
int& prelst0 = TINKER_MOD(dlmda, prelst0);
int& prelst1 = TINKER_MOD(dlmda, prelst1);
int& sizelmdahist = TINKER_MOD(dlmda, sizelmdahist);
int& vlmdaapmn = TINKER_MOD(dlmda, vlmdaapmn);
int& vlmdaexp = TINKER_MOD(dlmda, vlmdaexp);
int& vlmdainvn = TINKER_MOD(dlmda, vlmdainvn);
int& vrelst0 = TINKER_MOD(dlmda, vrelst0);
int& vrelst1 = TINKER_MOD(dlmda, vrelst1);
int*& lmdaihist = TINKER_MOD(dlmda, lmdaihist);
double& d2edl2 = TINKER_MOD(dlmda, d2edl2);
double& d2eldlmda2 = TINKER_MOD(dlmda, d2eldlmda2);
double& d2emdl2 = TINKER_MOD(dlmda, d2emdl2);
double& d2epdl2 = TINKER_MOD(dlmda, d2epdl2);
double& d2evdl2 = TINKER_MOD(dlmda, d2evdl2);
double& d2pldlmda2 = TINKER_MOD(dlmda, d2pldlmda2);
double& d2vldlmda2 = TINKER_MOD(dlmda, d2vldlmda2);
double& dedl = TINKER_MOD(dlmda, dedl);
double& dedlavg = TINKER_MOD(dlmda, dedlavg);
double& dedlstd = TINKER_MOD(dlmda, dedlstd);
double& deffdl = TINKER_MOD(dlmda, deffdl);
double& deldlmda = TINKER_MOD(dlmda, deldlmda);
double& demdl = TINKER_MOD(dlmda, demdl);
double& depdl = TINKER_MOD(dlmda, depdl);
double& devdl = TINKER_MOD(dlmda, devdl);
double& dpldlmda = TINKER_MOD(dlmda, dpldlmda);
double& dvldlmda = TINKER_MOD(dlmda, dvldlmda);
double& elmdaapmrho = TINKER_MOD(dlmda, elmdaapmrho);
double& elmdainveps = TINKER_MOD(dlmda, elmdainveps);
double& lmdaavg = TINKER_MOD(dlmda, lmdaavg);
double& lmdaddgdl = TINKER_MOD(dlmda, lmdaddgdl);
double& lmdadeltag = TINKER_MOD(dlmda, lmdadeltag);
double& lmdadfdl = TINKER_MOD(dlmda, lmdadfdl);
double& lmdadt = TINKER_MOD(dlmda, lmdadt);
double& lmdafric = TINKER_MOD(dlmda, lmdafric);
double& lmdamass = TINKER_MOD(dlmda, lmdamass);
double& lmdaparatio = TINKER_MOD(dlmda, lmdaparatio);
double& lmdapbratio = TINKER_MOD(dlmda, lmdapbratio);
double& lmdapcratio = TINKER_MOD(dlmda, lmdapcratio);
double& lmdastd = TINKER_MOD(dlmda, lmdastd);
double& lmdathalpha = TINKER_MOD(dlmda, lmdathalpha);
double& lmdatheta = TINKER_MOD(dlmda, lmdatheta);
double& lmdavbias = TINKER_MOD(dlmda, lmdavbias);
double& lmdavtheta = TINKER_MOD(dlmda, lmdavtheta);
double& plmdaapmrho = TINKER_MOD(dlmda, plmdaapmrho);
double& plmdainveps = TINKER_MOD(dlmda, plmdainveps);
double& qntelmda0 = TINKER_MOD(dlmda, qntelmda0);
double& qntelmda1 = TINKER_MOD(dlmda, qntelmda1);
double& qntplmda0 = TINKER_MOD(dlmda, qntplmda0);
double& qntplmda1 = TINKER_MOD(dlmda, qntplmda1);
double& qntvlmda0 = TINKER_MOD(dlmda, qntvlmda0);
double& qntvlmda1 = TINKER_MOD(dlmda, qntvlmda1);
double& vlmdaapmrho = TINKER_MOD(dlmda, vlmdaapmrho);
double& vlmdainveps = TINKER_MOD(dlmda, vlmdainveps);
double& wlmda = TINKER_MOD(dlmda, wlmda);
double& wlmda2 = TINKER_MOD(dlmda, wlmda2);
double (&demvirdl)[3][3] = TINKER_MOD(dlmda, demvirdl);
double (&depvirdl)[3][3] = TINKER_MOD(dlmda, depvirdl);
double (&devvirdl)[3][3] = TINKER_MOD(dlmda, devvirdl);
double (&dvirdl)[3][3] = TINKER_MOD(dlmda, dvirdl);
double*& bdplorig = TINKER_MOD(dlmda, bdplorig);
double*& bflxorig = TINKER_MOD(dlmda, bflxorig);
double*& lmdafhist = TINKER_MOD(dlmda, lmdafhist);
double*& lmdaflist = TINKER_MOD(dlmda, lmdaflist);
double*& lmdafmean = TINKER_MOD(dlmda, lmdafmean);
double*& lmdafsum = TINKER_MOD(dlmda, lmdafsum);
double*& lmdafwt = TINKER_MOD(dlmda, lmdafwt);
double*& lmdalhist = TINKER_MOD(dlmda, lmdalhist);
double*& lmdallist = TINKER_MOD(dlmda, lmdallist);
double*& pchg0orig = TINKER_MOD(dlmda, pchg0orig);
double*& pchgorig = TINKER_MOD(dlmda, pchgorig);
double*& pcoreorig = TINKER_MOD(dlmda, pcoreorig);
double*& polarityorig = TINKER_MOD(dlmda, polarityorig);
double*& pval0orig = TINKER_MOD(dlmda, pval0orig);
double*& pvalorig = TINKER_MOD(dlmda, pvalorig);
double*& abflxorig = TINKER_MOD(dlmda, abflxorig);
double*& aflxorig = TINKER_MOD(dlmda, aflxorig);
double*& dfmdl = TINKER_MOD(dlmda, dfmdl);
double*& dfpdl = TINKER_MOD(dlmda, dfpdl);
double*& dfsumdl = TINKER_MOD(dlmda, dfsumdl);
double*& dfvdl = TINKER_MOD(dlmda, dfvdl);
double*& lcmp = TINKER_MOD(dlmda, lcmp);
double*& lcphi = TINKER_MOD(dlmda, lcphi);
double*& lfmp = TINKER_MOD(dlmda, lfmp);
double*& lfphi = TINKER_MOD(dlmda, lfphi);
double*& poleorig = TINKER_MOD(dlmda, poleorig);
double*& lqgrid = TINKER_MOD(dlmda, lqgrid);
int& lmdatrial = TINKER_MOD(dlmda, lmdatrial);
int& use_abf = TINKER_MOD(dlmda, use_abf);
int& use_abfdyn = TINKER_MOD(dlmda, use_abfdyn);
int& use_dlmda = TINKER_MOD(dlmda, use_dlmda);
int& use_edlmda = TINKER_MOD(dlmda, use_edlmda);
int& use_elmdamap = TINKER_MOD(dlmda, use_elmdamap);
int& use_emdt = TINKER_MOD(dlmda, use_emdt);
int& use_epdt = TINKER_MOD(dlmda, use_epdt);
int& use_evdt = TINKER_MOD(dlmda, use_evdt);
int& use_mainlmda = TINKER_MOD(dlmda, use_mainlmda);
int& use_meta = TINKER_MOD(dlmda, use_meta);
int& use_metadyn = TINKER_MOD(dlmda, use_metadyn);
int& use_ost = TINKER_MOD(dlmda, use_ost);
int& use_ostdyn = TINKER_MOD(dlmda, use_ostdyn);
int& use_pdlmda = TINKER_MOD(dlmda, use_pdlmda);
int& use_plmda = TINKER_MOD(dlmda, use_plmda);
int& use_plmdamap = TINKER_MOD(dlmda, use_plmdamap);
int& use_relstage = TINKER_MOD(dlmda, use_relstage);
int& use_ti = TINKER_MOD(dlmda, use_ti);
int& use_vdlmda = TINKER_MOD(dlmda, use_vdlmda);
int& use_vlmdamap = TINKER_MOD(dlmda, use_vlmdamap);
int*& douindorig = TINKER_MOD(dlmda, douindorig);
char (&elmdamap)[3] = TINKER_MOD(dlmda, elmdamap);
char (&plmdamap)[3] = TINKER_MOD(dlmda, plmdamap);
char (&vlmdamap)[3] = TINKER_MOD(dlmda, vlmdamap);
char (&lmdathmap)[3] = TINKER_MOD(dlmda, lmdathmap);
char (&lmdaengymode)[4] = TINKER_MOD(dlmda, lmdaengymode);
char (&lmdasampmode)[4] = TINKER_MOD(dlmda, lmdasampmode);
char (&relstage)[4] = TINKER_MOD(dlmda, relstage);
char (&lmdasavefile)[240] = TINKER_MOD(dlmda, lmdasavefile);
#endif
} }
