#pragma once

#include "macro.hh"
#include "sizes.hh"

namespace tinker { namespace merck {
using namespace sizes;

extern int& nligne;
extern int (&bt_1)[2][500];
extern int (&eqclass)[5][500];
extern int (&crd)[100];
extern int (&val)[100];
extern int (&pilp)[100];
extern int (&mltb)[100];
extern int (&arom)[100];
extern int (&lin)[100];
extern int (&sbmb)[100];
extern int (&mmffarom)[6][maxtyp];
extern int (&mmffaromc)[6][maxtyp];
extern int (&mmffaroma)[6][maxtyp];
extern double (&rad0)[100];
extern double (&paulel)[100];
extern double (&r0ref)[100][100];
extern double (&kbref)[100][100];
extern double (&mmff_kb)[100][100];
extern double (&mmff_kb1)[100][100];
extern double (&mmff_b0)[100][100];
extern double (&mmff_b1)[100][100];
extern double*& mmff_ka;
extern double*& mmff_ka1;
extern double*& mmff_ka2;
extern double*& mmff_ka3;
extern double*& mmff_ka4;
extern double*& mmff_ka5;
extern double*& mmff_ka6;
extern double*& mmff_ka7;
extern double*& mmff_ka8;
extern double*& mmff_ang0;
extern double*& mmff_ang1;
extern double*& mmff_ang2;
extern double*& mmff_ang3;
extern double*& mmff_ang4;
extern double*& mmff_ang5;
extern double*& mmff_ang6;
extern double*& mmff_ang7;
extern double*& mmff_ang8;
extern double*& stbn_abc;
extern double*& stbn_cba;
extern double*& stbn_abc1;
extern double*& stbn_cba1;
extern double*& stbn_abc2;
extern double*& stbn_cba2;
extern double*& stbn_abc3;
extern double*& stbn_cba3;
extern double*& stbn_abc4;
extern double*& stbn_cba4;
extern double*& stbn_abc5;
extern double*& stbn_cba5;
extern double*& stbn_abc6;
extern double*& stbn_cba6;
extern double*& stbn_abc7;
extern double*& stbn_cba7;
extern double*& stbn_abc8;
extern double*& stbn_cba8;
extern double*& stbn_abc9;
extern double*& stbn_cba9;
extern double*& stbn_abc10;
extern double*& stbn_cba10;
extern double*& stbn_abc11;
extern double*& stbn_cba11;
extern double (&defstbn_abc)[5][5][5];
extern double (&defstbn_cba)[5][5][5];
extern double (&t1_1)[2001][2];
extern double (&t2_1)[2001][2];
extern double (&t3_1)[2001][2];
extern double (&t1_2)[2001][2];
extern double (&t2_2)[2001][2];
extern double (&t3_2)[2001][2];
extern char (&kt_1)[2001][16];
extern char (&kt_2)[2001][16];
extern double (&g)[maxclass];
extern double (&alph)[maxclass];
extern double (&nn)[maxclass];
extern char (&da)[maxclass][1];
extern double (&bci)[100][100];
extern double (&bci_1)[100][100];
extern double (&pbci)[maxclass];
extern double (&fcadj)[maxclass];

#ifdef TINKER_FORTRAN_MODULE_CPP
extern "C" int TINKER_MOD(merck, nligne);
extern "C" int TINKER_MOD(merck, bt_1)[2][500];
extern "C" int TINKER_MOD(merck, eqclass)[5][500];
extern "C" int TINKER_MOD(merck, crd)[100];
extern "C" int TINKER_MOD(merck, val)[100];
extern "C" int TINKER_MOD(merck, pilp)[100];
extern "C" int TINKER_MOD(merck, mltb)[100];
extern "C" int TINKER_MOD(merck, arom)[100];
extern "C" int TINKER_MOD(merck, lin)[100];
extern "C" int TINKER_MOD(merck, sbmb)[100];
extern "C" int TINKER_MOD(merck, mmffarom)[6][maxtyp];
extern "C" int TINKER_MOD(merck, mmffaromc)[6][maxtyp];
extern "C" int TINKER_MOD(merck, mmffaroma)[6][maxtyp];
extern "C" double TINKER_MOD(merck, rad0)[100];
extern "C" double TINKER_MOD(merck, paulel)[100];
extern "C" double TINKER_MOD(merck, r0ref)[100][100];
extern "C" double TINKER_MOD(merck, kbref)[100][100];
extern "C" double TINKER_MOD(merck, mmff_kb)[100][100];
extern "C" double TINKER_MOD(merck, mmff_kb1)[100][100];
extern "C" double TINKER_MOD(merck, mmff_b0)[100][100];
extern "C" double TINKER_MOD(merck, mmff_b1)[100][100];
extern "C" double* TINKER_MOD(merck, mmff_ka);
extern "C" double* TINKER_MOD(merck, mmff_ka1);
extern "C" double* TINKER_MOD(merck, mmff_ka2);
extern "C" double* TINKER_MOD(merck, mmff_ka3);
extern "C" double* TINKER_MOD(merck, mmff_ka4);
extern "C" double* TINKER_MOD(merck, mmff_ka5);
extern "C" double* TINKER_MOD(merck, mmff_ka6);
extern "C" double* TINKER_MOD(merck, mmff_ka7);
extern "C" double* TINKER_MOD(merck, mmff_ka8);
extern "C" double* TINKER_MOD(merck, mmff_ang0);
extern "C" double* TINKER_MOD(merck, mmff_ang1);
extern "C" double* TINKER_MOD(merck, mmff_ang2);
extern "C" double* TINKER_MOD(merck, mmff_ang3);
extern "C" double* TINKER_MOD(merck, mmff_ang4);
extern "C" double* TINKER_MOD(merck, mmff_ang5);
extern "C" double* TINKER_MOD(merck, mmff_ang6);
extern "C" double* TINKER_MOD(merck, mmff_ang7);
extern "C" double* TINKER_MOD(merck, mmff_ang8);
extern "C" double* TINKER_MOD(merck, stbn_abc);
extern "C" double* TINKER_MOD(merck, stbn_cba);
extern "C" double* TINKER_MOD(merck, stbn_abc1);
extern "C" double* TINKER_MOD(merck, stbn_cba1);
extern "C" double* TINKER_MOD(merck, stbn_abc2);
extern "C" double* TINKER_MOD(merck, stbn_cba2);
extern "C" double* TINKER_MOD(merck, stbn_abc3);
extern "C" double* TINKER_MOD(merck, stbn_cba3);
extern "C" double* TINKER_MOD(merck, stbn_abc4);
extern "C" double* TINKER_MOD(merck, stbn_cba4);
extern "C" double* TINKER_MOD(merck, stbn_abc5);
extern "C" double* TINKER_MOD(merck, stbn_cba5);
extern "C" double* TINKER_MOD(merck, stbn_abc6);
extern "C" double* TINKER_MOD(merck, stbn_cba6);
extern "C" double* TINKER_MOD(merck, stbn_abc7);
extern "C" double* TINKER_MOD(merck, stbn_cba7);
extern "C" double* TINKER_MOD(merck, stbn_abc8);
extern "C" double* TINKER_MOD(merck, stbn_cba8);
extern "C" double* TINKER_MOD(merck, stbn_abc9);
extern "C" double* TINKER_MOD(merck, stbn_cba9);
extern "C" double* TINKER_MOD(merck, stbn_abc10);
extern "C" double* TINKER_MOD(merck, stbn_cba10);
extern "C" double* TINKER_MOD(merck, stbn_abc11);
extern "C" double* TINKER_MOD(merck, stbn_cba11);
extern "C" double TINKER_MOD(merck, defstbn_abc)[5][5][5];
extern "C" double TINKER_MOD(merck, defstbn_cba)[5][5][5];
extern "C" double TINKER_MOD(merck, t1_1)[2001][2];
extern "C" double TINKER_MOD(merck, t2_1)[2001][2];
extern "C" double TINKER_MOD(merck, t3_1)[2001][2];
extern "C" double TINKER_MOD(merck, t1_2)[2001][2];
extern "C" double TINKER_MOD(merck, t2_2)[2001][2];
extern "C" double TINKER_MOD(merck, t3_2)[2001][2];
extern "C" char TINKER_MOD(merck, kt_1)[2001][16];
extern "C" char TINKER_MOD(merck, kt_2)[2001][16];
extern "C" double TINKER_MOD(merck, g)[maxclass];
extern "C" double TINKER_MOD(merck, alph)[maxclass];
extern "C" double TINKER_MOD(merck, nn)[maxclass];
extern "C" char TINKER_MOD(merck, da)[maxclass][1];
extern "C" double TINKER_MOD(merck, bci)[100][100];
extern "C" double TINKER_MOD(merck, bci_1)[100][100];
extern "C" double TINKER_MOD(merck, pbci)[maxclass];
extern "C" double TINKER_MOD(merck, fcadj)[maxclass];

int& nligne = TINKER_MOD(merck, nligne);
int (&bt_1)[2][500] = TINKER_MOD(merck, bt_1);
int (&eqclass)[5][500] = TINKER_MOD(merck, eqclass);
int (&crd)[100] = TINKER_MOD(merck, crd);
int (&val)[100] = TINKER_MOD(merck, val);
int (&pilp)[100] = TINKER_MOD(merck, pilp);
int (&mltb)[100] = TINKER_MOD(merck, mltb);
int (&arom)[100] = TINKER_MOD(merck, arom);
int (&lin)[100] = TINKER_MOD(merck, lin);
int (&sbmb)[100] = TINKER_MOD(merck, sbmb);
int (&mmffarom)[6][maxtyp] = TINKER_MOD(merck, mmffarom);
int (&mmffaromc)[6][maxtyp] = TINKER_MOD(merck, mmffaromc);
int (&mmffaroma)[6][maxtyp] = TINKER_MOD(merck, mmffaroma);
double (&rad0)[100] = TINKER_MOD(merck, rad0);
double (&paulel)[100] = TINKER_MOD(merck, paulel);
double (&r0ref)[100][100] = TINKER_MOD(merck, r0ref);
double (&kbref)[100][100] = TINKER_MOD(merck, kbref);
double (&mmff_kb)[100][100] = TINKER_MOD(merck, mmff_kb);
double (&mmff_kb1)[100][100] = TINKER_MOD(merck, mmff_kb1);
double (&mmff_b0)[100][100] = TINKER_MOD(merck, mmff_b0);
double (&mmff_b1)[100][100] = TINKER_MOD(merck, mmff_b1);
double*& mmff_ka = TINKER_MOD(merck, mmff_ka);
double*& mmff_ka1 = TINKER_MOD(merck, mmff_ka1);
double*& mmff_ka2 = TINKER_MOD(merck, mmff_ka2);
double*& mmff_ka3 = TINKER_MOD(merck, mmff_ka3);
double*& mmff_ka4 = TINKER_MOD(merck, mmff_ka4);
double*& mmff_ka5 = TINKER_MOD(merck, mmff_ka5);
double*& mmff_ka6 = TINKER_MOD(merck, mmff_ka6);
double*& mmff_ka7 = TINKER_MOD(merck, mmff_ka7);
double*& mmff_ka8 = TINKER_MOD(merck, mmff_ka8);
double*& mmff_ang0 = TINKER_MOD(merck, mmff_ang0);
double*& mmff_ang1 = TINKER_MOD(merck, mmff_ang1);
double*& mmff_ang2 = TINKER_MOD(merck, mmff_ang2);
double*& mmff_ang3 = TINKER_MOD(merck, mmff_ang3);
double*& mmff_ang4 = TINKER_MOD(merck, mmff_ang4);
double*& mmff_ang5 = TINKER_MOD(merck, mmff_ang5);
double*& mmff_ang6 = TINKER_MOD(merck, mmff_ang6);
double*& mmff_ang7 = TINKER_MOD(merck, mmff_ang7);
double*& mmff_ang8 = TINKER_MOD(merck, mmff_ang8);
double*& stbn_abc = TINKER_MOD(merck, stbn_abc);
double*& stbn_cba = TINKER_MOD(merck, stbn_cba);
double*& stbn_abc1 = TINKER_MOD(merck, stbn_abc1);
double*& stbn_cba1 = TINKER_MOD(merck, stbn_cba1);
double*& stbn_abc2 = TINKER_MOD(merck, stbn_abc2);
double*& stbn_cba2 = TINKER_MOD(merck, stbn_cba2);
double*& stbn_abc3 = TINKER_MOD(merck, stbn_abc3);
double*& stbn_cba3 = TINKER_MOD(merck, stbn_cba3);
double*& stbn_abc4 = TINKER_MOD(merck, stbn_abc4);
double*& stbn_cba4 = TINKER_MOD(merck, stbn_cba4);
double*& stbn_abc5 = TINKER_MOD(merck, stbn_abc5);
double*& stbn_cba5 = TINKER_MOD(merck, stbn_cba5);
double*& stbn_abc6 = TINKER_MOD(merck, stbn_abc6);
double*& stbn_cba6 = TINKER_MOD(merck, stbn_cba6);
double*& stbn_abc7 = TINKER_MOD(merck, stbn_abc7);
double*& stbn_cba7 = TINKER_MOD(merck, stbn_cba7);
double*& stbn_abc8 = TINKER_MOD(merck, stbn_abc8);
double*& stbn_cba8 = TINKER_MOD(merck, stbn_cba8);
double*& stbn_abc9 = TINKER_MOD(merck, stbn_abc9);
double*& stbn_cba9 = TINKER_MOD(merck, stbn_cba9);
double*& stbn_abc10 = TINKER_MOD(merck, stbn_abc10);
double*& stbn_cba10 = TINKER_MOD(merck, stbn_cba10);
double*& stbn_abc11 = TINKER_MOD(merck, stbn_abc11);
double*& stbn_cba11 = TINKER_MOD(merck, stbn_cba11);
double (&defstbn_abc)[5][5][5] = TINKER_MOD(merck, defstbn_abc);
double (&defstbn_cba)[5][5][5] = TINKER_MOD(merck, defstbn_cba);
double (&t1_1)[2001][2] = TINKER_MOD(merck, t1_1);
double (&t2_1)[2001][2] = TINKER_MOD(merck, t2_1);
double (&t3_1)[2001][2] = TINKER_MOD(merck, t3_1);
double (&t1_2)[2001][2] = TINKER_MOD(merck, t1_2);
double (&t2_2)[2001][2] = TINKER_MOD(merck, t2_2);
double (&t3_2)[2001][2] = TINKER_MOD(merck, t3_2);
char (&kt_1)[2001][16] = TINKER_MOD(merck, kt_1);
char (&kt_2)[2001][16] = TINKER_MOD(merck, kt_2);
double (&g)[maxclass] = TINKER_MOD(merck, g);
double (&alph)[maxclass] = TINKER_MOD(merck, alph);
double (&nn)[maxclass] = TINKER_MOD(merck, nn);
char (&da)[maxclass][1] = TINKER_MOD(merck, da);
double (&bci)[100][100] = TINKER_MOD(merck, bci);
double (&bci_1)[100][100] = TINKER_MOD(merck, bci_1);
double (&pbci)[maxclass] = TINKER_MOD(merck, pbci);
double (&fcadj)[maxclass] = TINKER_MOD(merck, fcadj);
#endif
} }
