#pragma once

#include "macro.hh"

namespace tinker { namespace ost {
extern int& fli0;
extern int& nflmda;
extern int& nmetahist;
extern int& nmethistsave;
extern int& sizemetahist;
extern int*& metaihist;
extern int*& osthist;
extern int*& ostnext;
extern int*& osthead;
extern double& hbias;
extern double& maxwfhist;
extern double& maxwlhist;
extern double& ostbdgdfl;
extern double& ostbdgdl;
extern double& ostdgdl;
extern double& ostgtempgamma;
extern double& ostgthresh;
extern double& ostltempgamma;
extern double& ostlthresh;
extern double& oststdev;
extern double& wfhist;
extern double& wflmda;
extern double& wflmda2;
extern double& wlhist;
extern double*& dvmetagrid;
extern double*& metahhist;
extern double*& metalhist;
extern double*& metawhist;
extern double*& osthhist;
extern double*& ostwfhist;
extern double*& ostwlhist;
extern double*& vkernelmax;
extern double*& vmetagrid;
extern double*& gfkernel;
extern double*& gkernel;
extern double*& glfkernel;
extern double*& glkernel;
extern int& fastkernel;
extern int& ostinterpol;
extern int& use_ostgtemp;
extern int& use_ostltemp;
extern char (&metasavefile)[240];

#ifdef TINKER_FORTRAN_MODULE_CPP
extern "C" int TINKER_MOD(ost, fli0);
extern "C" int TINKER_MOD(ost, nflmda);
extern "C" int TINKER_MOD(ost, nmetahist);
extern "C" int TINKER_MOD(ost, nmethistsave);
extern "C" int TINKER_MOD(ost, sizemetahist);
extern "C" int* TINKER_MOD(ost, metaihist);
extern "C" int* TINKER_MOD(ost, osthist);
extern "C" int* TINKER_MOD(ost, ostnext);
extern "C" int* TINKER_MOD(ost, osthead);
extern "C" double TINKER_MOD(ost, hbias);
extern "C" double TINKER_MOD(ost, maxwfhist);
extern "C" double TINKER_MOD(ost, maxwlhist);
extern "C" double TINKER_MOD(ost, ostbdgdfl);
extern "C" double TINKER_MOD(ost, ostbdgdl);
extern "C" double TINKER_MOD(ost, ostdgdl);
extern "C" double TINKER_MOD(ost, ostgtempgamma);
extern "C" double TINKER_MOD(ost, ostgthresh);
extern "C" double TINKER_MOD(ost, ostltempgamma);
extern "C" double TINKER_MOD(ost, ostlthresh);
extern "C" double TINKER_MOD(ost, oststdev);
extern "C" double TINKER_MOD(ost, wfhist);
extern "C" double TINKER_MOD(ost, wflmda);
extern "C" double TINKER_MOD(ost, wflmda2);
extern "C" double TINKER_MOD(ost, wlhist);
extern "C" double* TINKER_MOD(ost, dvmetagrid);
extern "C" double* TINKER_MOD(ost, metahhist);
extern "C" double* TINKER_MOD(ost, metalhist);
extern "C" double* TINKER_MOD(ost, metawhist);
extern "C" double* TINKER_MOD(ost, osthhist);
extern "C" double* TINKER_MOD(ost, ostwfhist);
extern "C" double* TINKER_MOD(ost, ostwlhist);
extern "C" double* TINKER_MOD(ost, vkernelmax);
extern "C" double* TINKER_MOD(ost, vmetagrid);
extern "C" double* TINKER_MOD(ost, gfkernel);
extern "C" double* TINKER_MOD(ost, gkernel);
extern "C" double* TINKER_MOD(ost, glfkernel);
extern "C" double* TINKER_MOD(ost, glkernel);
extern "C" int TINKER_MOD(ost, fastkernel);
extern "C" int TINKER_MOD(ost, ostinterpol);
extern "C" int TINKER_MOD(ost, use_ostgtemp);
extern "C" int TINKER_MOD(ost, use_ostltemp);
extern "C" char TINKER_MOD(ost, metasavefile)[240];

int& fli0 = TINKER_MOD(ost, fli0);
int& nflmda = TINKER_MOD(ost, nflmda);
int& nmetahist = TINKER_MOD(ost, nmetahist);
int& nmethistsave = TINKER_MOD(ost, nmethistsave);
int& sizemetahist = TINKER_MOD(ost, sizemetahist);
int*& metaihist = TINKER_MOD(ost, metaihist);
int*& osthist = TINKER_MOD(ost, osthist);
int*& ostnext = TINKER_MOD(ost, ostnext);
int*& osthead = TINKER_MOD(ost, osthead);
double& hbias = TINKER_MOD(ost, hbias);
double& maxwfhist = TINKER_MOD(ost, maxwfhist);
double& maxwlhist = TINKER_MOD(ost, maxwlhist);
double& ostbdgdfl = TINKER_MOD(ost, ostbdgdfl);
double& ostbdgdl = TINKER_MOD(ost, ostbdgdl);
double& ostdgdl = TINKER_MOD(ost, ostdgdl);
double& ostgtempgamma = TINKER_MOD(ost, ostgtempgamma);
double& ostgthresh = TINKER_MOD(ost, ostgthresh);
double& ostltempgamma = TINKER_MOD(ost, ostltempgamma);
double& ostlthresh = TINKER_MOD(ost, ostlthresh);
double& oststdev = TINKER_MOD(ost, oststdev);
double& wfhist = TINKER_MOD(ost, wfhist);
double& wflmda = TINKER_MOD(ost, wflmda);
double& wflmda2 = TINKER_MOD(ost, wflmda2);
double& wlhist = TINKER_MOD(ost, wlhist);
double*& dvmetagrid = TINKER_MOD(ost, dvmetagrid);
double*& metahhist = TINKER_MOD(ost, metahhist);
double*& metalhist = TINKER_MOD(ost, metalhist);
double*& metawhist = TINKER_MOD(ost, metawhist);
double*& osthhist = TINKER_MOD(ost, osthhist);
double*& ostwfhist = TINKER_MOD(ost, ostwfhist);
double*& ostwlhist = TINKER_MOD(ost, ostwlhist);
double*& vkernelmax = TINKER_MOD(ost, vkernelmax);
double*& vmetagrid = TINKER_MOD(ost, vmetagrid);
double*& gfkernel = TINKER_MOD(ost, gfkernel);
double*& gkernel = TINKER_MOD(ost, gkernel);
double*& glfkernel = TINKER_MOD(ost, glfkernel);
double*& glkernel = TINKER_MOD(ost, glkernel);
int& fastkernel = TINKER_MOD(ost, fastkernel);
int& ostinterpol = TINKER_MOD(ost, ostinterpol);
int& use_ostgtemp = TINKER_MOD(ost, use_ostgtemp);
int& use_ostltemp = TINKER_MOD(ost, use_ostltemp);
char (&metasavefile)[240] = TINKER_MOD(ost, metasavefile);
#endif
} }
