#pragma once

#include "macro.hh"

namespace tinker { namespace ost {
extern int& fli0;
extern int& iost;
extern int& iosthist;
extern int& nflmda;
extern int& nlmda;
extern int& nmetahist;
extern int& nmethistsave;
extern int& nosthist;
extern int& nosthistsave;
extern int& ostcvbin;
extern int& ostnavg;
extern int& ostnequil;
extern int& sizeosthist;
extern int& sizemetahist;
extern int*& metaihist;
extern int*& osthead;
extern int*& osthist;
extern int*& ostihist;
extern int*& ostnext;
extern double& deffdl;
extern double& eosttot;
extern double& hbias;
extern double& maxwfhist;
extern double& maxwlhist;
extern double& ostbdfdl;
extern double& ostbdgdfl;
extern double& ostbdgdl;
extern double& ostbvbias;
extern double& ostcvdif;
extern double& ostcvrat;
extern double& ostcvslp;
extern double& ostcvstd;
extern double& ostddgdl;
extern double& ostdedl;
extern double& ostdedlavg;
extern double& ostdedlslp;
extern double& ostdedlstd;
extern double& ostdgdl;
extern double& ostdt;
extern double& osteqratio;
extern double& ostfriction;
extern double& ostlambda;
extern double& ostlambdaavg;
extern double& ostlambdaslp;
extern double& ostlambdastd;
extern double& ostmass;
extern double& oststdev;
extern double& osttheta;
extern double& ostvtheta;
extern double& tempergamma;
extern double& temperthresh;
extern double& wfhist;
extern double& wflmda;
extern double& wflmda2;
extern double& wlhist;
extern double& wlmda;
extern double& wlmda2;
extern double*& dvmetagrid;
extern double*& fkernel;
extern double*& fsumkernel;
extern double*& gfkernel;
extern double*& metahhist;
extern double*& metalhist;
extern double*& metawhist;
extern double*& ostdedlavgbin;
extern double*& ostdedlslpbin;
extern double*& ostdedlstdbin;
extern double*& ostflist;
extern double*& ostfhist;
extern double*& osthhist;
extern double*& ostlmdaavgbin;
extern double*& ostlmdaslpbin;
extern double*& ostlmdastdbin;
extern double*& ostllist;
extern double*& ostlhist;
extern double*& ostwfhist;
extern double*& ostwlhist;
extern double*& vkernelmax;
extern double*& vmetagrid;
extern double*& gkernel;
extern double*& glfkernel;
extern double*& glkernel;
extern double*& pfkernel;
extern int& fastkernel;
extern int& ostemper;
extern int& ostinterpol;
extern int& osttrial;
extern char (&metasavefile)[240];
extern char (&ostsavefile)[240];

#ifdef TINKER_FORTRAN_MODULE_CPP
extern "C" int TINKER_MOD(ost, fli0);
extern "C" int TINKER_MOD(ost, iost);
extern "C" int TINKER_MOD(ost, iosthist);
extern "C" int TINKER_MOD(ost, nflmda);
extern "C" int TINKER_MOD(ost, nlmda);
extern "C" int TINKER_MOD(ost, nmetahist);
extern "C" int TINKER_MOD(ost, nmethistsave);
extern "C" int TINKER_MOD(ost, nosthist);
extern "C" int TINKER_MOD(ost, nosthistsave);
extern "C" int TINKER_MOD(ost, ostcvbin);
extern "C" int TINKER_MOD(ost, ostnavg);
extern "C" int TINKER_MOD(ost, ostnequil);
extern "C" int TINKER_MOD(ost, sizeosthist);
extern "C" int TINKER_MOD(ost, sizemetahist);
extern "C" int* TINKER_MOD(ost, metaihist);
extern "C" int* TINKER_MOD(ost, osthead);
extern "C" int* TINKER_MOD(ost, osthist);
extern "C" int* TINKER_MOD(ost, ostihist);
extern "C" int* TINKER_MOD(ost, ostnext);
extern "C" double TINKER_MOD(ost, deffdl);
extern "C" double TINKER_MOD(ost, eosttot);
extern "C" double TINKER_MOD(ost, hbias);
extern "C" double TINKER_MOD(ost, maxwfhist);
extern "C" double TINKER_MOD(ost, maxwlhist);
extern "C" double TINKER_MOD(ost, ostbdfdl);
extern "C" double TINKER_MOD(ost, ostbdgdfl);
extern "C" double TINKER_MOD(ost, ostbdgdl);
extern "C" double TINKER_MOD(ost, ostbvbias);
extern "C" double TINKER_MOD(ost, ostcvdif);
extern "C" double TINKER_MOD(ost, ostcvrat);
extern "C" double TINKER_MOD(ost, ostcvslp);
extern "C" double TINKER_MOD(ost, ostcvstd);
extern "C" double TINKER_MOD(ost, ostddgdl);
extern "C" double TINKER_MOD(ost, ostdedl);
extern "C" double TINKER_MOD(ost, ostdedlavg);
extern "C" double TINKER_MOD(ost, ostdedlslp);
extern "C" double TINKER_MOD(ost, ostdedlstd);
extern "C" double TINKER_MOD(ost, ostdgdl);
extern "C" double TINKER_MOD(ost, ostdt);
extern "C" double TINKER_MOD(ost, osteqratio);
extern "C" double TINKER_MOD(ost, ostfriction);
extern "C" double TINKER_MOD(ost, ostlambda);
extern "C" double TINKER_MOD(ost, ostlambdaavg);
extern "C" double TINKER_MOD(ost, ostlambdaslp);
extern "C" double TINKER_MOD(ost, ostlambdastd);
extern "C" double TINKER_MOD(ost, ostmass);
extern "C" double TINKER_MOD(ost, oststdev);
extern "C" double TINKER_MOD(ost, osttheta);
extern "C" double TINKER_MOD(ost, ostvtheta);
extern "C" double TINKER_MOD(ost, tempergamma);
extern "C" double TINKER_MOD(ost, temperthresh);
extern "C" double TINKER_MOD(ost, wfhist);
extern "C" double TINKER_MOD(ost, wflmda);
extern "C" double TINKER_MOD(ost, wflmda2);
extern "C" double TINKER_MOD(ost, wlhist);
extern "C" double TINKER_MOD(ost, wlmda);
extern "C" double TINKER_MOD(ost, wlmda2);
extern "C" double* TINKER_MOD(ost, dvmetagrid);
extern "C" double* TINKER_MOD(ost, fkernel);
extern "C" double* TINKER_MOD(ost, fsumkernel);
extern "C" double* TINKER_MOD(ost, gfkernel);
extern "C" double* TINKER_MOD(ost, metahhist);
extern "C" double* TINKER_MOD(ost, metalhist);
extern "C" double* TINKER_MOD(ost, metawhist);
extern "C" double* TINKER_MOD(ost, ostdedlavgbin);
extern "C" double* TINKER_MOD(ost, ostdedlslpbin);
extern "C" double* TINKER_MOD(ost, ostdedlstdbin);
extern "C" double* TINKER_MOD(ost, ostflist);
extern "C" double* TINKER_MOD(ost, ostfhist);
extern "C" double* TINKER_MOD(ost, osthhist);
extern "C" double* TINKER_MOD(ost, ostlmdaavgbin);
extern "C" double* TINKER_MOD(ost, ostlmdaslpbin);
extern "C" double* TINKER_MOD(ost, ostlmdastdbin);
extern "C" double* TINKER_MOD(ost, ostllist);
extern "C" double* TINKER_MOD(ost, ostlhist);
extern "C" double* TINKER_MOD(ost, ostwfhist);
extern "C" double* TINKER_MOD(ost, ostwlhist);
extern "C" double* TINKER_MOD(ost, vkernelmax);
extern "C" double* TINKER_MOD(ost, vmetagrid);
extern "C" double* TINKER_MOD(ost, gkernel);
extern "C" double* TINKER_MOD(ost, glfkernel);
extern "C" double* TINKER_MOD(ost, glkernel);
extern "C" double* TINKER_MOD(ost, pfkernel);
extern "C" int TINKER_MOD(ost, fastkernel);
extern "C" int TINKER_MOD(ost, ostemper);
extern "C" int TINKER_MOD(ost, ostinterpol);
extern "C" int TINKER_MOD(ost, osttrial);
extern "C" char TINKER_MOD(ost, metasavefile)[240];
extern "C" char TINKER_MOD(ost, ostsavefile)[240];

int& fli0 = TINKER_MOD(ost, fli0);
int& iost = TINKER_MOD(ost, iost);
int& iosthist = TINKER_MOD(ost, iosthist);
int& nflmda = TINKER_MOD(ost, nflmda);
int& nlmda = TINKER_MOD(ost, nlmda);
int& nmetahist = TINKER_MOD(ost, nmetahist);
int& nmethistsave = TINKER_MOD(ost, nmethistsave);
int& nosthist = TINKER_MOD(ost, nosthist);
int& nosthistsave = TINKER_MOD(ost, nosthistsave);
int& ostcvbin = TINKER_MOD(ost, ostcvbin);
int& ostnavg = TINKER_MOD(ost, ostnavg);
int& ostnequil = TINKER_MOD(ost, ostnequil);
int& sizeosthist = TINKER_MOD(ost, sizeosthist);
int& sizemetahist = TINKER_MOD(ost, sizemetahist);
int*& metaihist = TINKER_MOD(ost, metaihist);
int*& osthead = TINKER_MOD(ost, osthead);
int*& osthist = TINKER_MOD(ost, osthist);
int*& ostihist = TINKER_MOD(ost, ostihist);
int*& ostnext = TINKER_MOD(ost, ostnext);
double& deffdl = TINKER_MOD(ost, deffdl);
double& eosttot = TINKER_MOD(ost, eosttot);
double& hbias = TINKER_MOD(ost, hbias);
double& maxwfhist = TINKER_MOD(ost, maxwfhist);
double& maxwlhist = TINKER_MOD(ost, maxwlhist);
double& ostbdfdl = TINKER_MOD(ost, ostbdfdl);
double& ostbdgdfl = TINKER_MOD(ost, ostbdgdfl);
double& ostbdgdl = TINKER_MOD(ost, ostbdgdl);
double& ostbvbias = TINKER_MOD(ost, ostbvbias);
double& ostcvdif = TINKER_MOD(ost, ostcvdif);
double& ostcvrat = TINKER_MOD(ost, ostcvrat);
double& ostcvslp = TINKER_MOD(ost, ostcvslp);
double& ostcvstd = TINKER_MOD(ost, ostcvstd);
double& ostddgdl = TINKER_MOD(ost, ostddgdl);
double& ostdedl = TINKER_MOD(ost, ostdedl);
double& ostdedlavg = TINKER_MOD(ost, ostdedlavg);
double& ostdedlslp = TINKER_MOD(ost, ostdedlslp);
double& ostdedlstd = TINKER_MOD(ost, ostdedlstd);
double& ostdgdl = TINKER_MOD(ost, ostdgdl);
double& ostdt = TINKER_MOD(ost, ostdt);
double& osteqratio = TINKER_MOD(ost, osteqratio);
double& ostfriction = TINKER_MOD(ost, ostfriction);
double& ostlambda = TINKER_MOD(ost, ostlambda);
double& ostlambdaavg = TINKER_MOD(ost, ostlambdaavg);
double& ostlambdaslp = TINKER_MOD(ost, ostlambdaslp);
double& ostlambdastd = TINKER_MOD(ost, ostlambdastd);
double& ostmass = TINKER_MOD(ost, ostmass);
double& oststdev = TINKER_MOD(ost, oststdev);
double& osttheta = TINKER_MOD(ost, osttheta);
double& ostvtheta = TINKER_MOD(ost, ostvtheta);
double& tempergamma = TINKER_MOD(ost, tempergamma);
double& temperthresh = TINKER_MOD(ost, temperthresh);
double& wfhist = TINKER_MOD(ost, wfhist);
double& wflmda = TINKER_MOD(ost, wflmda);
double& wflmda2 = TINKER_MOD(ost, wflmda2);
double& wlhist = TINKER_MOD(ost, wlhist);
double& wlmda = TINKER_MOD(ost, wlmda);
double& wlmda2 = TINKER_MOD(ost, wlmda2);
double*& dvmetagrid = TINKER_MOD(ost, dvmetagrid);
double*& fkernel = TINKER_MOD(ost, fkernel);
double*& fsumkernel = TINKER_MOD(ost, fsumkernel);
double*& gfkernel = TINKER_MOD(ost, gfkernel);
double*& metahhist = TINKER_MOD(ost, metahhist);
double*& metalhist = TINKER_MOD(ost, metalhist);
double*& metawhist = TINKER_MOD(ost, metawhist);
double*& ostdedlavgbin = TINKER_MOD(ost, ostdedlavgbin);
double*& ostdedlslpbin = TINKER_MOD(ost, ostdedlslpbin);
double*& ostdedlstdbin = TINKER_MOD(ost, ostdedlstdbin);
double*& ostflist = TINKER_MOD(ost, ostflist);
double*& ostfhist = TINKER_MOD(ost, ostfhist);
double*& osthhist = TINKER_MOD(ost, osthhist);
double*& ostlmdaavgbin = TINKER_MOD(ost, ostlmdaavgbin);
double*& ostlmdaslpbin = TINKER_MOD(ost, ostlmdaslpbin);
double*& ostlmdastdbin = TINKER_MOD(ost, ostlmdastdbin);
double*& ostllist = TINKER_MOD(ost, ostllist);
double*& ostlhist = TINKER_MOD(ost, ostlhist);
double*& ostwfhist = TINKER_MOD(ost, ostwfhist);
double*& ostwlhist = TINKER_MOD(ost, ostwlhist);
double*& vkernelmax = TINKER_MOD(ost, vkernelmax);
double*& vmetagrid = TINKER_MOD(ost, vmetagrid);
double*& gkernel = TINKER_MOD(ost, gkernel);
double*& glfkernel = TINKER_MOD(ost, glfkernel);
double*& glkernel = TINKER_MOD(ost, glkernel);
double*& pfkernel = TINKER_MOD(ost, pfkernel);
int& fastkernel = TINKER_MOD(ost, fastkernel);
int& ostemper = TINKER_MOD(ost, ostemper);
int& ostinterpol = TINKER_MOD(ost, ostinterpol);
int& osttrial = TINKER_MOD(ost, osttrial);
char (&metasavefile)[240] = TINKER_MOD(ost, metasavefile);
char (&ostsavefile)[240] = TINKER_MOD(ost, ostsavefile);
#endif
} }
