@echo off
rem
rem
rem  ###########################################################
rem  ##                                                       ##
rem  ##  compile.bat  --  compile each of the TINKER modules  ##
rem  ##      (Compaq Visual Fortran for Windows Version)      ##
rem  ##                                                       ##
rem  ###########################################################
rem
rem
DF /compile_only /optimize /fast active.f
DF /compile_only /optimize /fast alchemy.f
DF /compile_only /optimize /fast analysis.f
DF /compile_only /optimize /fast analyze.f
DF /compile_only /optimize /fast angles.f
DF /compile_only /optimize /fast anneal.f
DF /compile_only /optimize /fast archive.f
DF /compile_only /optimize /fast attach.f
DF /compile_only /optimize /fast basefile.f
DF /compile_only /optimize /fast beeman.f
DF /compile_only /optimize /fast bicubic.f
DF /compile_only /optimize /fast bitors.f
DF /compile_only /optimize /fast bonds.f
DF /compile_only /optimize /fast born.f
DF /compile_only /optimize /fast bounds.f
DF /compile_only /optimize /fast bussi.f
DF /compile_only /optimize /fast calendar.f
DF /compile_only /optimize /fast center.f
DF /compile_only /optimize /fast chkpole.f
DF /compile_only /optimize /fast chkring.f
DF /compile_only /optimize /fast chkxyz.f
DF /compile_only /optimize /fast cholesky.f
DF /compile_only /optimize /fast clock.f
DF /compile_only /optimize /fast cluster.f
DF /compile_only /optimize /fast column.f
DF /compile_only /optimize /fast command.f
DF /compile_only /optimize /fast connect.f
DF /compile_only /optimize /fast connolly.f
DF /compile_only /optimize /fast control.f
DF /compile_only /optimize /fast correlate.f
DF /compile_only /optimize /fast crystal.f
DF /compile_only /optimize /fast cspline.f
DF /compile_only /optimize /fast cutoffs.f
DF /compile_only /optimize /fast deflate.f
DF /compile_only /optimize /fast delete.f
DF /compile_only /optimize /fast diagq.f
DF /compile_only /optimize /fast diffeq.f
DF /compile_only /optimize /fast diffuse.f
DF /compile_only /optimize /fast distgeom.f
DF /compile_only /optimize /fast document.f
DF /compile_only /optimize /fast dynamic.f
DF /compile_only /optimize /fast eangang.f
DF /compile_only /optimize /fast eangang1.f
DF /compile_only /optimize /fast eangang2.f
DF /compile_only /optimize /fast eangang3.f
DF /compile_only /optimize /fast eangle.f
DF /compile_only /optimize /fast eangle1.f
DF /compile_only /optimize /fast eangle2.f
DF /compile_only /optimize /fast eangle3.f
DF /compile_only /optimize /fast ebond.f
DF /compile_only /optimize /fast ebond1.f
DF /compile_only /optimize /fast ebond2.f
DF /compile_only /optimize /fast ebond3.f
DF /compile_only /optimize /fast ebuck.f
DF /compile_only /optimize /fast ebuck1.f
DF /compile_only /optimize /fast ebuck2.f
DF /compile_only /optimize /fast ebuck3.f
DF /compile_only /optimize /fast echarge.f
DF /compile_only /optimize /fast echarge1.f
DF /compile_only /optimize /fast echarge2.f
DF /compile_only /optimize /fast echarge3.f
DF /compile_only /optimize /fast echgdpl.f
DF /compile_only /optimize /fast echgdpl1.f
DF /compile_only /optimize /fast echgdpl2.f
DF /compile_only /optimize /fast echgdpl3.f
DF /compile_only /optimize /fast edipole.f
DF /compile_only /optimize /fast edipole1.f
DF /compile_only /optimize /fast edipole2.f
DF /compile_only /optimize /fast edipole3.f
DF /compile_only /optimize /fast egauss.f
DF /compile_only /optimize /fast egauss1.f
DF /compile_only /optimize /fast egauss2.f
DF /compile_only /optimize /fast egauss3.f
DF /compile_only /optimize /fast egeom.f
DF /compile_only /optimize /fast egeom1.f
DF /compile_only /optimize /fast egeom2.f
DF /compile_only /optimize /fast egeom3.f
DF /compile_only /optimize /fast ehal.f
DF /compile_only /optimize /fast ehal1.f
DF /compile_only /optimize /fast ehal2.f
DF /compile_only /optimize /fast ehal3.f
DF /compile_only /optimize /fast eimprop.f
DF /compile_only /optimize /fast eimprop1.f
DF /compile_only /optimize /fast eimprop2.f
DF /compile_only /optimize /fast eimprop3.f
DF /compile_only /optimize /fast eimptor.f
DF /compile_only /optimize /fast eimptor1.f
DF /compile_only /optimize /fast eimptor2.f
DF /compile_only /optimize /fast eimptor3.f
DF /compile_only /optimize /fast elj.f
DF /compile_only /optimize /fast elj1.f
DF /compile_only /optimize /fast elj2.f
DF /compile_only /optimize /fast elj3.f
DF /compile_only /optimize /fast embed.f
DF /compile_only /optimize /fast emetal.f
DF /compile_only /optimize /fast emetal1.f
DF /compile_only /optimize /fast emetal2.f
DF /compile_only /optimize /fast emetal3.f
DF /compile_only /optimize /fast emm3hb.f
DF /compile_only /optimize /fast emm3hb1.f
DF /compile_only /optimize /fast emm3hb2.f
DF /compile_only /optimize /fast emm3hb3.f
DF /compile_only /optimize /fast empole.f
DF /compile_only /optimize /fast empole1.f
DF /compile_only /optimize /fast empole2.f
DF /compile_only /optimize /fast empole3.f
DF /compile_only /optimize /fast energy.f
DF /compile_only /optimize /fast eopbend.f
DF /compile_only /optimize /fast eopbend1.f
DF /compile_only /optimize /fast eopbend2.f
DF /compile_only /optimize /fast eopbend3.f
DF /compile_only /optimize /fast eopdist.f
DF /compile_only /optimize /fast eopdist1.f
DF /compile_only /optimize /fast eopdist2.f
DF /compile_only /optimize /fast eopdist3.f
DF /compile_only /optimize /fast epitors.f
DF /compile_only /optimize /fast epitors1.f
DF /compile_only /optimize /fast epitors2.f
DF /compile_only /optimize /fast epitors3.f
DF /compile_only /optimize /fast erf.f
DF /compile_only /optimize /fast erxnfld.f
DF /compile_only /optimize /fast erxnfld1.f
DF /compile_only /optimize /fast erxnfld2.f
DF /compile_only /optimize /fast erxnfld3.f
DF /compile_only /optimize /fast esolv.f
DF /compile_only /optimize /fast esolv1.f
DF /compile_only /optimize /fast esolv2.f
DF /compile_only /optimize /fast esolv3.f
DF /compile_only /optimize /fast estrbnd.f
DF /compile_only /optimize /fast estrbnd1.f
DF /compile_only /optimize /fast estrbnd2.f
DF /compile_only /optimize /fast estrbnd3.f
DF /compile_only /optimize /fast estrtor.f
DF /compile_only /optimize /fast estrtor1.f
DF /compile_only /optimize /fast estrtor2.f
DF /compile_only /optimize /fast estrtor3.f
DF /compile_only /optimize /fast etors.f
DF /compile_only /optimize /fast etors1.f
DF /compile_only /optimize /fast etors2.f
DF /compile_only /optimize /fast etors3.f
DF /compile_only /optimize /fast etortor.f
DF /compile_only /optimize /fast etortor1.f
DF /compile_only /optimize /fast etortor2.f
DF /compile_only /optimize /fast etortor3.f
DF /compile_only /optimize /fast eurey.f
DF /compile_only /optimize /fast eurey1.f
DF /compile_only /optimize /fast eurey2.f
DF /compile_only /optimize /fast eurey3.f
DF /compile_only /optimize /fast evcorr.f
DF /compile_only /optimize /fast extra.f
DF /compile_only /optimize /fast extra1.f
DF /compile_only /optimize /fast extra2.f
DF /compile_only /optimize /fast extra3.f
DF /compile_only /optimize /fast fatal.f
DF /compile_only /optimize /fast fft3d.f
DF /compile_only /optimize /fast fftpack.f
DF /compile_only /optimize /fast field.f
DF /compile_only /optimize /fast final.f
DF /compile_only /optimize /fast flatten.f
DF /compile_only /optimize /fast freeunit.f
DF /compile_only /optimize /fast gda.f
DF /compile_only /optimize /fast geometry.f
DF /compile_only /optimize /fast getint.f
DF /compile_only /optimize /fast getkey.f
DF /compile_only /optimize /fast getmol.f
DF /compile_only /optimize /fast getmol2.f
DF /compile_only /optimize /fast getnumb.f
DF /compile_only /optimize /fast getpdb.f
DF /compile_only /optimize /fast getprm.f
DF /compile_only /optimize /fast getref.f
DF /compile_only /optimize /fast getstring.f
DF /compile_only /optimize /fast gettext.f
DF /compile_only /optimize /fast getword.f
DF /compile_only /optimize /fast getxyz.f
DF /compile_only /optimize /fast ghmcstep.f
DF /compile_only /optimize /fast gradient.f
DF /compile_only /optimize /fast gradrgd.f
DF /compile_only /optimize /fast gradrot.f
DF /compile_only /optimize /fast groups.f
DF /compile_only /optimize /fast grpline.f
DF /compile_only /optimize /fast gyrate.f
DF /compile_only /optimize /fast hessian.f
DF /compile_only /optimize /fast hessrgd.f
DF /compile_only /optimize /fast hessrot.f
DF /compile_only /optimize /fast hybrid.f
DF /compile_only /optimize /fast image.f
DF /compile_only /optimize /fast impose.f
DF /compile_only /optimize /fast induce.f
DF /compile_only /optimize /fast inertia.f
DF /compile_only /optimize /fast initatom.f
DF /compile_only /optimize /fast initial.f
DF /compile_only /optimize /fast initprm.f
DF /compile_only /optimize /fast initres.f
DF /compile_only /optimize /fast initrot.f
DF /compile_only /optimize /fast insert.f
DF /compile_only /optimize /fast intedit.f
DF /compile_only /optimize /fast intxyz.f
DF /compile_only /optimize /fast invbeta.f
DF /compile_only /optimize /fast invert.f
DF /compile_only /optimize /fast jacobi.f
DF /compile_only /optimize /fast kangang.f
DF /compile_only /optimize /fast kangle.f
DF /compile_only /optimize /fast katom.f
DF /compile_only /optimize /fast kbond.f
DF /compile_only /optimize /fast kcharge.f
DF /compile_only /optimize /fast kdipole.f
DF /compile_only /optimize /fast kewald.f
DF /compile_only /optimize /fast kextra.f
DF /compile_only /optimize /fast kgeom.f
DF /compile_only /optimize /fast kimprop.f
DF /compile_only /optimize /fast kimptor.f
DF /compile_only /optimize /fast kinetic.f
DF /compile_only /optimize /fast kmetal.f
DF /compile_only /optimize /fast kmpole.f
DF /compile_only /optimize /fast kopbend.f
DF /compile_only /optimize /fast kopdist.f
DF /compile_only /optimize /fast korbit.f
DF /compile_only /optimize /fast kpitors.f
DF /compile_only /optimize /fast kpolar.f
DF /compile_only /optimize /fast ksolv.f
DF /compile_only /optimize /fast kstrbnd.f
DF /compile_only /optimize /fast kstrtor.f
DF /compile_only /optimize /fast ktors.f
DF /compile_only /optimize /fast ktortor.f
DF /compile_only /optimize /fast kurey.f
DF /compile_only /optimize /fast kvdw.f
DF /compile_only /optimize /fast lattice.f
DF /compile_only /optimize /fast lbfgs.f
DF /compile_only /optimize /fast lights.f
DF /compile_only /optimize /fast makeint.f
DF /compile_only /optimize /fast makeref.f
DF /compile_only /optimize /fast makexyz.f
DF /compile_only /optimize /fast maxwell.f
DF /compile_only /optimize /fast mdinit.f
DF /compile_only /optimize /fast mdrest.f
DF /compile_only /optimize /fast mdsave.f
DF /compile_only /optimize /fast mdstat.f
DF /compile_only /optimize /fast mechanic.f
DF /compile_only /optimize /fast merge.f
DF /compile_only /optimize /fast minimize.f
DF /compile_only /optimize /fast minirot.f
DF /compile_only /optimize /fast minrigid.f
DF /compile_only /optimize /fast molecule.f
DF /compile_only /optimize /fast molxyz.f
DF /compile_only /optimize /fast moments.f
DF /compile_only /optimize /fast monte.f
DF /compile_only /optimize /fast mutate.f
DF /compile_only /optimize /fast nblist.f
DF /compile_only /optimize /fast newton.f
DF /compile_only /optimize /fast newtrot.f
DF /compile_only /optimize /fast nextarg.f
DF /compile_only /optimize /fast nexttext.f
DF /compile_only /optimize /fast nose.f
DF /compile_only /optimize /fast nspline.f
DF /compile_only /optimize /fast nucleic.f
DF /compile_only /optimize /fast number.f
DF /compile_only /optimize /fast numeral.f
DF /compile_only /optimize /fast numgrad.f
DF /compile_only /optimize /fast ocvm.f
DF /compile_only /optimize /fast openend.f
DF /compile_only /optimize /fast optimize.f
DF /compile_only /optimize /fast optirot.f
DF /compile_only /optimize /fast optrigid.f
DF /compile_only /optimize /fast optsave.f
DF /compile_only /optimize /fast orbital.f
DF /compile_only /optimize /fast orient.f
DF /compile_only /optimize /fast orthog.f
DF /compile_only /optimize /fast overlap.f
DF /compile_only /optimize /fast path.f
DF /compile_only /optimize /fast pdbxyz.f
DF /compile_only /optimize /fast picalc.f
DF /compile_only /optimize /fast pmestuff.f
DF /compile_only /optimize /fast pmpb.f
DF /compile_only /optimize /fast polarize.f
DF /compile_only /optimize /fast poledit.f
DF /compile_only /optimize /fast polymer.f
DF /compile_only /optimize /fast potential.f
DF /compile_only /optimize /fast precise.f
DF /compile_only /optimize /fast pressure.f
DF /compile_only /optimize /fast prmedit.f
DF /compile_only /optimize /fast prmkey.f
DF /compile_only /optimize /fast promo.f
DF /compile_only /optimize /fast protein.f
DF /compile_only /optimize /fast prtdyn.f
DF /compile_only /optimize /fast prterr.f
DF /compile_only /optimize /fast prtint.f
DF /compile_only /optimize /fast prtmol2.f
DF /compile_only /optimize /fast prtpdb.f
DF /compile_only /optimize /fast prtprm.f
DF /compile_only /optimize /fast prtseq.f
DF /compile_only /optimize /fast prtxyz.f
DF /compile_only /optimize /fast pss.f
DF /compile_only /optimize /fast pssrigid.f
DF /compile_only /optimize /fast pssrot.f
DF /compile_only /optimize /fast quatfit.f
DF /compile_only /optimize /fast radial.f
DF /compile_only /optimize /fast random.f
DF /compile_only /optimize /fast rattle.f
DF /compile_only /optimize /fast readdyn.f
DF /compile_only /optimize /fast readgau.f
DF /compile_only /optimize /fast readint.f
DF /compile_only /optimize /fast readmol.f
DF /compile_only /optimize /fast readmol2.f
DF /compile_only /optimize /fast readpdb.f
DF /compile_only /optimize /fast readprm.f
DF /compile_only /optimize /fast readseq.f
DF /compile_only /optimize /fast readxyz.f
DF /compile_only /optimize /fast replica.f
DF /compile_only /optimize /fast respa.f
DF /compile_only /optimize /fast rgdstep.f
DF /compile_only /optimize /fast rings.f
DF /compile_only /optimize /fast rmsfit.f
DF /compile_only /optimize /fast rotlist.f
DF /compile_only /optimize /fast rotpole.f
DF /compile_only /optimize /fast saddle.f
DF /compile_only /optimize /fast scan.f
DF /compile_only /optimize /fast sdstep.f
DF /compile_only /optimize /fast search.f
DF /compile_only /optimize /fast server.f
DF /compile_only /optimize /fast shakeup.f
DF /compile_only /optimize /fast sigmoid.f
DF /compile_only /optimize /fast sktstuff.f
DF /compile_only /optimize /fast sniffer.f
DF /compile_only /optimize /fast sort.f
DF /compile_only /optimize /fast spacefill.f
DF /compile_only /optimize /fast spectrum.f
DF /compile_only /optimize /fast square.f
DF /compile_only /optimize /fast suffix.f
DF /compile_only /optimize /fast superpose.f
DF /compile_only /optimize /fast surface.f
DF /compile_only /optimize /fast surfatom.f
DF /compile_only /optimize /fast switch.f
DF /compile_only /optimize /fast sybylxyz.f
DF /compile_only /optimize /fast temper.f
DF /compile_only /optimize /fast testgrad.f
DF /compile_only /optimize /fast testhess.f
DF /compile_only /optimize /fast testpair.f
DF /compile_only /optimize /fast testpol.f
DF /compile_only /optimize /fast testrot.f
DF /compile_only /optimize /fast timer.f
DF /compile_only /optimize /fast timerot.f
DF /compile_only /optimize /fast tncg.f
DF /compile_only /optimize /fast torphase.f
DF /compile_only /optimize /fast torque.f
DF /compile_only /optimize /fast torsfit.f
DF /compile_only /optimize /fast torsions.f
DF /compile_only /optimize /fast trimtext.f
DF /compile_only /optimize /fast unitcell.f
DF /compile_only /optimize /fast valence.f
DF /compile_only /optimize /fast verlet.f
DF /compile_only /optimize /fast version.f
DF /compile_only /optimize /fast vibbig.f
DF /compile_only /optimize /fast vibrate.f
DF /compile_only /optimize /fast vibrot.f
DF /compile_only /optimize /fast volume.f
DF /compile_only /optimize /fast xtalfit.f
DF /compile_only /optimize /fast xtalmin.f
DF /compile_only /optimize /fast xyzatm.f
DF /compile_only /optimize /fast xyzedit.f
DF /compile_only /optimize /fast xyzint.f
DF /compile_only /optimize /fast xyzpdb.f
DF /compile_only /optimize /fast xyzsybyl.f
DF /compile_only /optimize /fast zatom.f
