#
#
#  ############################################################
#  ##                                                        ##
#  ##  compile.make  --  compile each of the TINKER modules  ##
#  ##               (Mac OS X/gfortran Version)              ##
#  ##                                                        ##
#  ############################################################
#
#
gfortran -c -O3 active.f
gfortran -c -O3 alchemy.f
gfortran -c -O3 analysis.f
gfortran -c -O3 analyze.f
gfortran -c -O3 angles.f
gfortran -c -O3 anneal.f
gfortran -c -O3 archive.f
gfortran -c -O3 attach.f
gfortran -c -O3 basefile.f
gfortran -c -O3 beeman.f
gfortran -c -O3 bicubic.f
gfortran -c -O3 bitors.f
gfortran -c -O3 bonds.f
gfortran -c -O3 born.f
gfortran -c -O3 bounds.f
gfortran -c -O3 bussi.f
gfortran -c -O3 calendar.f
gfortran -c -O3 center.f
gfortran -c -O3 chkpole.f
gfortran -c -O3 chkring.f
gfortran -c -O3 chkxyz.f
gfortran -c -O3 cholesky.f
gfortran -c -O3 clock.f
gfortran -c -O3 cluster.f
gfortran -c -O3 column.f
gfortran -c -O3 command.f
gfortran -c -O3 connect.f
gfortran -c -O3 connolly.f
gfortran -c -O3 control.f
gfortran -c -O3 correlate.f
gfortran -c -O3 crystal.f
gfortran -c -O3 cspline.f
gfortran -c -O3 cutoffs.f
gfortran -c -O3 deflate.f
gfortran -c -O3 delete.f
gfortran -c -O3 diagq.f
gfortran -c -O3 diffeq.f
gfortran -c -O3 diffuse.f
gfortran -c -O3 distgeom.f
gfortran -c -O3 document.f
gfortran -c -O3 dynamic.f
gfortran -c -O3 eangang.f
gfortran -c -O3 eangang1.f
gfortran -c -O3 eangang2.f
gfortran -c -O3 eangang3.f
gfortran -c -O3 eangle.f
gfortran -c -O3 eangle1.f
gfortran -c -O3 eangle2.f
gfortran -c -O3 eangle3.f
gfortran -c -O3 ebond.f
gfortran -c -O3 ebond1.f
gfortran -c -O3 ebond2.f
gfortran -c -O3 ebond3.f
gfortran -c -O3 ebuck.f
gfortran -c -O3 ebuck1.f
gfortran -c -O3 ebuck2.f
gfortran -c -O3 ebuck3.f
gfortran -c -O3 echarge.f
gfortran -c -O3 echarge1.f
gfortran -c -O3 echarge2.f
gfortran -c -O3 echarge3.f
gfortran -c -O3 echgdpl.f
gfortran -c -O3 echgdpl1.f
gfortran -c -O3 echgdpl2.f
gfortran -c -O3 echgdpl3.f
gfortran -c -O3 edipole.f
gfortran -c -O3 edipole1.f
gfortran -c -O3 edipole2.f
gfortran -c -O3 edipole3.f
gfortran -c -O3 egauss.f
gfortran -c -O3 egauss1.f
gfortran -c -O3 egauss2.f
gfortran -c -O3 egauss3.f
gfortran -c -O3 egeom.f
gfortran -c -O3 egeom1.f
gfortran -c -O3 egeom2.f
gfortran -c -O3 egeom3.f
gfortran -c -O3 ehal.f
gfortran -c -O3 ehal1.f
gfortran -c -O3 ehal2.f
gfortran -c -O3 ehal3.f
gfortran -c -O3 eimprop.f
gfortran -c -O3 eimprop1.f
gfortran -c -O3 eimprop2.f
gfortran -c -O3 eimprop3.f
gfortran -c -O3 eimptor.f
gfortran -c -O3 eimptor1.f
gfortran -c -O3 eimptor2.f
gfortran -c -O3 eimptor3.f
gfortran -c -O3 elj.f
gfortran -c -O3 elj1.f
gfortran -c -O3 elj2.f
gfortran -c -O3 elj3.f
gfortran -c -O3 embed.f
gfortran -c -O3 emetal.f
gfortran -c -O3 emetal1.f
gfortran -c -O3 emetal2.f
gfortran -c -O3 emetal3.f
gfortran -c -O3 emm3hb.f
gfortran -c -O3 emm3hb1.f
gfortran -c -O3 emm3hb2.f
gfortran -c -O3 emm3hb3.f
gfortran -c -O3 empole.f
gfortran -c -O3 empole1.f
gfortran -c -O3 empole2.f
gfortran -c -O3 empole3.f
gfortran -c -O3 energy.f
gfortran -c -O3 eopbend.f
gfortran -c -O3 eopbend1.f
gfortran -c -O3 eopbend2.f
gfortran -c -O3 eopbend3.f
gfortran -c -O3 eopdist.f
gfortran -c -O3 eopdist1.f
gfortran -c -O3 eopdist2.f
gfortran -c -O3 eopdist3.f
gfortran -c -O3 epitors.f
gfortran -c -O3 epitors1.f
gfortran -c -O3 epitors2.f
gfortran -c -O3 epitors3.f
gfortran -c -O3 erf.f
gfortran -c -O3 erxnfld.f
gfortran -c -O3 erxnfld1.f
gfortran -c -O3 erxnfld2.f
gfortran -c -O3 erxnfld3.f
gfortran -c -O3 esolv.f
gfortran -c -O3 esolv1.f
gfortran -c -O3 esolv2.f
gfortran -c -O3 esolv3.f
gfortran -c -O3 estrbnd.f
gfortran -c -O3 estrbnd1.f
gfortran -c -O3 estrbnd2.f
gfortran -c -O3 estrbnd3.f
gfortran -c -O3 estrtor.f
gfortran -c -O3 estrtor1.f
gfortran -c -O3 estrtor2.f
gfortran -c -O3 estrtor3.f
gfortran -c -O3 etors.f
gfortran -c -O3 etors1.f
gfortran -c -O3 etors2.f
gfortran -c -O3 etors3.f
gfortran -c -O3 etortor.f
gfortran -c -O3 etortor1.f
gfortran -c -O3 etortor2.f
gfortran -c -O3 etortor3.f
gfortran -c -O3 eurey.f
gfortran -c -O3 eurey1.f
gfortran -c -O3 eurey2.f
gfortran -c -O3 eurey3.f
gfortran -c -O3 evcorr.f
gfortran -c -O3 extra.f
gfortran -c -O3 extra1.f
gfortran -c -O3 extra2.f
gfortran -c -O3 extra3.f
gfortran -c -O3 fatal.f
gfortran -c -O3 fft3d.f
gfortran -c -O3 fftpack.f
gfortran -c -O3 field.f
gfortran -c -O3 final.f
gfortran -c -O3 flatten.f
gfortran -c -O3 freeunit.f
gfortran -c -O3 gda.f
gfortran -c -O3 geometry.f
gfortran -c -O3 getint.f
gfortran -c -O3 getkey.f
gfortran -c -O3 getmol2.f
gfortran -c -O3 getnumb.f
gfortran -c -O3 getpdb.f
gfortran -c -O3 getprm.f
gfortran -c -O3 getref.f
gfortran -c -O3 getstring.f
gfortran -c -O3 gettext.f
gfortran -c -O3 getword.f
gfortran -c -O3 getxyz.f
gfortran -c -O3 ghmcstep.f
gfortran -c -O3 gradient.f
gfortran -c -O3 gradrgd.f
gfortran -c -O3 gradrot.f
gfortran -c -O3 groups.f
gfortran -c -O3 grpline.f
gfortran -c -O3 gyrate.f
gfortran -c -O3 hessian.f
gfortran -c -O3 hessrgd.f
gfortran -c -O3 hessrot.f
gfortran -c -O3 hybrid.f
gfortran -c -O3 image.f
gfortran -c -O3 impose.f
gfortran -c -O3 induce.f
gfortran -c -O3 inertia.f
gfortran -c -O3 initial.f
gfortran -c -O3 initprm.f
gfortran -c -O3 initres.f
gfortran -c -O3 initrot.f
gfortran -c -O3 insert.f
gfortran -c -O3 intedit.f
gfortran -c -O3 intxyz.f
gfortran -c -O3 invbeta.f
gfortran -c -O3 invert.f
gfortran -c -O3 jacobi.f
gfortran -c -O3 kangang.f
gfortran -c -O3 kangle.f
gfortran -c -O3 katom.f
gfortran -c -O3 kbond.f
gfortran -c -O3 kcharge.f
gfortran -c -O3 kdipole.f
gfortran -c -O3 kewald.f
gfortran -c -O3 kgeom.f
gfortran -c -O3 kimprop.f
gfortran -c -O3 kimptor.f
gfortran -c -O3 kinetic.f
gfortran -c -O3 kmetal.f
gfortran -c -O3 kmpole.f
gfortran -c -O3 kopbend.f
gfortran -c -O3 kopdist.f
gfortran -c -O3 korbit.f
gfortran -c -O3 kpitors.f
gfortran -c -O3 kpolar.f
gfortran -c -O3 ksolv.f
gfortran -c -O3 kstrbnd.f
gfortran -c -O3 kstrtor.f
gfortran -c -O3 ktors.f
gfortran -c -O3 ktortor.f
gfortran -c -O3 kurey.f
gfortran -c -O3 kvdw.f
gfortran -c -O3 lattice.f
gfortran -c -O3 lbfgs.f
gfortran -c -O3 lights.f
gfortran -c -O3 makeint.f
gfortran -c -O3 makeref.f
gfortran -c -O3 makexyz.f
gfortran -c -O3 maxwell.f
gfortran -c -O3 mdinit.f
gfortran -c -O3 mdrest.f
gfortran -c -O3 mdsave.f
gfortran -c -O3 mdstat.f
gfortran -c -O3 mechanic.f
gfortran -c -O3 merge.f
gfortran -c -O3 minimize.f
gfortran -c -O3 minirot.f
gfortran -c -O3 minrigid.f
gfortran -c -O3 molecule.f
gfortran -c -O3 moments.f
gfortran -c -O3 monte.f
gfortran -c -O3 mutate.f
gfortran -c -O3 nblist.f
gfortran -c -O3 newton.f
gfortran -c -O3 newtrot.f
gfortran -c -O3 nextarg.f
gfortran -c -O3 nexttext.f
gfortran -c -O3 nspline.f
gfortran -c -O3 nucleic.f
gfortran -c -O3 number.f
gfortran -c -O3 numeral.f
gfortran -c -O3 numgrad.f
gfortran -c -O3 ocvm.f
gfortran -c -O3 openend.f
gfortran -c -O3 optimize.f
gfortran -c -O3 optirot.f
gfortran -c -O3 optrigid.f
gfortran -c -O3 optsave.f
gfortran -c -O3 orbital.f
gfortran -c -O3 orient.f
gfortran -c -O3 orthog.f
gfortran -c -O3 overlap.f
gfortran -c -O3 path.f
gfortran -c -O3 pdbxyz.f
gfortran -c -O3 piscf.f
gfortran -c -O3 pmestuff.f
gfortran -c -O3 pmpb.f
gfortran -c -O3 polarize.f
gfortran -c -O3 poledit.f
gfortran -c -O3 polymer.f
gfortran -c -O3 potential.f
gfortran -c -O3 precise.f
gfortran -c -O3 pressure.f
gfortran -c -O3 prmedit.f
gfortran -c -O3 prmkey.f
gfortran -c -O3 promo.f
gfortran -c -O3 protein.f
gfortran -c -O3 prtdyn.f
gfortran -c -O3 prterr.f
gfortran -c -O3 prtint.f
gfortran -c -O3 prtmol2.f
gfortran -c -O3 prtpdb.f
gfortran -c -O3 prtprm.f
gfortran -c -O3 prtseq.f
gfortran -c -O3 prtxyz.f
gfortran -c -O3 pss.f
gfortran -c -O3 pssrigid.f
gfortran -c -O3 pssrot.f
gfortran -c -O3 quatfit.f
gfortran -c -O3 radial.f
gfortran -c -O3 random.f
gfortran -c -O3 rattle.f
gfortran -c -O3 readdyn.f
gfortran -c -O3 readgau.f
gfortran -c -O3 readint.f
gfortran -c -O3 readmol2.f
gfortran -c -O3 readpdb.f
gfortran -c -O3 readprm.f
gfortran -c -O3 readseq.f
gfortran -c -O3 readxyz.f
gfortran -c -O3 replica.f
gfortran -c -O3 respa.f
gfortran -c -O3 rgdstep.f
gfortran -c -O3 rings.f
gfortran -c -O3 rmsfit.f
gfortran -c -O3 rotlist.f
gfortran -c -O3 rotpole.f
gfortran -c -O3 saddle.f
gfortran -c -O3 scan.f
gfortran -c -O3 sdstep.f
gfortran -c -O3 search.f
gfortran -c -O3 server.f
gfortran -c -O3 shakeup.f
gfortran -c -O3 sigmoid.f
gfortran -c -O3 sktstuff.f
gfortran -c -O3 sniffer.f
gfortran -c -O3 sort.f
gfortran -c -O3 spacefill.f
gfortran -c -O3 spectrum.f
gfortran -c -O3 square.f
gfortran -c -O3 suffix.f
gfortran -c -O3 superpose.f
gfortran -c -O3 surface.f
gfortran -c -O3 surfatom.f
gfortran -c -O3 switch.f
gfortran -c -O3 sybylxyz.f
gfortran -c -O3 temper.f
gfortran -c -O3 testgrad.f
gfortran -c -O3 testhess.f
gfortran -c -O3 testpair.f
gfortran -c -O3 testrot.f
gfortran -c -O3 timer.f
gfortran -c -O3 timerot.f
gfortran -c -O3 tncg.f
gfortran -c -O3 torphase.f
gfortran -c -O3 torque.f
gfortran -c -O3 torsfit.f
gfortran -c -O3 torsions.f
gfortran -c -O3 trimtext.f
gfortran -c -O3 unitcell.f
gfortran -c -O3 valence.f
gfortran -c -O3 verlet.f
gfortran -c -O3 version.f
gfortran -c -O3 vibbig.f
gfortran -c -O3 vibrate.f
gfortran -c -O3 vibrot.f
gfortran -c -O3 volume.f
gfortran -c -O3 xtalfit.f
gfortran -c -O3 xtalmin.f
gfortran -c -O3 xyzatm.f
gfortran -c -O3 xyzedit.f
gfortran -c -O3 xyzint.f
gfortran -c -O3 xyzpdb.f
gfortran -c -O3 xyzsybyl.f
gfortran -c -O3 zatom.f
