#
#
#  ############################################################
#  ##                                                        ##
#  ##  compile.make  --  compile each of the TINKER modules  ##
#  ##                 (Linux/GNU g77 Version)                ##
#  ##                                                        ##
#  ############################################################
#
#
g77 -c -O3 -ffast-math active.f
g77 -c -O3 -ffast-math alchemy.f
g77 -c -O3 -ffast-math analysis.f
g77 -c -O3 -ffast-math analyze.f
g77 -c -O3 -ffast-math angles.f
g77 -c -O3 -ffast-math anneal.f
g77 -c -O3 -ffast-math archive.f
g77 -c -O3 -ffast-math attach.f
g77 -c -O3 -ffast-math basefile.f
g77 -c -O3 -ffast-math beeman.f
g77 -c -O3 -ffast-math bicubic.f
g77 -c -O3 -ffast-math bitors.f
g77 -c -O3 -ffast-math bonds.f
g77 -c -O3 -ffast-math born.f
g77 -c -O3 -ffast-math bounds.f
g77 -c -O3 -ffast-math bspline.f
g77 -c -O3 -ffast-math calendar.f
g77 -c -O3 -ffast-math center.f
g77 -c -O3 -ffast-math chkpole.f
g77 -c -O3 -ffast-math chkring.f
g77 -c -O3 -ffast-math chkxyz.f
g77 -c -O3 -ffast-math cholesky.f
g77 -c -O3 -ffast-math clock.f
g77 -c -O3 -ffast-math cluster.f
g77 -c -O3 -ffast-math column.f
g77 -c -O3 -ffast-math command.f
g77 -c -O3 -ffast-math connect.f
g77 -c -O3 -ffast-math connolly.f
g77 -c -O3 -ffast-math control.f
g77 -c -O3 -ffast-math correlate.f
g77 -c -O3 -ffast-math crystal.f
g77 -c -O3 -ffast-math cspline.f
g77 -c -O3 -ffast-math cutoffs.f
g77 -c -O3 -ffast-math deflate.f
g77 -c -O3 -ffast-math delete.f
g77 -c -O3 -ffast-math diagq.f
g77 -c -O3 -ffast-math diffeq.f
g77 -c -O3 -ffast-math diffuse.f
g77 -c -O3 -ffast-math distgeom.f
g77 -c -O3 -ffast-math document.f
g77 -c -O3 -ffast-math dynamic.f
g77 -c -O3 -ffast-math eangang.f
g77 -c -O3 -ffast-math eangang1.f
g77 -c -O3 -ffast-math eangang2.f
g77 -c -O3 -ffast-math eangang3.f
g77 -c -O3 -ffast-math eangle.f
g77 -c -O3 -ffast-math eangle1.f
g77 -c -O3 -ffast-math eangle2.f
g77 -c -O3 -ffast-math eangle3.f
g77 -c -O3 -ffast-math ebond.f
g77 -c -O3 -ffast-math ebond1.f
g77 -c -O3 -ffast-math ebond2.f
g77 -c -O3 -ffast-math ebond3.f
g77 -c -O3 -ffast-math ebuck.f
g77 -c -O3 -ffast-math ebuck1.f
g77 -c -O3 -ffast-math ebuck2.f
g77 -c -O3 -ffast-math ebuck3.f
g77 -c -O3 -ffast-math echarge.f
g77 -c -O3 -ffast-math echarge1.f
g77 -c -O3 -ffast-math echarge2.f
g77 -c -O3 -ffast-math echarge3.f
g77 -c -O3 -ffast-math echgdpl.f
g77 -c -O3 -ffast-math echgdpl1.f
g77 -c -O3 -ffast-math echgdpl2.f
g77 -c -O3 -ffast-math echgdpl3.f
g77 -c -O3 -ffast-math edipole.f
g77 -c -O3 -ffast-math edipole1.f
g77 -c -O3 -ffast-math edipole2.f
g77 -c -O3 -ffast-math edipole3.f
g77 -c -O3 -ffast-math egauss.f
g77 -c -O3 -ffast-math egauss1.f
g77 -c -O3 -ffast-math egauss2.f
g77 -c -O3 -ffast-math egauss3.f
g77 -c -O3 -ffast-math egeom.f
g77 -c -O3 -ffast-math egeom1.f
g77 -c -O3 -ffast-math egeom2.f
g77 -c -O3 -ffast-math egeom3.f
g77 -c -O3 -ffast-math ehal.f
g77 -c -O3 -ffast-math ehal1.f
g77 -c -O3 -ffast-math ehal2.f
g77 -c -O3 -ffast-math ehal3.f
g77 -c -O3 -ffast-math eimprop.f
g77 -c -O3 -ffast-math eimprop1.f
g77 -c -O3 -ffast-math eimprop2.f
g77 -c -O3 -ffast-math eimprop3.f
g77 -c -O3 -ffast-math eimptor.f
g77 -c -O3 -ffast-math eimptor1.f
g77 -c -O3 -ffast-math eimptor2.f
g77 -c -O3 -ffast-math eimptor3.f
g77 -c -O3 -ffast-math elj.f
g77 -c -O3 -ffast-math elj1.f
g77 -c -O3 -ffast-math elj2.f
g77 -c -O3 -ffast-math elj3.f
g77 -c -O3 -ffast-math embed.f
g77 -c -O3 -ffast-math emetal.f
g77 -c -O3 -ffast-math emetal1.f
g77 -c -O3 -ffast-math emetal2.f
g77 -c -O3 -ffast-math emetal3.f
g77 -c -O3 -ffast-math emm3hb.f
g77 -c -O3 -ffast-math emm3hb1.f
g77 -c -O3 -ffast-math emm3hb2.f
g77 -c -O3 -ffast-math emm3hb3.f
g77 -c -O3 -ffast-math empole.f
g77 -c -O3 -ffast-math empole1.f
g77 -c -O3 -ffast-math empole2.f
g77 -c -O3 -ffast-math empole3.f
g77 -c -O3 -ffast-math energy.f
g77 -c -O3 -ffast-math eopbend.f
g77 -c -O3 -ffast-math eopbend1.f
g77 -c -O3 -ffast-math eopbend2.f
g77 -c -O3 -ffast-math eopbend3.f
g77 -c -O3 -ffast-math eopdist.f
g77 -c -O3 -ffast-math eopdist1.f
g77 -c -O3 -ffast-math eopdist2.f
g77 -c -O3 -ffast-math eopdist3.f
g77 -c -O3 -ffast-math epitors.f
g77 -c -O3 -ffast-math epitors1.f
g77 -c -O3 -ffast-math epitors2.f
g77 -c -O3 -ffast-math epitors3.f
g77 -c -O3 -ffast-math erf.f
g77 -c -O3 -ffast-math erxnfld.f
g77 -c -O3 -ffast-math erxnfld1.f
g77 -c -O3 -ffast-math erxnfld2.f
g77 -c -O3 -ffast-math erxnfld3.f
g77 -c -O3 -ffast-math esolv.f
g77 -c -O3 -ffast-math esolv1.f
g77 -c -O3 -ffast-math esolv2.f
g77 -c -O3 -ffast-math esolv3.f
g77 -c -O3 -ffast-math estrbnd.f
g77 -c -O3 -ffast-math estrbnd1.f
g77 -c -O3 -ffast-math estrbnd2.f
g77 -c -O3 -ffast-math estrbnd3.f
g77 -c -O3 -ffast-math estrtor.f
g77 -c -O3 -ffast-math estrtor1.f
g77 -c -O3 -ffast-math estrtor2.f
g77 -c -O3 -ffast-math estrtor3.f
g77 -c -O3 -ffast-math etors.f
g77 -c -O3 -ffast-math etors1.f
g77 -c -O3 -ffast-math etors2.f
g77 -c -O3 -ffast-math etors3.f
g77 -c -O3 -ffast-math etortor.f
g77 -c -O3 -ffast-math etortor1.f
g77 -c -O3 -ffast-math etortor2.f
g77 -c -O3 -ffast-math etortor3.f
g77 -c -O3 -ffast-math eurey.f
g77 -c -O3 -ffast-math eurey1.f
g77 -c -O3 -ffast-math eurey2.f
g77 -c -O3 -ffast-math eurey3.f
g77 -c -O3 -ffast-math evcorr.f
g77 -c -O3 -ffast-math extra.f
g77 -c -O3 -ffast-math extra1.f
g77 -c -O3 -ffast-math extra2.f
g77 -c -O3 -ffast-math extra3.f
g77 -c -O3 -ffast-math fatal.f
g77 -c -O3 -ffast-math fft3d.f
g77 -c -O3 -ffast-math fftpack.f
g77 -c -O3 -ffast-math field.f
g77 -c -O3 -ffast-math final.f
g77 -c -O3 -ffast-math flatten.f
g77 -c -O3 -ffast-math freeunit.f
g77 -c -O3 -ffast-math gda.f
g77 -c -O3 -ffast-math geometry.f
g77 -c -O3 -ffast-math getime.f
g77 -c -O3 -ffast-math getint.f
g77 -c -O3 -ffast-math getkey.f
g77 -c -O3 -ffast-math getmol2.f
g77 -c -O3 -ffast-math getnumb.f
g77 -c -O3 -ffast-math getpdb.f
g77 -c -O3 -ffast-math getprm.f
g77 -c -O3 -ffast-math getref.f
g77 -c -O3 -ffast-math getstring.f
g77 -c -O3 -ffast-math gettext.f
g77 -c -O3 -ffast-math getword.f
g77 -c -O3 -ffast-math getxyz.f
g77 -c -O3 -ffast-math gradient.f
g77 -c -O3 -ffast-math gradrgd.f
g77 -c -O3 -ffast-math gradrot.f
g77 -c -O3 -ffast-math groups.f
g77 -c -O3 -ffast-math grpline.f
g77 -c -O3 -ffast-math gyrate.f
g77 -c -O3 -ffast-math hessian.f
g77 -c -O3 -ffast-math hessrgd.f
g77 -c -O3 -ffast-math hessrot.f
g77 -c -O3 -ffast-math hybrid.f
g77 -c -O3 -ffast-math image.f
g77 -c -O3 -ffast-math impose.f
g77 -c -O3 -ffast-math induce.f
g77 -c -O3 -ffast-math inertia.f
g77 -c -O3 -ffast-math initial.f
g77 -c -O3 -ffast-math initprm.f
g77 -c -O3 -ffast-math initres.f
g77 -c -O3 -ffast-math initrot.f
g77 -c -O3 -ffast-math insert.f
g77 -c -O3 -ffast-math intedit.f
g77 -c -O3 -ffast-math intxyz.f
g77 -c -O3 -ffast-math invbeta.f
g77 -c -O3 -ffast-math invert.f
g77 -c -O3 -ffast-math jacobi.f
g77 -c -O3 -ffast-math kangang.f
g77 -c -O3 -ffast-math kangle.f
g77 -c -O3 -ffast-math katom.f
g77 -c -O3 -ffast-math kbond.f
g77 -c -O3 -ffast-math kcharge.f
g77 -c -O3 -ffast-math kdipole.f
g77 -c -O3 -ffast-math kewald.f
g77 -c -O3 -ffast-math kgeom.f
g77 -c -O3 -ffast-math kimprop.f
g77 -c -O3 -ffast-math kimptor.f
g77 -c -O3 -ffast-math kinetic.f
g77 -c -O3 -ffast-math kmetal.f
g77 -c -O3 -ffast-math kmpole.f
g77 -c -O3 -ffast-math kopbend.f
g77 -c -O3 -ffast-math kopdist.f
g77 -c -O3 -ffast-math korbit.f
g77 -c -O3 -ffast-math kpitors.f
g77 -c -O3 -ffast-math kpolar.f
g77 -c -O3 -ffast-math ksolv.f
g77 -c -O3 -ffast-math kstrbnd.f
g77 -c -O3 -ffast-math kstrtor.f
g77 -c -O3 -ffast-math ktors.f
g77 -c -O3 -ffast-math ktortor.f
g77 -c -O3 -ffast-math kurey.f
g77 -c -O3 -ffast-math kvdw.f
g77 -c -O3 -ffast-math lattice.f
g77 -c -O3 -ffast-math lbfgs.f
g77 -c -O3 -ffast-math lights.f
g77 -c -O3 -ffast-math makeint.f
g77 -c -O3 -ffast-math makepdb.f
g77 -c -O3 -ffast-math makeref.f
g77 -c -O3 -ffast-math makexyz.f
g77 -c -O3 -ffast-math maxwell.f
g77 -c -O3 -ffast-math mdinit.f
g77 -c -O3 -ffast-math mdrest.f
g77 -c -O3 -ffast-math mdsave.f
g77 -c -O3 -ffast-math mdstat.f
g77 -c -O3 -ffast-math mechanic.f
g77 -c -O3 -ffast-math merge.f
g77 -c -O3 -ffast-math minimize.f
g77 -c -O3 -ffast-math minirot.f
g77 -c -O3 -ffast-math minrigid.f
g77 -c -O3 -ffast-math molecule.f
g77 -c -O3 -ffast-math moments.f
g77 -c -O3 -ffast-math monte.f
g77 -c -O3 -ffast-math mutate.f
g77 -c -O3 -ffast-math nblist.f
g77 -c -O3 -ffast-math newton.f
g77 -c -O3 -ffast-math newtrot.f
g77 -c -O3 -ffast-math nextarg.f
g77 -c -O3 -ffast-math nexttext.f
g77 -c -O3 -ffast-math nspline.f
g77 -c -O3 -ffast-math nucleic.f
g77 -c -O3 -ffast-math number.f
g77 -c -O3 -ffast-math numeral.f
g77 -c -O3 -ffast-math numgrad.f
g77 -c -O3 -ffast-math ocvm.f
g77 -c -O3 -ffast-math openend.f
g77 -c -O3 -ffast-math optimize.f
g77 -c -O3 -ffast-math optirot.f
g77 -c -O3 -ffast-math optrigid.f
g77 -c -O3 -ffast-math optsave.f
g77 -c -O3 -ffast-math orbital.f
g77 -c -O3 -ffast-math orient.f
g77 -c -O3 -ffast-math orthog.f
g77 -c -O3 -ffast-math overlap.f
g77 -c -O3 -ffast-math path.f
g77 -c -O3 -ffast-math pdbxyz.f
g77 -c -O3 -ffast-math piscf.f
g77 -c -O3 -ffast-math pmestuff.f
g77 -c -O3 -ffast-math pmpb.f
g77 -c -O3 -ffast-math polarize.f
g77 -c -O3 -ffast-math poledit.f
g77 -c -O3 -ffast-math polymer.f
g77 -c -O3 -ffast-math potential.f
g77 -c -O3 -ffast-math precise.f
g77 -c -O3 -ffast-math pressure.f
g77 -c -O3 -ffast-math prmedit.f
g77 -c -O3 -ffast-math prmkey.f
g77 -c -O3 -ffast-math promo.f
g77 -c -O3 -ffast-math protein.f
g77 -c -O3 -ffast-math prtdyn.f
g77 -c -O3 -ffast-math prterr.f
g77 -c -O3 -ffast-math prtint.f
g77 -c -O3 -ffast-math prtmol2.f
g77 -c -O3 -ffast-math prtpdb.f
g77 -c -O3 -ffast-math prtprm.f
g77 -c -O3 -ffast-math prtseq.f
g77 -c -O3 -ffast-math prtxyz.f
g77 -c -O3 -ffast-math pss.f
g77 -c -O3 -ffast-math pssrigid.f
g77 -c -O3 -ffast-math pssrot.f
g77 -c -O3 -ffast-math quatfit.f
g77 -c -O3 -ffast-math radial.f
g77 -c -O3 -ffast-math random.f
g77 -c -O3 -ffast-math rattle.f
g77 -c -O3 -ffast-math readdyn.f
g77 -c -O3 -ffast-math readgau.f
g77 -c -O3 -ffast-math readint.f
g77 -c -O3 -ffast-math readmol2.f
g77 -c -O3 -ffast-math readpdb.f
g77 -c -O3 -ffast-math readprm.f
g77 -c -O3 -ffast-math readseq.f
g77 -c -O3 -ffast-math readxyz.f
g77 -c -O3 -ffast-math replica.f
g77 -c -O3 -ffast-math rgdstep.f
g77 -c -O3 -ffast-math rings.f
g77 -c -O3 -ffast-math rmsfit.f
g77 -c -O3 -ffast-math rotlist.f
g77 -c -O3 -ffast-math rotpole.f
g77 -c -O3 -ffast-math saddle.f
g77 -c -O3 -ffast-math scan.f
g77 -c -O3 -ffast-math sdstep.f
g77 -c -O3 -ffast-math search.f
g77 -c -O3 -ffast-math server.f
g77 -c -O3 -ffast-math setime.f
g77 -c -O3 -ffast-math shakeup.f
g77 -c -O3 -ffast-math sigmoid.f
g77 -c -O3 -ffast-math sktstuff.f
g77 -c -O3 -ffast-math sniffer.f
g77 -c -O3 -ffast-math sort.f
g77 -c -O3 -ffast-math spacefill.f
g77 -c -O3 -ffast-math spectrum.f
g77 -c -O3 -ffast-math square.f
g77 -c -O3 -ffast-math suffix.f
g77 -c -O3 -ffast-math superpose.f
g77 -c -O3 -ffast-math surface.f
g77 -c -O3 -ffast-math surfatom.f
g77 -c -O3 -ffast-math switch.f
g77 -c -O3 -ffast-math sybylxyz.f
g77 -c -O3 -ffast-math temper.f
g77 -c -O3 -ffast-math testgrad.f
g77 -c -O3 -ffast-math testhess.f
g77 -c -O3 -ffast-math testpair.f
g77 -c -O3 -ffast-math testrot.f
g77 -c -O3 -ffast-math timer.f
g77 -c -O3 -ffast-math timerot.f
g77 -c -O3 -ffast-math tncg.f
g77 -c -O3 -ffast-math torphase.f
g77 -c -O3 -ffast-math torque.f
g77 -c -O3 -ffast-math torsions.f
g77 -c -O3 -ffast-math trimtext.f
g77 -c -O3 -ffast-math unitcell.f
g77 -c -O3 -ffast-math valence.f
g77 -c -O3 -ffast-math verlet.f
g77 -c -O3 -ffast-math version.f
g77 -c -O3 -ffast-math vibbig.f
g77 -c -O3 -ffast-math vibrate.f
g77 -c -O3 -ffast-math vibrot.f
g77 -c -O3 -ffast-math volume.f
g77 -c -O3 -ffast-math xtalfit.f
g77 -c -O3 -ffast-math xtalmin.f
g77 -c -O3 -ffast-math xyzatm.f
g77 -c -O3 -ffast-math xyzedit.f
g77 -c -O3 -ffast-math xyzint.f
g77 -c -O3 -ffast-math xyzpdb.f
g77 -c -O3 -ffast-math xyzsybyl.f
g77 -c -O3 -ffast-math zatom.f
