#pragma once

#include "macro.hh"

#ifdef __cplusplus
extern "C" {
#endif
extern int TINKER_MOD(dlmda, elmdaapmn);
extern int TINKER_MOD(dlmda, elmdaexp);
extern int TINKER_MOD(dlmda, elmdainvn);
extern int TINKER_MOD(dlmda, emdtexp);
extern int TINKER_MOD(dlmda, epdtexp);
extern int TINKER_MOD(dlmda, erelst0);
extern int TINKER_MOD(dlmda, erelst1);
extern int TINKER_MOD(dlmda, evdtexp);
extern int TINKER_MOD(dlmda, lmdaintv);
extern int TINKER_MOD(dlmda, lmdanpa);
extern int TINKER_MOD(dlmda, lmdanpb);
extern int TINKER_MOD(dlmda, lmdanpc);
extern int TINKER_MOD(dlmda, lmdastep);
extern int TINKER_MOD(dlmda, nlmda);
extern int TINKER_MOD(dlmda, nlmdahist);
extern int TINKER_MOD(dlmda, nlmdasave);
#define TINKER_MOD__nrelsub 5
extern int TINKER_MOD(dlmda, plmdaapmn);
extern int TINKER_MOD(dlmda, plmdaexp);
extern int TINKER_MOD(dlmda, plmdainvn);
extern int TINKER_MOD(dlmda, prelst0);
extern int TINKER_MOD(dlmda, prelst1);
#define TINKER_MOD__rellig1 1
#define TINKER_MOD__rellig2 2
#define TINKER_MOD__relnone 3
extern int TINKER_MOD(dlmda, sizelmdahist);
extern int TINKER_MOD(dlmda, vlmdaapmn);
extern int TINKER_MOD(dlmda, vlmdaexp);
extern int TINKER_MOD(dlmda, vlmdainvn);
extern int TINKER_MOD(dlmda, vrelst0);
extern int TINKER_MOD(dlmda, vrelst1);
extern int* TINKER_MOD(dlmda, lmdaihist);
extern double TINKER_MOD(dlmda, d2edl2);
extern double TINKER_MOD(dlmda, d2eldlmda2);
extern double TINKER_MOD(dlmda, d2emdl2);
extern double TINKER_MOD(dlmda, d2epdl2);
extern double TINKER_MOD(dlmda, d2evdl2);
extern double TINKER_MOD(dlmda, d2pldlmda2);
extern double TINKER_MOD(dlmda, d2vldlmda2);
extern double TINKER_MOD(dlmda, dedl);
extern double TINKER_MOD(dlmda, dedlavg);
extern double TINKER_MOD(dlmda, dedlstd);
extern double TINKER_MOD(dlmda, deffdl);
extern double TINKER_MOD(dlmda, deldlmda);
extern double TINKER_MOD(dlmda, demdl);
extern double TINKER_MOD(dlmda, depdl);
extern double TINKER_MOD(dlmda, devdl);
extern double TINKER_MOD(dlmda, dpldlmda);
extern double TINKER_MOD(dlmda, dvldlmda);
extern double TINKER_MOD(dlmda, elmdaapmrho);
extern double TINKER_MOD(dlmda, elmdainveps);
extern double TINKER_MOD(dlmda, lmdaavg);
extern double TINKER_MOD(dlmda, lmdaddgdl);
extern double TINKER_MOD(dlmda, lmdadeltag);
extern double TINKER_MOD(dlmda, lmdadfdl);
extern double TINKER_MOD(dlmda, lmdadt);
extern double TINKER_MOD(dlmda, lmdafric);
extern double TINKER_MOD(dlmda, lmdamass);
extern double TINKER_MOD(dlmda, lmdaparatio);
extern double TINKER_MOD(dlmda, lmdapbratio);
extern double TINKER_MOD(dlmda, lmdapcratio);
extern double TINKER_MOD(dlmda, lmdastd);
extern double TINKER_MOD(dlmda, lmdatheta);
extern double TINKER_MOD(dlmda, lmdavbias);
extern double TINKER_MOD(dlmda, lmdavtheta);
extern double TINKER_MOD(dlmda, plmdaapmrho);
extern double TINKER_MOD(dlmda, plmdainveps);
extern double TINKER_MOD(dlmda, qntelmda0);
extern double TINKER_MOD(dlmda, qntelmda1);
extern double TINKER_MOD(dlmda, qntplmda0);
extern double TINKER_MOD(dlmda, qntplmda1);
extern double TINKER_MOD(dlmda, qntvlmda0);
extern double TINKER_MOD(dlmda, qntvlmda1);
extern double TINKER_MOD(dlmda, vlmdaapmrho);
extern double TINKER_MOD(dlmda, vlmdainveps);
extern double TINKER_MOD(dlmda, wlmda);
extern double TINKER_MOD(dlmda, wlmda2);
extern double TINKER_MOD(dlmda, demvirdl)[3][3];
extern double TINKER_MOD(dlmda, depvirdl)[3][3];
extern double TINKER_MOD(dlmda, devvirdl)[3][3];
extern double TINKER_MOD(dlmda, dvirdl)[3][3];
extern double* TINKER_MOD(dlmda, bdplorig);
extern double* TINKER_MOD(dlmda, bflxorig);
extern double* TINKER_MOD(dlmda, lmdafhist);
extern double* TINKER_MOD(dlmda, lmdaflist);
extern double* TINKER_MOD(dlmda, lmdafmean);
extern double* TINKER_MOD(dlmda, lmdafsum);
extern double* TINKER_MOD(dlmda, lmdafwt);
extern double* TINKER_MOD(dlmda, lmdalhist);
extern double* TINKER_MOD(dlmda, lmdallist);
extern double* TINKER_MOD(dlmda, pchg0orig);
extern double* TINKER_MOD(dlmda, pchgorig);
extern double* TINKER_MOD(dlmda, pcoreorig);
extern double* TINKER_MOD(dlmda, polarityorig);
extern double* TINKER_MOD(dlmda, pval0orig);
extern double* TINKER_MOD(dlmda, pvalorig);
extern double* TINKER_MOD(dlmda, abflxorig);
extern double* TINKER_MOD(dlmda, aflxorig);
extern double* TINKER_MOD(dlmda, dfmdl);
extern double* TINKER_MOD(dlmda, dfpdl);
extern double* TINKER_MOD(dlmda, dfsumdl);
extern double* TINKER_MOD(dlmda, dfvdl);
extern double* TINKER_MOD(dlmda, lcmp);
extern double* TINKER_MOD(dlmda, lcphi);
extern double* TINKER_MOD(dlmda, lfmp);
extern double* TINKER_MOD(dlmda, lfphi);
extern double* TINKER_MOD(dlmda, poleorig);
extern double* TINKER_MOD(dlmda, lqgrid);
extern int TINKER_MOD(dlmda, lmdatrial);
extern int TINKER_MOD(dlmda, use_abf);
extern int TINKER_MOD(dlmda, use_abfdyn);
extern int TINKER_MOD(dlmda, use_dlmda);
extern int TINKER_MOD(dlmda, use_edlmda);
extern int TINKER_MOD(dlmda, use_elmdamap);
extern int TINKER_MOD(dlmda, use_emdt);
extern int TINKER_MOD(dlmda, use_epdt);
extern int TINKER_MOD(dlmda, use_evdt);
extern int TINKER_MOD(dlmda, use_mainlmda);
extern int TINKER_MOD(dlmda, use_meta);
extern int TINKER_MOD(dlmda, use_metadyn);
extern int TINKER_MOD(dlmda, use_ost);
extern int TINKER_MOD(dlmda, use_ostdyn);
extern int TINKER_MOD(dlmda, use_pdlmda);
extern int TINKER_MOD(dlmda, use_plmda);
extern int TINKER_MOD(dlmda, use_plmdamap);
extern int TINKER_MOD(dlmda, use_relstage);
extern int TINKER_MOD(dlmda, use_ti);
extern int TINKER_MOD(dlmda, use_vdlmda);
extern int TINKER_MOD(dlmda, use_vlmdamap);
extern int* TINKER_MOD(dlmda, douindorig);
extern char TINKER_MOD(dlmda, elmdamap)[3];
extern char TINKER_MOD(dlmda, plmdamap)[3];
extern char TINKER_MOD(dlmda, vlmdamap)[3];
extern char TINKER_MOD(dlmda, lmdaengymode)[4];
extern char TINKER_MOD(dlmda, lmdasampmode)[4];
extern char TINKER_MOD(dlmda, relstage)[4];
extern char TINKER_MOD(dlmda, abflabel)[40];
extern char TINKER_MOD(dlmda, abftitle)[40];
extern char TINKER_MOD(dlmda, lmdasavefile)[240];
#ifdef __cplusplus
}
#endif
