#
#
#  ############################################################
#  ##                                                        ##
#  ##  compile.make  --  compile each of the TINKER modules  ##
#  ##                 (HP Tru64 Unix Version)                ##
#  ##                                                        ##
#  ############################################################
#
#
f77 -c -fast -arch generic -tune generic active.f
f77 -c -fast -arch generic -tune generic alchemy.f
f77 -c -fast -arch generic -tune generic analysis.f
f77 -c -fast -arch generic -tune generic analyze.f
f77 -c -fast -arch generic -tune generic angles.f
f77 -c -fast -arch generic -tune generic anneal.f
f77 -c -fast -arch generic -tune generic archive.f
f77 -c -fast -arch generic -tune generic attach.f
f77 -c -fast -arch generic -tune generic bar.f
f77 -c -fast -arch generic -tune generic basefile.f
f77 -c -fast -arch generic -tune generic beeman.f
f77 -c -fast -arch generic -tune generic bicubic.f
f77 -c -fast -arch generic -tune generic bitors.f
f77 -c -fast -arch generic -tune generic bonds.f
f77 -c -fast -arch generic -tune generic born.f
f77 -c -fast -arch generic -tune generic bounds.f
f77 -c -fast -arch generic -tune generic bussi.f
f77 -c -fast -arch generic -tune generic calendar.f
f77 -c -fast -arch generic -tune generic center.f
f77 -c -fast -arch generic -tune generic chkpole.f
f77 -c -fast -arch generic -tune generic chkring.f
f77 -c -fast -arch generic -tune generic chkxyz.f
f77 -c -fast -arch generic -tune generic cholesky.f
f77 -c -fast -arch generic -tune generic clock.f
f77 -c -fast -arch generic -tune generic cluster.f
f77 -c -fast -arch generic -tune generic column.f
f77 -c -fast -arch generic -tune generic command.f
f77 -c -fast -arch generic -tune generic connect.f
f77 -c -fast -arch generic -tune generic connolly.f
f77 -c -fast -arch generic -tune generic control.f
f77 -c -fast -arch generic -tune generic correlate.f
f77 -c -fast -arch generic -tune generic crystal.f
f77 -c -fast -arch generic -tune generic cspline.f
f77 -c -fast -arch generic -tune generic cutoffs.f
f77 -c -fast -arch generic -tune generic deflate.f
f77 -c -fast -arch generic -tune generic delete.f
f77 -c -fast -arch generic -tune generic diagq.f
f77 -c -fast -arch generic -tune generic diffeq.f
f77 -c -fast -arch generic -tune generic diffuse.f
f77 -c -fast -arch generic -tune generic distgeom.f
f77 -c -fast -arch generic -tune generic document.f
f77 -c -fast -arch generic -tune generic dynamic.f
f77 -c -fast -arch generic -tune generic eangang.f
f77 -c -fast -arch generic -tune generic eangang1.f
f77 -c -fast -arch generic -tune generic eangang2.f
f77 -c -fast -arch generic -tune generic eangang3.f
f77 -c -fast -arch generic -tune generic eangle.f
f77 -c -fast -arch generic -tune generic eangle1.f
f77 -c -fast -arch generic -tune generic eangle2.f
f77 -c -fast -arch generic -tune generic eangle3.f
f77 -c -fast -arch generic -tune generic ebond.f
f77 -c -fast -arch generic -tune generic ebond1.f
f77 -c -fast -arch generic -tune generic ebond2.f
f77 -c -fast -arch generic -tune generic ebond3.f
f77 -c -fast -arch generic -tune generic ebuck.f
f77 -c -fast -arch generic -tune generic ebuck1.f
f77 -c -fast -arch generic -tune generic ebuck2.f
f77 -c -fast -arch generic -tune generic ebuck3.f
f77 -c -fast -arch generic -tune generic echarge.f
f77 -c -fast -arch generic -tune generic echarge1.f
f77 -c -fast -arch generic -tune generic echarge2.f
f77 -c -fast -arch generic -tune generic echarge3.f
f77 -c -fast -arch generic -tune generic echgdpl.f
f77 -c -fast -arch generic -tune generic echgdpl1.f
f77 -c -fast -arch generic -tune generic echgdpl2.f
f77 -c -fast -arch generic -tune generic echgdpl3.f
f77 -c -fast -arch generic -tune generic edipole.f
f77 -c -fast -arch generic -tune generic edipole1.f
f77 -c -fast -arch generic -tune generic edipole2.f
f77 -c -fast -arch generic -tune generic edipole3.f
f77 -c -fast -arch generic -tune generic egauss.f
f77 -c -fast -arch generic -tune generic egauss1.f
f77 -c -fast -arch generic -tune generic egauss2.f
f77 -c -fast -arch generic -tune generic egauss3.f
f77 -c -fast -arch generic -tune generic egeom.f
f77 -c -fast -arch generic -tune generic egeom1.f
f77 -c -fast -arch generic -tune generic egeom2.f
f77 -c -fast -arch generic -tune generic egeom3.f
f77 -c -fast -arch generic -tune generic ehal.f
f77 -c -fast -arch generic -tune generic ehal1.f
f77 -c -fast -arch generic -tune generic ehal2.f
f77 -c -fast -arch generic -tune generic ehal3.f
f77 -c -fast -arch generic -tune generic eimprop.f
f77 -c -fast -arch generic -tune generic eimprop1.f
f77 -c -fast -arch generic -tune generic eimprop2.f
f77 -c -fast -arch generic -tune generic eimprop3.f
f77 -c -fast -arch generic -tune generic eimptor.f
f77 -c -fast -arch generic -tune generic eimptor1.f
f77 -c -fast -arch generic -tune generic eimptor2.f
f77 -c -fast -arch generic -tune generic eimptor3.f
f77 -c -fast -arch generic -tune generic elj.f
f77 -c -fast -arch generic -tune generic elj1.f
f77 -c -fast -arch generic -tune generic elj2.f
f77 -c -fast -arch generic -tune generic elj3.f
f77 -c -fast -arch generic -tune generic embed.f
f77 -c -fast -arch generic -tune generic emetal.f
f77 -c -fast -arch generic -tune generic emetal1.f
f77 -c -fast -arch generic -tune generic emetal2.f
f77 -c -fast -arch generic -tune generic emetal3.f
f77 -c -fast -arch generic -tune generic emm3hb.f
f77 -c -fast -arch generic -tune generic emm3hb1.f
f77 -c -fast -arch generic -tune generic emm3hb2.f
f77 -c -fast -arch generic -tune generic emm3hb3.f
f77 -c -fast -arch generic -tune generic empole.f
f77 -c -fast -arch generic -tune generic empole1.f
f77 -c -fast -arch generic -tune generic empole2.f
f77 -c -fast -arch generic -tune generic empole3.f
f77 -c -fast -arch generic -tune generic energy.f
f77 -c -fast -arch generic -tune generic eopbend.f
f77 -c -fast -arch generic -tune generic eopbend1.f
f77 -c -fast -arch generic -tune generic eopbend2.f
f77 -c -fast -arch generic -tune generic eopbend3.f
f77 -c -fast -arch generic -tune generic eopdist.f
f77 -c -fast -arch generic -tune generic eopdist1.f
f77 -c -fast -arch generic -tune generic eopdist2.f
f77 -c -fast -arch generic -tune generic eopdist3.f
f77 -c -fast -arch generic -tune generic epitors.f
f77 -c -fast -arch generic -tune generic epitors1.f
f77 -c -fast -arch generic -tune generic epitors2.f
f77 -c -fast -arch generic -tune generic epitors3.f
f77 -c -fast -arch generic -tune generic erf.f
f77 -c -fast -arch generic -tune generic erxnfld.f
f77 -c -fast -arch generic -tune generic erxnfld1.f
f77 -c -fast -arch generic -tune generic erxnfld2.f
f77 -c -fast -arch generic -tune generic erxnfld3.f
f77 -c -fast -arch generic -tune generic esolv.f
f77 -c -fast -arch generic -tune generic esolv1.f
f77 -c -fast -arch generic -tune generic esolv2.f
f77 -c -fast -arch generic -tune generic esolv3.f
f77 -c -fast -arch generic -tune generic estrbnd.f
f77 -c -fast -arch generic -tune generic estrbnd1.f
f77 -c -fast -arch generic -tune generic estrbnd2.f
f77 -c -fast -arch generic -tune generic estrbnd3.f
f77 -c -fast -arch generic -tune generic estrtor.f
f77 -c -fast -arch generic -tune generic estrtor1.f
f77 -c -fast -arch generic -tune generic estrtor2.f
f77 -c -fast -arch generic -tune generic estrtor3.f
f77 -c -fast -arch generic -tune generic etors.f
f77 -c -fast -arch generic -tune generic etors1.f
f77 -c -fast -arch generic -tune generic etors2.f
f77 -c -fast -arch generic -tune generic etors3.f
f77 -c -fast -arch generic -tune generic etortor.f
f77 -c -fast -arch generic -tune generic etortor1.f
f77 -c -fast -arch generic -tune generic etortor2.f
f77 -c -fast -arch generic -tune generic etortor3.f
f77 -c -fast -arch generic -tune generic eurey.f
f77 -c -fast -arch generic -tune generic eurey1.f
f77 -c -fast -arch generic -tune generic eurey2.f
f77 -c -fast -arch generic -tune generic eurey3.f
f77 -c -fast -arch generic -tune generic evcorr.f
f77 -c -fast -arch generic -tune generic extra.f
f77 -c -fast -arch generic -tune generic extra1.f
f77 -c -fast -arch generic -tune generic extra2.f
f77 -c -fast -arch generic -tune generic extra3.f
f77 -c -fast -arch generic -tune generic fatal.f
f77 -c -fast -arch generic -tune generic fft3d.f
f77 -c -fast -arch generic -tune generic fftpack.f
f77 -c -fast -arch generic -tune generic field.f
f77 -c -fast -arch generic -tune generic final.f
f77 -c -fast -arch generic -tune generic flatten.f
f77 -c -fast -arch generic -tune generic freeunit.f
f77 -c -fast -arch generic -tune generic gda.f
f77 -c -fast -arch generic -tune generic geometry.f
f77 -c -fast -arch generic -tune generic getint.f
f77 -c -fast -arch generic -tune generic getkey.f
f77 -c -fast -arch generic -tune generic getmol.f
f77 -c -fast -arch generic -tune generic getmol2.f
f77 -c -fast -arch generic -tune generic getnumb.f
f77 -c -fast -arch generic -tune generic getpdb.f
f77 -c -fast -arch generic -tune generic getprm.f
f77 -c -fast -arch generic -tune generic getref.f
f77 -c -fast -arch generic -tune generic getstring.f
f77 -c -fast -arch generic -tune generic gettext.f
f77 -c -fast -arch generic -tune generic getword.f
f77 -c -fast -arch generic -tune generic getxyz.f
f77 -c -fast -arch generic -tune generic ghmcstep.f
f77 -c -fast -arch generic -tune generic gradient.f
f77 -c -fast -arch generic -tune generic gradrgd.f
f77 -c -fast -arch generic -tune generic gradrot.f
f77 -c -fast -arch generic -tune generic groups.f
f77 -c -fast -arch generic -tune generic grpline.f
f77 -c -fast -arch generic -tune generic gyrate.f
f77 -c -fast -arch generic -tune generic hessian.f
f77 -c -fast -arch generic -tune generic hessrgd.f
f77 -c -fast -arch generic -tune generic hessrot.f
f77 -c -fast -arch generic -tune generic hybrid.f
f77 -c -fast -arch generic -tune generic image.f
f77 -c -fast -arch generic -tune generic impose.f
f77 -c -fast -arch generic -tune generic induce.f
f77 -c -fast -arch generic -tune generic inertia.f
f77 -c -fast -arch generic -tune generic initatom.f
f77 -c -fast -arch generic -tune generic initial.f
f77 -c -fast -arch generic -tune generic initprm.f
f77 -c -fast -arch generic -tune generic initres.f
f77 -c -fast -arch generic -tune generic initrot.f
f77 -c -fast -arch generic -tune generic insert.f
f77 -c -fast -arch generic -tune generic intedit.f
f77 -c -fast -arch generic -tune generic intxyz.f
f77 -c -fast -arch generic -tune generic invbeta.f
f77 -c -fast -arch generic -tune generic invert.f
f77 -c -fast -arch generic -tune generic jacobi.f
f77 -c -fast -arch generic -tune generic kangang.f
f77 -c -fast -arch generic -tune generic kangle.f
f77 -c -fast -arch generic -tune generic katom.f
f77 -c -fast -arch generic -tune generic kbond.f
f77 -c -fast -arch generic -tune generic kcharge.f
f77 -c -fast -arch generic -tune generic kdipole.f
f77 -c -fast -arch generic -tune generic kewald.f
f77 -c -fast -arch generic -tune generic kextra.f
f77 -c -fast -arch generic -tune generic kgeom.f
f77 -c -fast -arch generic -tune generic kimprop.f
f77 -c -fast -arch generic -tune generic kimptor.f
f77 -c -fast -arch generic -tune generic kinetic.f
f77 -c -fast -arch generic -tune generic kmetal.f
f77 -c -fast -arch generic -tune generic kmpole.f
f77 -c -fast -arch generic -tune generic kopbend.f
f77 -c -fast -arch generic -tune generic kopdist.f
f77 -c -fast -arch generic -tune generic korbit.f
f77 -c -fast -arch generic -tune generic kpitors.f
f77 -c -fast -arch generic -tune generic kpolar.f
f77 -c -fast -arch generic -tune generic ksolv.f
f77 -c -fast -arch generic -tune generic kstrbnd.f
f77 -c -fast -arch generic -tune generic kstrtor.f
f77 -c -fast -arch generic -tune generic ktors.f
f77 -c -fast -arch generic -tune generic ktortor.f
f77 -c -fast -arch generic -tune generic kurey.f
f77 -c -fast -arch generic -tune generic kvdw.f
f77 -c -fast -arch generic -tune generic lattice.f
f77 -c -fast -arch generic -tune generic lbfgs.f
f77 -c -fast -arch generic -tune generic lights.f
f77 -c -fast -arch generic -tune generic makeint.f
f77 -c -fast -arch generic -tune generic makeref.f
f77 -c -fast -arch generic -tune generic makexyz.f
f77 -c -fast -arch generic -tune generic maxwell.f
f77 -c -fast -arch generic -tune generic mdinit.f
f77 -c -fast -arch generic -tune generic mdrest.f
f77 -c -fast -arch generic -tune generic mdsave.f
f77 -c -fast -arch generic -tune generic mdstat.f
f77 -c -fast -arch generic -tune generic mechanic.f
f77 -c -fast -arch generic -tune generic merge.f
f77 -c -fast -arch generic -tune generic minimize.f
f77 -c -fast -arch generic -tune generic minirot.f
f77 -c -fast -arch generic -tune generic minrigid.f
f77 -c -fast -arch generic -tune generic molecule.f
f77 -c -fast -arch generic -tune generic molxyz.f
f77 -c -fast -arch generic -tune generic moments.f
f77 -c -fast -arch generic -tune generic monte.f
f77 -c -fast -arch generic -tune generic mutate.f
f77 -c -fast -arch generic -tune generic nblist.f
f77 -c -fast -arch generic -tune generic newton.f
f77 -c -fast -arch generic -tune generic newtrot.f
f77 -c -fast -arch generic -tune generic nextarg.f
f77 -c -fast -arch generic -tune generic nexttext.f
f77 -c -fast -arch generic -tune generic nose.f
f77 -c -fast -arch generic -tune generic nspline.f
f77 -c -fast -arch generic -tune generic nucleic.f
f77 -c -fast -arch generic -tune generic number.f
f77 -c -fast -arch generic -tune generic numeral.f
f77 -c -fast -arch generic -tune generic numgrad.f
f77 -c -fast -arch generic -tune generic ocvm.f
f77 -c -fast -arch generic -tune generic openend.f
f77 -c -fast -arch generic -tune generic optimize.f
f77 -c -fast -arch generic -tune generic optirot.f
f77 -c -fast -arch generic -tune generic optrigid.f
f77 -c -fast -arch generic -tune generic optsave.f
f77 -c -fast -arch generic -tune generic orbital.f
f77 -c -fast -arch generic -tune generic orient.f
f77 -c -fast -arch generic -tune generic orthog.f
f77 -c -fast -arch generic -tune generic overlap.f
f77 -c -fast -arch generic -tune generic path.f
f77 -c -fast -arch generic -tune generic pdbxyz.f
f77 -c -fast -arch generic -tune generic picalc.f
f77 -c -fast -arch generic -tune generic pmestuff.f
f77 -c -fast -arch generic -tune generic pmpb.f
f77 -c -fast -arch generic -tune generic polarize.f
f77 -c -fast -arch generic -tune generic poledit.f
f77 -c -fast -arch generic -tune generic potential.f
f77 -c -fast -arch generic -tune generic polymer.f
f77 -c -fast -arch generic -tune generic precise.f
f77 -c -fast -arch generic -tune generic pressure.f
f77 -c -fast -arch generic -tune generic prmedit.f
f77 -c -fast -arch generic -tune generic prmkey.f
f77 -c -fast -arch generic -tune generic promo.f
f77 -c -fast -arch generic -tune generic protein.f
f77 -c -fast -arch generic -tune generic prtdyn.f
f77 -c -fast -arch generic -tune generic prterr.f
f77 -c -fast -arch generic -tune generic prtint.f
f77 -c -fast -arch generic -tune generic prtmol2.f
f77 -c -fast -arch generic -tune generic prtpdb.f
f77 -c -fast -arch generic -tune generic prtprm.f
f77 -c -fast -arch generic -tune generic prtseq.f
f77 -c -fast -arch generic -tune generic prtxyz.f
f77 -c -fast -arch generic -tune generic pss.f
f77 -c -fast -arch generic -tune generic pssrigid.f
f77 -c -fast -arch generic -tune generic pssrot.f
f77 -c -fast -arch generic -tune generic quatfit.f
f77 -c -fast -arch generic -tune generic radial.f
f77 -c -fast -arch generic -tune generic random.f
f77 -c -fast -arch generic -tune generic rattle.f
f77 -c -fast -arch generic -tune generic readdyn.f
f77 -c -fast -arch generic -tune generic readgau.f
f77 -c -fast -arch generic -tune generic readint.f
f77 -c -fast -arch generic -tune generic readmol.f
f77 -c -fast -arch generic -tune generic readmol2.f
f77 -c -fast -arch generic -tune generic readpdb.f
f77 -c -fast -arch generic -tune generic readprm.f
f77 -c -fast -arch generic -tune generic readseq.f
f77 -c -fast -arch generic -tune generic readxyz.f
f77 -c -fast -arch generic -tune generic replica.f
f77 -c -fast -arch generic -tune generic respa.f
f77 -c -fast -arch generic -tune generic rgdstep.f
f77 -c -fast -arch generic -tune generic rings.f
f77 -c -fast -arch generic -tune generic rmsfit.f
f77 -c -fast -arch generic -tune generic rotlist.f
f77 -c -fast -arch generic -tune generic rotpole.f
f77 -c -fast -arch generic -tune generic saddle.f
f77 -c -fast -arch generic -tune generic scan.f
f77 -c -fast -arch generic -tune generic sdstep.f
f77 -c -fast -arch generic -tune generic search.f
f77 -c -fast -arch generic -tune generic server.f
f77 -c -fast -arch generic -tune generic shakeup.f
f77 -c -fast -arch generic -tune generic sigmoid.f
f77 -c -fast -arch generic -tune generic sktstuff.f
f77 -c -fast -arch generic -tune generic sniffer.f
f77 -c -fast -arch generic -tune generic sort.f
f77 -c -fast -arch generic -tune generic spacefill.f
f77 -c -fast -arch generic -tune generic spectrum.f
f77 -c -fast -arch generic -tune generic square.f
f77 -c -fast -arch generic -tune generic suffix.f
f77 -c -fast -arch generic -tune generic superpose.f
f77 -c -fast -arch generic -tune generic surface.f
f77 -c -fast -arch generic -tune generic surfatom.f
f77 -c -fast -arch generic -tune generic switch.f
f77 -c -fast -arch generic -tune generic sybylxyz.f
f77 -c -fast -arch generic -tune generic temper.f
f77 -c -fast -arch generic -tune generic testgrad.f
f77 -c -fast -arch generic -tune generic testhess.f
f77 -c -fast -arch generic -tune generic testpair.f
f77 -c -fast -arch generic -tune generic testpol.f
f77 -c -fast -arch generic -tune generic testrot.f
f77 -c -fast -arch generic -tune generic timer.f
f77 -c -fast -arch generic -tune generic timerot.f
f77 -c -fast -arch generic -tune generic tncg.f
f77 -c -fast -arch generic -tune generic torphase.f
f77 -c -fast -arch generic -tune generic torque.f
f77 -c -fast -arch generic -tune generic torsfit.f
f77 -c -fast -arch generic -tune generic torsions.f
f77 -c -fast -arch generic -tune generic trimtext.f
f77 -c -fast -arch generic -tune generic unitcell.f
f77 -c -fast -arch generic -tune generic valence.f
f77 -c -fast -arch generic -tune generic verlet.f
f77 -c -fast -arch generic -tune generic version.f
f77 -c -fast -arch generic -tune generic vibbig.f
f77 -c -fast -arch generic -tune generic vibrate.f
f77 -c -fast -arch generic -tune generic vibrot.f
f77 -c -fast -arch generic -tune generic volume.f
f77 -c -fast -arch generic -tune generic xtalfit.f
f77 -c -fast -arch generic -tune generic xtalmin.f
f77 -c -fast -arch generic -tune generic xyzatm.f
f77 -c -fast -arch generic -tune generic xyzedit.f
f77 -c -fast -arch generic -tune generic xyzint.f
f77 -c -fast -arch generic -tune generic xyzpdb.f
f77 -c -fast -arch generic -tune generic xyzsybyl.f
f77 -c -fast -arch generic -tune generic zatom.f
