#
#
#  ############################################################
#  ##                                                        ##
#  ##  compile.make  --  compile each of the TINKER modules  ##
#  ##                 (Linux/GNU gcc Version)                ##
#  ##                                                        ##
#  ############################################################
#
#
gcc  -c -O2  active.c
gcc  -c -O2  alchemy.c
gcc  -c -O2  analysis.c
gcc  -c -O2  analyze.c
gcc  -c -O2  angles.c
gcc  -c -O2  anneal.c
gcc  -c -O2  archive.c
gcc  -c -O2  attach.c
gcc  -c -O2  basefile.c
gcc  -c -O2  beeman.c
gcc  -c -O2  bicubic.c
gcc  -c -O2  bitors.c
gcc  -c -O2  bonds.c
gcc  -c -O2  born.c
gcc  -c -O2  bounds.c
gcc  -c -O2  bspline.c
gcc  -c -O2  calendar.c
gcc  -c -O2  center.c
gcc  -c -O2  chkpole.c
gcc  -c -O2  chkring.c
gcc  -c -O2  chkxyz.c
gcc  -c -O2  cholesky.c
gcc  -c -O2  cluster.c
gcc  -c -O2  column.c
gcc  -c -O2  command.c
gcc  -c -O2  connect.c
gcc  -c -O2  connolly.c
gcc  -c -O2  control.c
gcc  -c -O2  correlate.c
gcc  -c -O2  crystal.c
gcc  -c -O2  cspline.c
gcc  -c -O2  cutoffs.c
gcc  -c -O2  deflate.c
gcc  -c -O2  delete.c
gcc  -c -O2  diagq.c
gcc  -c -O2  diffeq.c
gcc  -c -O2  diffuse.c
gcc  -c -O2  distgeom.c
gcc  -c -O2  document.c
gcc  -c -O2  dynamic.c
gcc  -c -O2  eangang.c
gcc  -c -O2  eangang1.c
gcc  -c -O2  eangang2.c
gcc  -c -O2  eangang3.c
gcc  -c -O2  eangle.c
gcc  -c -O2  eangle1.c
gcc  -c -O2  eangle2.c
gcc  -c -O2  eangle3.c
gcc  -c -O2  ebond.c
gcc  -c -O2  ebond1.c
gcc  -c -O2  ebond2.c
gcc  -c -O2  ebond3.c
gcc  -c -O2  ebuck.c
gcc  -c -O2  ebuck1.c
gcc  -c -O2  ebuck2.c
gcc  -c -O2  ebuck3.c
gcc  -c -O2  echarge.c
gcc  -c -O2  echarge1.c
gcc  -c -O2  echarge2.c
gcc  -c -O2  echarge3.c
gcc  -c -O2  echgdpl.c
gcc  -c -O2  echgdpl1.c
gcc  -c -O2  echgdpl2.c
gcc  -c -O2  echgdpl3.c
gcc  -c -O2  edipole.c
gcc  -c -O2  edipole1.c
gcc  -c -O2  edipole2.c
gcc  -c -O2  edipole3.c
gcc  -c -O2  egauss.c
gcc  -c -O2  egauss1.c
gcc  -c -O2  egauss2.c
gcc  -c -O2  egauss3.c
gcc  -c -O2  egeom.c
gcc  -c -O2  egeom1.c
gcc  -c -O2  egeom2.c
gcc  -c -O2  egeom3.c
gcc  -c -O2  ehal.c
gcc  -c -O2  ehal1.c
gcc  -c -O2  ehal2.c
gcc  -c -O2  ehal3.c
gcc  -c -O2  eimprop.c
gcc  -c -O2  eimprop1.c
gcc  -c -O2  eimprop2.c
gcc  -c -O2  eimprop3.c
gcc  -c -O2  eimptor.c
gcc  -c -O2  eimptor1.c
gcc  -c -O2  eimptor2.c
gcc  -c -O2  eimptor3.c
gcc  -c -O2  elj.c
gcc  -c -O2  elj1.c
gcc  -c -O2  elj2.c
gcc  -c -O2  elj3.c
gcc  -c -O2  embed.c
gcc  -c -O2  emetal.c
gcc  -c -O2  emetal1.c
gcc  -c -O2  emetal2.c
gcc  -c -O2  emetal3.c
gcc  -c -O2  emm3hb.c
gcc  -c -O2  emm3hb1.c
gcc  -c -O2  emm3hb2.c
gcc  -c -O2  emm3hb3.c
gcc  -c -O2  empole.c
gcc  -c -O2  empole1.c
gcc  -c -O2  empole2.c
gcc  -c -O2  empole3.c
gcc  -c -O2  energy.c
gcc  -c -O2  eopbend.c
gcc  -c -O2  eopbend1.c
gcc  -c -O2  eopbend2.c
gcc  -c -O2  eopbend3.c
gcc  -c -O2  eopdist.c
gcc  -c -O2  eopdist1.c
gcc  -c -O2  eopdist2.c
gcc  -c -O2  eopdist3.c
gcc  -c -O2  epitors.c
gcc  -c -O2  epitors1.c
gcc  -c -O2  epitors2.c
gcc  -c -O2  epitors3.c
gcc  -c -O2  erf.c
gcc  -c -O2  erxnfld.c
gcc  -c -O2  erxnfld1.c
gcc  -c -O2  erxnfld2.c
gcc  -c -O2  erxnfld3.c
gcc  -c -O2  esolv.c
gcc  -c -O2  esolv1.c
gcc  -c -O2  esolv2.c
gcc  -c -O2  esolv3.c
gcc  -c -O2  estrbnd.c
gcc  -c -O2  estrbnd1.c
gcc  -c -O2  estrbnd2.c
gcc  -c -O2  estrbnd3.c
gcc  -c -O2  estrtor.c
gcc  -c -O2  estrtor1.c
gcc  -c -O2  estrtor2.c
gcc  -c -O2  estrtor3.c
gcc  -c -O2  etors.c
gcc  -c -O2  etors1.c
gcc  -c -O2  etors2.c
gcc  -c -O2  etors3.c
gcc  -c -O2  etortor.c
gcc  -c -O2  etortor1.c
gcc  -c -O2  etortor2.c
gcc  -c -O2  etortor3.c
gcc  -c -O2  eurey.c
gcc  -c -O2  eurey1.c
gcc  -c -O2  eurey2.c
gcc  -c -O2  eurey3.c
gcc  -c -O2  extra.c
gcc  -c -O2  extra1.c
gcc  -c -O2  extra2.c
gcc  -c -O2  extra3.c
gcc  -c -O2  fatal.c
gcc  -c -O2  fft3d.c
gcc  -c -O2  fftpack.c
gcc  -c -O2  field.c
gcc  -c -O2  final.c
gcc  -c -O2  flatten.c
gcc  -c -O2  freeunit.c
gcc  -c -O2  gda.c
gcc  -c -O2  geometry.c
gcc  -c -O2  getime.c
gcc  -c -O2  getint.c
gcc  -c -O2  getkey.c
gcc  -c -O2  getmol2.c
gcc  -c -O2  getnumb.c
gcc  -c -O2  getpdb.c
gcc  -c -O2  getprm.c
gcc  -c -O2  getref.c
gcc  -c -O2  getstring.c
gcc  -c -O2  gettext.c
gcc  -c -O2  getword.c
gcc  -c -O2  getxyz.c
gcc  -c -O2  gradient.c
gcc  -c -O2  gradrgd.c
gcc  -c -O2  gradrot.c
gcc  -c -O2  groups.c
gcc  -c -O2  grpline.c
gcc  -c -O2  gyrate.c
gcc  -c -O2  hessian.c
gcc  -c -O2  hessrgd.c
gcc  -c -O2  hessrot.c
gcc  -c -O2  hybrid.c
gcc  -c -O2  image.c
gcc  -c -O2  impose.c
gcc  -c -O2  induce.c
gcc  -c -O2  inertia.c
gcc  -c -O2  initial.c
gcc  -c -O2  initprm.c
gcc  -c -O2  initres.c
gcc  -c -O2  initrot.c
gcc  -c -O2  insert.c
gcc  -c -O2  intedit.c
gcc  -c -O2  intxyz.c
gcc  -c -O2  invbeta.c
gcc  -c -O2  invert.c
gcc  -c -O2  jacobi.c
gcc  -c -O2  kangang.c
gcc  -c -O2  kangle.c
gcc  -c -O2  katom.c
gcc  -c -O2  kbond.c
gcc  -c -O2  kcharge.c
gcc  -c -O2  kdipole.c
gcc  -c -O2  kewald.c
gcc  -c -O2  kgeom.c
gcc  -c -O2  kimprop.c
gcc  -c -O2  kimptor.c
gcc  -c -O2  kinetic.c
gcc  -c -O2  kmetal.c
gcc  -c -O2  kmpole.c
gcc  -c -O2  kopbend.c
gcc  -c -O2  kopdist.c
gcc  -c -O2  korbit.c
gcc  -c -O2  kpitors.c
gcc  -c -O2  kpolar.c
gcc  -c -O2  ksolv.c
gcc  -c -O2  kstrbnd.c
gcc  -c -O2  kstrtor.c
gcc  -c -O2  ktors.c
gcc  -c -O2  ktortor.c
gcc  -c -O2  kurey.c
gcc  -c -O2  kvdw.c
gcc  -c -O2  lattice.c
gcc  -c -O2  lbfgs.c
gcc  -c -O2  lights.c
gcc  -c -O2  makeint.c
gcc  -c -O2  makepdb.c
gcc  -c -O2  makeref.c
gcc  -c -O2  makexyz.c
gcc  -c -O2  maxwell.c
gcc  -c -O2  mdinit.c
gcc  -c -O2  mdrest.c
gcc  -c -O2  mdsave.c
gcc  -c -O2  mdstat.c
gcc  -c -O2  mechanic.c
gcc  -c -O2  merge.c
gcc  -c -O2  minimize.c
gcc  -c -O2  minirot.c
gcc  -c -O2  minrigid.c
gcc  -c -O2  molecule.c
gcc  -c -O2  moments.c
gcc  -c -O2  monte.c
gcc  -c -O2  mutate.c
gcc  -c -O2  nblist.c
gcc  -c -O2  newton.c
gcc  -c -O2  newtrot.c
gcc  -c -O2  nextarg.c
gcc  -c -O2  nexttext.c
gcc  -c -O2  nspline.c
gcc  -c -O2  nucleic.c
gcc  -c -O2  number.c
gcc  -c -O2  numeral.c
gcc  -c -O2  numgrad.c
gcc  -c -O2  ocvm.c
gcc  -c -O2  openend.c
gcc  -c -O2  optimize.c
gcc  -c -O2  optirot.c
gcc  -c -O2  optrigid.c
gcc  -c -O2  optsave.c
gcc  -c -O2  orbital.c
gcc  -c -O2  orient.c
gcc  -c -O2  orthog.c
gcc  -c -O2  overlap.c
gcc  -c -O2  path.c
gcc  -c -O2  pdbxyz.c
gcc  -c -O2  piscf.c
gcc  -c -O2  pmepol.c
gcc  -c -O2  pmpb.c
gcc  -c -O2  polarize.c
gcc  -c -O2  poledit.c
gcc  -c -O2  polymer.c
gcc  -c -O2  potential.c
gcc  -c -O2  precise.c
gcc  -c -O2  pressure.c
gcc  -c -O2  prmedit.c
gcc  -c -O2  prmkey.c
gcc  -c -O2  promo.c
gcc  -c -O2  protein.c
gcc  -c -O2  prtdyn.c
gcc  -c -O2  prterr.c
gcc  -c -O2  prtint.c
gcc  -c -O2  prtmol2.c
gcc  -c -O2  prtpdb.c
gcc  -c -O2  prtprm.c
gcc  -c -O2  prtseq.c
gcc  -c -O2  prtxyz.c
gcc  -c -O2  pss.c
gcc  -c -O2  pssrigid.c
gcc  -c -O2  pssrot.c
gcc  -c -O2  quatfit.c
gcc  -c -O2  radial.c
gcc  -c -O2  random.c
gcc  -c -O2  rattle.c
gcc  -c -O2  readdyn.c
gcc  -c -O2  readgau.c
gcc  -c -O2  readint.c
gcc  -c -O2  readmol2.c
gcc  -c -O2  readpdb.c
gcc  -c -O2  readprm.c
gcc  -c -O2  readseq.c
gcc  -c -O2  readxyz.c
gcc  -c -O2  replica.c
gcc  -c -O2  rgdstep.c
gcc  -c -O2  rings.c
gcc  -c -O2  rmsfit.c
gcc  -c -O2  rotlist.c
gcc  -c -O2  rotpole.c
gcc  -c -O2  saddle.c
gcc  -c -O2  scan.c
gcc  -c -O2  sdstep.c
gcc  -c -O2  search.c
gcc  -c -O2  server.c
gcc  -c -O2  setime.c
gcc  -c -O2  shakeup.c
gcc  -c -O2  sigmoid.c
gcc  -c -O2  sktstuff.c
gcc  -c -O2  sniffer.c
gcc  -c -O2  sort.c
gcc  -c -O2  spacefill.c
gcc  -c -O2  spectrum.c
gcc  -c -O2  square.c
gcc  -c -O2  suffix.c
gcc  -c -O2  superpose.c
gcc  -c -O2  surface.c
gcc  -c -O2  surfatom.c
gcc  -c -O2  switch.c
gcc  -c -O2  sybylxyz.c
gcc  -c -O2  temper.c
gcc  -c -O2  testgrad.c
gcc  -c -O2  testhess.c
gcc  -c -O2  testpair.c
gcc  -c -O2  testrot.c
gcc  -c -O2  timer.c
gcc  -c -O2  timerot.c
gcc  -c -O2  tncg.c
gcc  -c -O2  torphase.c
gcc  -c -O2  torque.c
gcc  -c -O2  torsions.c
gcc  -c -O2  trimtext.c
gcc  -c -O2  unitcell.c
gcc  -c -O2  valence.c
gcc  -c -O2  verlet.c
gcc  -c -O2  version.c
gcc  -c -O2  vibbig.c
gcc  -c -O2  vibrate.c
gcc  -c -O2  vibrot.c
gcc  -c -O2  volume.c
gcc  -c -O2  xtalfit.c
gcc  -c -O2  xtalmin.c
gcc  -c -O2  xyzatm.c
gcc  -c -O2  xyzedit.c
gcc  -c -O2  xyzint.c
gcc  -c -O2  xyzpdb.c
gcc  -c -O2  xyzsybyl.c
gcc  -c -O2  zatom.c
