#
#
#  ############################################################
#  ##                                                        ##
#  ##  compile.make  --  compile each of the TINKER modules  ##
#  ##             (PGI pgf95 for Mac OSX Version)            ##
#  ##                                                        ##
#  ############################################################
#
#
pgf95 -c -fast -mp active.f
pgf95 -c -fast -mp alchemy.f
pgf95 -c -fast -mp analysis.f
pgf95 -c -fast -mp analyze.f
pgf95 -c -fast -mp angles.f
pgf95 -c -fast -mp anneal.f
pgf95 -c -fast -mp archive.f
pgf95 -c -fast -mp attach.f
pgf95 -c -fast -mp bar.f
pgf95 -c -fast -mp basefile.f
pgf95 -c -fast -mp beeman.f
pgf95 -c -fast -mp bicubic.f
pgf95 -c -fast -mp bitors.f
pgf95 -c -fast -mp bonds.f
pgf95 -c -fast -mp born.f
pgf95 -c -fast -mp bounds.f
pgf95 -c -fast -mp bussi.f
pgf95 -c -fast -mp calendar.f
pgf95 -c -fast -mp center.f
pgf95 -c -fast -mp chkpole.f
pgf95 -c -fast -mp chkring.f
pgf95 -c -fast -mp chkxyz.f
pgf95 -c -fast -mp cholesky.f
pgf95 -c -fast -mp clock.f
pgf95 -c -fast -mp cluster.f
pgf95 -c -fast -mp column.f
pgf95 -c -fast -mp command.f
pgf95 -c -fast -mp connect.f
pgf95 -c -fast -mp connolly.f
pgf95 -c -fast -mp control.f
pgf95 -c -fast -mp correlate.f
pgf95 -c -fast -mp crystal.f
pgf95 -c -fast -mp cspline.f
pgf95 -c -fast -mp cutoffs.f
pgf95 -c -fast -mp deflate.f
pgf95 -c -fast -mp delete.f
pgf95 -c -fast -mp diagq.f
pgf95 -c -fast -mp diffeq.f
pgf95 -c -fast -mp diffuse.f
pgf95 -c -fast -mp distgeom.f
pgf95 -c -fast -mp document.f
pgf95 -c -fast -mp dynamic.f
pgf95 -c -fast -mp eangang.f
pgf95 -c -fast -mp eangang1.f
pgf95 -c -fast -mp eangang2.f
pgf95 -c -fast -mp eangang3.f
pgf95 -c -fast -mp eangle.f
pgf95 -c -fast -mp eangle1.f
pgf95 -c -fast -mp eangle2.f
pgf95 -c -fast -mp eangle3.f
pgf95 -c -fast -mp ebond.f
pgf95 -c -fast -mp ebond1.f
pgf95 -c -fast -mp ebond2.f
pgf95 -c -fast -mp ebond3.f
pgf95 -c -fast -mp ebuck.f
pgf95 -c -fast -mp ebuck1.f
pgf95 -c -fast -mp ebuck2.f
pgf95 -c -fast -mp ebuck3.f
pgf95 -c -fast -mp echarge.f
pgf95 -c -fast -mp echarge1.f
pgf95 -c -fast -mp echarge2.f
pgf95 -c -fast -mp echarge3.f
pgf95 -c -fast -mp echgdpl.f
pgf95 -c -fast -mp echgdpl1.f
pgf95 -c -fast -mp echgdpl2.f
pgf95 -c -fast -mp echgdpl3.f
pgf95 -c -fast -mp edipole.f
pgf95 -c -fast -mp edipole1.f
pgf95 -c -fast -mp edipole2.f
pgf95 -c -fast -mp edipole3.f
pgf95 -c -fast -mp egauss.f
pgf95 -c -fast -mp egauss1.f
pgf95 -c -fast -mp egauss2.f
pgf95 -c -fast -mp egauss3.f
pgf95 -c -fast -mp egeom.f
pgf95 -c -fast -mp egeom1.f
pgf95 -c -fast -mp egeom2.f
pgf95 -c -fast -mp egeom3.f
pgf95 -c -fast -mp ehal.f
pgf95 -c -fast -mp ehal1.f
pgf95 -c -fast -mp ehal2.f
pgf95 -c -fast -mp ehal3.f
pgf95 -c -fast -mp eimprop.f
pgf95 -c -fast -mp eimprop1.f
pgf95 -c -fast -mp eimprop2.f
pgf95 -c -fast -mp eimprop3.f
pgf95 -c -fast -mp eimptor.f
pgf95 -c -fast -mp eimptor1.f
pgf95 -c -fast -mp eimptor2.f
pgf95 -c -fast -mp eimptor3.f
pgf95 -c -fast -mp elj.f
pgf95 -c -fast -mp elj1.f
pgf95 -c -fast -mp elj2.f
pgf95 -c -fast -mp elj3.f
pgf95 -c -fast -mp embed.f
pgf95 -c -fast -mp emetal.f
pgf95 -c -fast -mp emetal1.f
pgf95 -c -fast -mp emetal2.f
pgf95 -c -fast -mp emetal3.f
pgf95 -c -fast -mp emm3hb.f
pgf95 -c -fast -mp emm3hb1.f
pgf95 -c -fast -mp emm3hb2.f
pgf95 -c -fast -mp emm3hb3.f
pgf95 -c -fast -mp empole.f
pgf95 -c -fast -mp empole1.f
pgf95 -c -fast -mp empole2.f
pgf95 -c -fast -mp empole3.f
pgf95 -c -fast -mp energy.f
pgf95 -c -fast -mp eopbend.f
pgf95 -c -fast -mp eopbend1.f
pgf95 -c -fast -mp eopbend2.f
pgf95 -c -fast -mp eopbend3.f
pgf95 -c -fast -mp eopdist.f
pgf95 -c -fast -mp eopdist1.f
pgf95 -c -fast -mp eopdist2.f
pgf95 -c -fast -mp eopdist3.f
pgf95 -c -fast -mp epitors.f
pgf95 -c -fast -mp epitors1.f
pgf95 -c -fast -mp epitors2.f
pgf95 -c -fast -mp epitors3.f
pgf95 -c -fast -mp erf.f
pgf95 -c -fast -mp erxnfld.f
pgf95 -c -fast -mp erxnfld1.f
pgf95 -c -fast -mp erxnfld2.f
pgf95 -c -fast -mp erxnfld3.f
pgf95 -c -fast -mp esolv.f
pgf95 -c -fast -mp esolv1.f
pgf95 -c -fast -mp esolv2.f
pgf95 -c -fast -mp esolv3.f
pgf95 -c -fast -mp estrbnd.f
pgf95 -c -fast -mp estrbnd1.f
pgf95 -c -fast -mp estrbnd2.f
pgf95 -c -fast -mp estrbnd3.f
pgf95 -c -fast -mp estrtor.f
pgf95 -c -fast -mp estrtor1.f
pgf95 -c -fast -mp estrtor2.f
pgf95 -c -fast -mp estrtor3.f
pgf95 -c -fast -mp etors.f
pgf95 -c -fast -mp etors1.f
pgf95 -c -fast -mp etors2.f
pgf95 -c -fast -mp etors3.f
pgf95 -c -fast -mp etortor.f
pgf95 -c -fast -mp etortor1.f
pgf95 -c -fast -mp etortor2.f
pgf95 -c -fast -mp etortor3.f
pgf95 -c -fast -mp eurey.f
pgf95 -c -fast -mp eurey1.f
pgf95 -c -fast -mp eurey2.f
pgf95 -c -fast -mp eurey3.f
pgf95 -c -fast -mp evcorr.f
pgf95 -c -fast -mp extra.f
pgf95 -c -fast -mp extra1.f
pgf95 -c -fast -mp extra2.f
pgf95 -c -fast -mp extra3.f
pgf95 -c -fast -mp fatal.f
pgf95 -c -fast -mp fft3d.f
pgf95 -c -fast -mp fftpack.f
pgf95 -c -fast -mp field.f
pgf95 -c -fast -mp final.f
pgf95 -c -fast -mp flatten.f
pgf95 -c -fast -mp freeunit.f
pgf95 -c -fast -mp gda.f
pgf95 -c -fast -mp geometry.f
pgf95 -c -fast -mp getint.f
pgf95 -c -fast -mp getkey.f
pgf95 -c -fast -mp getmol.f
pgf95 -c -fast -mp getmol2.f
pgf95 -c -fast -mp getnumb.f
pgf95 -c -fast -mp getpdb.f
pgf95 -c -fast -mp getprm.f
pgf95 -c -fast -mp getref.f
pgf95 -c -fast -mp getstring.f
pgf95 -c -fast -mp gettext.f
pgf95 -c -fast -mp getword.f
pgf95 -c -fast -mp getxyz.f
pgf95 -c -fast -mp ghmcstep.f
pgf95 -c -fast -mp gradient.f
pgf95 -c -fast -mp gradrgd.f
pgf95 -c -fast -mp gradrot.f
pgf95 -c -fast -mp groups.f
pgf95 -c -fast -mp grpline.f
pgf95 -c -fast -mp gyrate.f
pgf95 -c -fast -mp hessian.f
pgf95 -c -fast -mp hessrgd.f
pgf95 -c -fast -mp hessrot.f
pgf95 -c -fast -mp hybrid.f
pgf95 -c -fast -mp image.f
pgf95 -c -fast -mp impose.f
pgf95 -c -fast -mp induce.f
pgf95 -c -fast -mp inertia.f
pgf95 -c -fast -mp initatom.f
pgf95 -c -fast -mp initial.f
pgf95 -c -fast -mp initprm.f
pgf95 -c -fast -mp initres.f
pgf95 -c -fast -mp initrot.f
pgf95 -c -fast -mp insert.f
pgf95 -c -fast -mp intedit.f
pgf95 -c -fast -mp intxyz.f
pgf95 -c -fast -mp invbeta.f
pgf95 -c -fast -mp invert.f
pgf95 -c -fast -mp jacobi.f
pgf95 -c -fast -mp kangang.f
pgf95 -c -fast -mp kangle.f
pgf95 -c -fast -mp katom.f
pgf95 -c -fast -mp kbond.f
pgf95 -c -fast -mp kcharge.f
pgf95 -c -fast -mp kdipole.f
pgf95 -c -fast -mp kewald.f
pgf95 -c -fast -mp kextra.f
pgf95 -c -fast -mp kgeom.f
pgf95 -c -fast -mp kimprop.f
pgf95 -c -fast -mp kimptor.f
pgf95 -c -fast -mp kinetic.f
pgf95 -c -fast -mp kmetal.f
pgf95 -c -fast -mp kmpole.f
pgf95 -c -fast -mp kopbend.f
pgf95 -c -fast -mp kopdist.f
pgf95 -c -fast -mp korbit.f
pgf95 -c -fast -mp kpitors.f
pgf95 -c -fast -mp kpolar.f
pgf95 -c -fast -mp ksolv.f
pgf95 -c -fast -mp kstrbnd.f
pgf95 -c -fast -mp kstrtor.f
pgf95 -c -fast -mp ktors.f
pgf95 -c -fast -mp ktortor.f
pgf95 -c -fast -mp kurey.f
pgf95 -c -fast -mp kvdw.f
pgf95 -c -fast -mp lattice.f
pgf95 -c -fast -mp lbfgs.f
pgf95 -c -fast -mp lights.f
pgf95 -c -fast -mp makeint.f
pgf95 -c -fast -mp makeref.f
pgf95 -c -fast -mp makexyz.f
pgf95 -c -fast -mp maxwell.f
pgf95 -c -fast -mp mdinit.f
pgf95 -c -fast -mp mdrest.f
pgf95 -c -fast -mp mdsave.f
pgf95 -c -fast -mp mdstat.f
pgf95 -c -fast -mp mechanic.f
pgf95 -c -fast -mp merge.f
pgf95 -c -fast -mp minimize.f
pgf95 -c -fast -mp minirot.f
pgf95 -c -fast -mp minrigid.f
pgf95 -c -fast -mp molecule.f
pgf95 -c -fast -mp molxyz.f
pgf95 -c -fast -mp moments.f
pgf95 -c -fast -mp monte.f
pgf95 -c -fast -mp mutate.f
pgf95 -c -fast -mp nblist.f
pgf95 -c -fast -mp newton.f
pgf95 -c -fast -mp newtrot.f
pgf95 -c -fast -mp nextarg.f
pgf95 -c -fast -mp nexttext.f
pgf95 -c -fast -mp nose.f
pgf95 -c -fast -mp nspline.f
pgf95 -c -fast -mp nucleic.f
pgf95 -c -fast -mp number.f
pgf95 -c -fast -mp numeral.f
pgf95 -c -fast -mp numgrad.f
pgf95 -c -fast -mp ocvm.f
pgf95 -c -fast -mp openend.f
pgf95 -c -fast -mp optimize.f
pgf95 -c -fast -mp optirot.f
pgf95 -c -fast -mp optrigid.f
pgf95 -c -fast -mp optsave.f
pgf95 -c -fast -mp orbital.f
pgf95 -c -fast -mp orient.f
pgf95 -c -fast -mp orthog.f
pgf95 -c -fast -mp overlap.f
pgf95 -c -fast -mp path.f
pgf95 -c -fast -mp pdbxyz.f
pgf95 -c -fast -mp picalc.f
pgf95 -c -fast -mp pmestuff.f
pgf95 -c -fast -mp pmpb.f
pgf95 -c -fast -mp polarize.f
pgf95 -c -fast -mp poledit.f
pgf95 -c -fast -mp polymer.f
pgf95 -c -fast -mp potential.f
pgf95 -c -fast -mp precise.f
pgf95 -c -fast -mp pressure.f
pgf95 -c -fast -mp prmedit.f
pgf95 -c -fast -mp prmkey.f
pgf95 -c -fast -mp promo.f
pgf95 -c -fast -mp protein.f
pgf95 -c -fast -mp prtdyn.f
pgf95 -c -fast -mp prterr.f
pgf95 -c -fast -mp prtint.f
pgf95 -c -fast -mp prtmol2.f
pgf95 -c -fast -mp prtpdb.f
pgf95 -c -fast -mp prtprm.f
pgf95 -c -fast -mp prtseq.f
pgf95 -c -fast -mp prtxyz.f
pgf95 -c -fast -mp pss.f
pgf95 -c -fast -mp pssrigid.f
pgf95 -c -fast -mp pssrot.f
pgf95 -c -fast -mp quatfit.f
pgf95 -c -fast -mp radial.f
pgf95 -c -fast -mp random.f
pgf95 -c -fast -mp rattle.f
pgf95 -c -fast -mp readdyn.f
pgf95 -c -fast -mp readgau.f
pgf95 -c -fast -mp readint.f
pgf95 -c -fast -mp readmol.f
pgf95 -c -fast -mp readmol2.f
pgf95 -c -fast -mp readpdb.f
pgf95 -c -fast -mp readprm.f
pgf95 -c -fast -mp readseq.f
pgf95 -c -fast -mp readxyz.f
pgf95 -c -fast -mp replica.f
pgf95 -c -fast -mp respa.f
pgf95 -c -fast -mp rgdstep.f
pgf95 -c -fast -mp rings.f
pgf95 -c -fast -mp rmsfit.f
pgf95 -c -fast -mp rotlist.f
pgf95 -c -fast -mp rotpole.f
pgf95 -c -fast -mp saddle.f
pgf95 -c -fast -mp scan.f
pgf95 -c -fast -mp sdstep.f
pgf95 -c -fast -mp search.f
pgf95 -c -fast -mp server.f
pgf95 -c -fast -mp shakeup.f
pgf95 -c -fast -mp sigmoid.f
pgf95 -c -fast -mp sktstuff.f
pgf95 -c -fast -mp sniffer.f
pgf95 -c -fast -mp sort.f
pgf95 -c -fast -mp spacefill.f
pgf95 -c -fast -mp spectrum.f
pgf95 -c -fast -mp square.f
pgf95 -c -fast -mp suffix.f
pgf95 -c -fast -mp superpose.f
pgf95 -c -fast -mp surface.f
pgf95 -c -fast -mp surfatom.f
pgf95 -c -fast -mp switch.f
pgf95 -c -fast -mp sybylxyz.f
pgf95 -c -fast -mp temper.f
pgf95 -c -fast -mp testgrad.f
pgf95 -c -fast -mp testhess.f
pgf95 -c -fast -mp testpair.f
pgf95 -c -fast -mp testpol.f
pgf95 -c -fast -mp testrot.f
pgf95 -c -fast -mp timer.f
pgf95 -c -fast -mp timerot.f
pgf95 -c -fast -mp tncg.f
pgf95 -c -fast -mp torphase.f
pgf95 -c -fast -mp torque.f
pgf95 -c -fast -mp torsfit.f
pgf95 -c -fast -mp torsions.f
pgf95 -c -fast -mp trimtext.f
pgf95 -c -fast -mp unitcell.f
pgf95 -c -fast -mp valence.f
pgf95 -c -fast -mp verlet.f
pgf95 -c -fast -mp version.f
pgf95 -c -fast -mp vibbig.f
pgf95 -c -fast -mp vibrate.f
pgf95 -c -fast -mp vibrot.f
pgf95 -c -fast -mp volume.f
pgf95 -c -fast -mp xtalfit.f
pgf95 -c -fast -mp xtalmin.f
pgf95 -c -fast -mp xyzatm.f
pgf95 -c -fast -mp xyzedit.f
pgf95 -c -fast -mp xyzint.f
pgf95 -c -fast -mp xyzpdb.f
pgf95 -c -fast -mp xyzsybyl.f
pgf95 -c -fast -mp zatom.f
