// apbs configuration header generated by CMake

// apbs version string
#define PACKAGE_STRING "1.5"

// apbs fast mode
/* #undef APBS_FAST */

// apbs debugging mode
/* #undef DEBUG */

// prints verbose debugging information
#define VERBOSE_DEBUG

// apbs quiet mode
/* #undef VAPBSQUIET */

// time function available
#define HAVE_TIME_FUNC

// rand function available
#define HAVE_RAND_FUNC

// srand function available
#define HAVE_SRAND_FUNC

// readline library is available
/* #undef HAVE_LIBREADLINE */

// do not inline functions
#define APBS_NOINLINE



// Is macro embedding availble?
/* #undef HAVE_EMBED */

// zlib compression is available
/* #undef HAVE_ZLIB */

// include TINKER support
#define WITH_TINKER



// FEtk components is enabled
/* #undef FETK_ENABLED */

// have FEtk component PUNC
// TODO: Rename this to HAVE_PUNC in source and /Data/software/apbs/apbs/CMakeLists.txt
/* #undef HAVE_PUNC_H */

// have FEtk component MCX
// TODO: Rename this to HAVE_MCX in source and /Data/software/apbs/apbs/CMakeLists.txt
/* #undef HAVE_MCX_H */

// have FEtk component MC
// TODO: Rename this to HAVE_MC in source and /Data/software/apbs/apbs/CMakeLists.txt
/* #undef HAVE_MC_H */

// have fetk component GAMER
// TODO: Rename this to HAVE_GAMER in source and /Data/software/apbs/apbs/CMakeLists.txt
/* #undef HAVE_BIOM_H */

/* #undef HAVE_MPI_H */

// The floating point epsilon for the current machine
#define FLOAT_EPSILON 2.220446e-16

// The double precision epsilon for the current machine
#define DOUBLE_EPSILON 2.220446e-16




// Remain for use be determined.

/* Define to 1 if you have the <inttypes.h> header file. */
//#undef HAVE_INTTYPES_H

/* Define to 1 if you have the <memory.h> header file. */
//#undef HAVE_MEMORY_H

/* have the MPI library */
//#undef HAVE_MPI_H
/* Define to 1 if you have the <stdint.h> header file. */
//#undef HAVE_STDINT_H

/* Define to 1 if you have the <stdlib.h> header file. */
//#undef HAVE_STDLIB_H

/* have machine-supplied strcasecmp */
//#undef HAVE_STRCASECMP

/* Define to 1 if you have the <strings.h> header file. */
//#undef HAVE_STRINGS_H

/* Define to 1 if you have the <string.h> header file. */
//#undef HAVE_STRING_H

/* Define to 1 if you have the <sys/stat.h> header file. */
//#undef HAVE_SYS_STAT_H

/* Define to 1 if you have the <sys/types.h> header file. */
//#undef HAVE_SYS_TYPES_H

/* Define to 1 if you have the <unistd.h> header file. */
//#undef HAVE_UNISTD_H

/* Define to the sub-directory in which libtool stores uninstalled libraries.
   */
//#undef LT_OBJDIR

/* Name of package */
//#undef PACKAGE

/* Define to the address where bug reports for this package should be sent. */
//#undef PACKAGE_BUGREPORT

/* Define to the full name of this package. */
//#undef PACKAGE_NAME

/* Define to the full name and version of this package. */
//#undef PACKAGE_STRING

/* Define to the one symbol short name of this package. */
//#undef PACKAGE_TARNAME

/* Define to the home page for this package. */
//#undef PACKAGE_URL

/* Define to the version of this package. */
//#undef PACKAGE_VERSION

/* Define to 1 if you have the ANSI C header files. */
//#undef STDC_HEADERS

/* use hierarchical basis method */
//#undef USE_HB

/* Version number of package */
//#undef VERSION
