#
#
#  ############################################################
#  ##                                                        ##
#  ##  compile.make  --  compile each of the TINKER modules  ##
#  ##            (PGI Fortran for Linux Version)             ##
#  ##                                                        ##
#  ############################################################
#
#
pgf77 -c -fast active.f
pgf77 -c -fast alchemy.f
pgf77 -c -fast analysis.f
pgf77 -c -fast analyze.f
pgf77 -c -fast angles.f
pgf77 -c -fast anneal.f
pgf77 -c -fast archive.f
pgf77 -c -fast attach.f
pgf77 -c -fast basefile.f
pgf77 -c -fast beeman.f
pgf77 -c -fast bicubic.f
pgf77 -c -fast bitors.f
pgf77 -c -fast bonds.f
pgf77 -c -fast born.f
pgf77 -c -fast bounds.f
pgf77 -c -fast calendar.f
pgf77 -c -fast center.f
pgf77 -c -fast chkpole.f
pgf77 -c -fast chkring.f
pgf77 -c -fast chkxyz.f
pgf77 -c -fast cholesky.f
pgf77 -c -fast clock.f
pgf77 -c -fast cluster.f
pgf77 -c -fast column.f
pgf77 -c -fast command.f
pgf77 -c -fast connect.f
pgf77 -c -fast connolly.f
pgf77 -c -fast control.f
pgf77 -c -fast correlate.f
pgf77 -c -fast crystal.f
pgf77 -c -fast cspline.f
pgf77 -c -fast cutoffs.f
pgf77 -c -fast deflate.f
pgf77 -c -fast delete.f
pgf77 -c -fast diagq.f
pgf77 -c -fast diffeq.f
pgf77 -c -fast diffuse.f
pgf77 -c -fast distgeom.f
pgf77 -c -fast document.f
pgf77 -c -fast dynamic.f
pgf77 -c -fast eangang.f
pgf77 -c -fast eangang1.f
pgf77 -c -fast eangang2.f
pgf77 -c -fast eangang3.f
pgf77 -c -fast eangle.f
pgf77 -c -fast eangle1.f
pgf77 -c -fast eangle2.f
pgf77 -c -fast eangle3.f
pgf77 -c -fast ebond.f
pgf77 -c -fast ebond1.f
pgf77 -c -fast ebond2.f
pgf77 -c -fast ebond3.f
pgf77 -c -fast ebuck.f
pgf77 -c -fast ebuck1.f
pgf77 -c -fast ebuck2.f
pgf77 -c -fast ebuck3.f
pgf77 -c -fast echarge.f
pgf77 -c -fast echarge1.f
pgf77 -c -fast echarge2.f
pgf77 -c -fast echarge3.f
pgf77 -c -fast echgdpl.f
pgf77 -c -fast echgdpl1.f
pgf77 -c -fast echgdpl2.f
pgf77 -c -fast echgdpl3.f
pgf77 -c -fast edipole.f
pgf77 -c -fast edipole1.f
pgf77 -c -fast edipole2.f
pgf77 -c -fast edipole3.f
pgf77 -c -fast egauss.f
pgf77 -c -fast egauss1.f
pgf77 -c -fast egauss2.f
pgf77 -c -fast egauss3.f
pgf77 -c -fast egeom.f
pgf77 -c -fast egeom1.f
pgf77 -c -fast egeom2.f
pgf77 -c -fast egeom3.f
pgf77 -c -fast ehal.f
pgf77 -c -fast ehal1.f
pgf77 -c -fast ehal2.f
pgf77 -c -fast ehal3.f
pgf77 -c -fast eimprop.f
pgf77 -c -fast eimprop1.f
pgf77 -c -fast eimprop2.f
pgf77 -c -fast eimprop3.f
pgf77 -c -fast eimptor.f
pgf77 -c -fast eimptor1.f
pgf77 -c -fast eimptor2.f
pgf77 -c -fast eimptor3.f
pgf77 -c -fast elj.f
pgf77 -c -fast elj1.f
pgf77 -c -fast elj2.f
pgf77 -c -fast elj3.f
pgf77 -c -fast embed.f
pgf77 -c -fast emetal.f
pgf77 -c -fast emetal1.f
pgf77 -c -fast emetal2.f
pgf77 -c -fast emetal3.f
pgf77 -c -fast emm3hb.f
pgf77 -c -fast emm3hb1.f
pgf77 -c -fast emm3hb2.f
pgf77 -c -fast emm3hb3.f
pgf77 -c -fast empole.f
pgf77 -c -fast empole1.f
pgf77 -c -fast empole2.f
pgf77 -c -fast empole3.f
pgf77 -c -fast energy.f
pgf77 -c -fast eopbend.f
pgf77 -c -fast eopbend1.f
pgf77 -c -fast eopbend2.f
pgf77 -c -fast eopbend3.f
pgf77 -c -fast eopdist.f
pgf77 -c -fast eopdist1.f
pgf77 -c -fast eopdist2.f
pgf77 -c -fast eopdist3.f
pgf77 -c -fast epitors.f
pgf77 -c -fast epitors1.f
pgf77 -c -fast epitors2.f
pgf77 -c -fast epitors3.f
pgf77 -c -fast erf.f
pgf77 -c -fast erxnfld.f
pgf77 -c -fast erxnfld1.f
pgf77 -c -fast erxnfld2.f
pgf77 -c -fast erxnfld3.f
pgf77 -c -fast esolv.f
pgf77 -c -fast esolv1.f
pgf77 -c -fast esolv2.f
pgf77 -c -fast esolv3.f
pgf77 -c -fast estrbnd.f
pgf77 -c -fast estrbnd1.f
pgf77 -c -fast estrbnd2.f
pgf77 -c -fast estrbnd3.f
pgf77 -c -fast estrtor.f
pgf77 -c -fast estrtor1.f
pgf77 -c -fast estrtor2.f
pgf77 -c -fast estrtor3.f
pgf77 -c -fast etors.f
pgf77 -c -fast etors1.f
pgf77 -c -fast etors2.f
pgf77 -c -fast etors3.f
pgf77 -c -fast etortor.f
pgf77 -c -fast etortor1.f
pgf77 -c -fast etortor2.f
pgf77 -c -fast etortor3.f
pgf77 -c -fast eurey.f
pgf77 -c -fast eurey1.f
pgf77 -c -fast eurey2.f
pgf77 -c -fast eurey3.f
pgf77 -c -fast evcorr.f
pgf77 -c -fast extra.f
pgf77 -c -fast extra1.f
pgf77 -c -fast extra2.f
pgf77 -c -fast extra3.f
pgf77 -c -fast fatal.f
pgf77 -c -fast fft3d.f
pgf77 -c -fast fftpack.f
pgf77 -c -fast field.f
pgf77 -c -fast final.f
pgf77 -c -fast flatten.f
pgf77 -c -fast freeunit.f
pgf77 -c -fast gda.f
pgf77 -c -fast geometry.f
pgf77 -c -fast getime.f
pgf77 -c -fast getint.f
pgf77 -c -fast getkey.f
pgf77 -c -fast getmol2.f
pgf77 -c -fast getnumb.f
pgf77 -c -fast getpdb.f
pgf77 -c -fast getprm.f
pgf77 -c -fast getref.f
pgf77 -c -fast getstring.f
pgf77 -c -fast gettext.f
pgf77 -c -fast getword.f
pgf77 -c -fast getxyz.f
pgf77 -c -fast gradient.f
pgf77 -c -fast gradrgd.f
pgf77 -c -fast gradrot.f
pgf77 -c -fast groups.f
pgf77 -c -fast grpline.f
pgf77 -c -fast gyrate.f
pgf77 -c -fast hessian.f
pgf77 -c -fast hessrgd.f
pgf77 -c -fast hessrot.f
pgf77 -c -fast hybrid.f
pgf77 -c -fast image.f
pgf77 -c -fast impose.f
pgf77 -c -fast induce.f
pgf77 -c -fast inertia.f
pgf77 -c -fast initial.f
pgf77 -c -fast initprm.f
pgf77 -c -fast initres.f
pgf77 -c -fast initrot.f
pgf77 -c -fast insert.f
pgf77 -c -fast intedit.f
pgf77 -c -fast intxyz.f
pgf77 -c -fast invbeta.f
pgf77 -c -fast invert.f
pgf77 -c -fast jacobi.f
pgf77 -c -fast kangang.f
pgf77 -c -fast kangle.f
pgf77 -c -fast katom.f
pgf77 -c -fast kbond.f
pgf77 -c -fast kcharge.f
pgf77 -c -fast kdipole.f
pgf77 -c -fast kewald.f
pgf77 -c -fast kgeom.f
pgf77 -c -fast kimprop.f
pgf77 -c -fast kimptor.f
pgf77 -c -fast kinetic.f
pgf77 -c -fast kmetal.f
pgf77 -c -fast kmpole.f
pgf77 -c -fast kopbend.f
pgf77 -c -fast kopdist.f
pgf77 -c -fast korbit.f
pgf77 -c -fast kpitors.f
pgf77 -c -fast kpolar.f
pgf77 -c -fast ksolv.f
pgf77 -c -fast kstrbnd.f
pgf77 -c -fast kstrtor.f
pgf77 -c -fast ktors.f
pgf77 -c -fast ktortor.f
pgf77 -c -fast kurey.f
pgf77 -c -fast kvdw.f
pgf77 -c -fast lattice.f
pgf77 -c -fast lbfgs.f
pgf77 -c -fast lights.f
pgf77 -c -fast makeint.f
pgf77 -c -fast makepdb.f
pgf77 -c -fast makeref.f
pgf77 -c -fast makexyz.f
pgf77 -c -fast maxwell.f
pgf77 -c -fast mdinit.f
pgf77 -c -fast mdrest.f
pgf77 -c -fast mdsave.f
pgf77 -c -fast mdstat.f
pgf77 -c -fast mechanic.f
pgf77 -c -fast merge.f
pgf77 -c -fast minimize.f
pgf77 -c -fast minirot.f
pgf77 -c -fast minrigid.f
pgf77 -c -fast molecule.f
pgf77 -c -fast moments.f
pgf77 -c -fast monte.f
pgf77 -c -fast mutate.f
pgf77 -c -fast nblist.f
pgf77 -c -fast newton.f
pgf77 -c -fast newtrot.f
pgf77 -c -fast nextarg.f
pgf77 -c -fast nexttext.f
pgf77 -c -fast nspline.f
pgf77 -c -fast nucleic.f
pgf77 -c -fast number.f
pgf77 -c -fast numeral.f
pgf77 -c -fast numgrad.f
pgf77 -c -fast ocvm.f
pgf77 -c -fast openend.f
pgf77 -c -fast optimize.f
pgf77 -c -fast optirot.f
pgf77 -c -fast optrigid.f
pgf77 -c -fast optsave.f
pgf77 -c -fast orbital.f
pgf77 -c -fast orient.f
pgf77 -c -fast orthog.f
pgf77 -c -fast overlap.f
pgf77 -c -fast path.f
pgf77 -c -fast pdbxyz.f
pgf77 -c -fast piscf.f
pgf77 -c -fast pmestuff.f
pgf77 -c -fast pmpb.f
pgf77 -c -fast polarize.f
pgf77 -c -fast poledit.f
pgf77 -c -fast polymer.f
pgf77 -c -fast potential.f
pgf77 -c -fast precise.f
pgf77 -c -fast pressure.f
pgf77 -c -fast prmedit.f
pgf77 -c -fast prmkey.f
pgf77 -c -fast promo.f
pgf77 -c -fast protein.f
pgf77 -c -fast prtdyn.f
pgf77 -c -fast prterr.f
pgf77 -c -fast prtint.f
pgf77 -c -fast prtmol2.f
pgf77 -c -fast prtpdb.f
pgf77 -c -fast prtprm.f
pgf77 -c -fast prtseq.f
pgf77 -c -fast prtxyz.f
pgf77 -c -fast pss.f
pgf77 -c -fast pssrigid.f
pgf77 -c -fast pssrot.f
pgf77 -c -fast quatfit.f
pgf77 -c -fast radial.f
pgf77 -c -fast random.f
pgf77 -c -fast rattle.f
pgf77 -c -fast readdyn.f
pgf77 -c -fast readgau.f
pgf77 -c -fast readint.f
pgf77 -c -fast readmol2.f
pgf77 -c -fast readpdb.f
pgf77 -c -fast readprm.f
pgf77 -c -fast readseq.f
pgf77 -c -fast readxyz.f
pgf77 -c -fast replica.f
pgf77 -c -fast rgdstep.f
pgf77 -c -fast rings.f
pgf77 -c -fast rmsfit.f
pgf77 -c -fast rotlist.f
pgf77 -c -fast rotpole.f
pgf77 -c -fast saddle.f
pgf77 -c -fast scan.f
pgf77 -c -fast sdstep.f
pgf77 -c -fast search.f
pgf77 -c -fast server.f
pgf77 -c -fast setime.f
pgf77 -c -fast shakeup.f
pgf77 -c -fast sigmoid.f
pgf77 -c -fast sktstuff.f
pgf77 -c -fast sniffer.f
pgf77 -c -fast sort.f
pgf77 -c -fast spacefill.f
pgf77 -c -fast spectrum.f
pgf77 -c -fast square.f
pgf77 -c -fast suffix.f
pgf77 -c -fast superpose.f
pgf77 -c -fast surface.f
pgf77 -c -fast surfatom.f
pgf77 -c -fast switch.f
pgf77 -c -fast sybylxyz.f
pgf77 -c -fast temper.f
pgf77 -c -fast testgrad.f
pgf77 -c -fast testhess.f
pgf77 -c -fast testpair.f
pgf77 -c -fast testrot.f
pgf77 -c -fast timer.f
pgf77 -c -fast timerot.f
pgf77 -c -fast tncg.f
pgf77 -c -fast torphase.f
pgf77 -c -fast torque.f
pgf77 -c -fast torsfit.f
pgf77 -c -fast torsions.f
pgf77 -c -fast trimtext.f
pgf77 -c -fast unitcell.f
pgf77 -c -fast valence.f
pgf77 -c -fast verlet.f
pgf77 -c -fast version.f
pgf77 -c -fast vibbig.f
pgf77 -c -fast vibrate.f
pgf77 -c -fast vibrot.f
pgf77 -c -fast volume.f
pgf77 -c -fast xtalfit.f
pgf77 -c -fast xtalmin.f
pgf77 -c -fast xyzatm.f
pgf77 -c -fast xyzedit.f
pgf77 -c -fast xyzint.f
pgf77 -c -fast xyzpdb.f
pgf77 -c -fast xyzsybyl.f
pgf77 -c -fast zatom.f
