#
#
#  ############################################################
#  ##                                                        ##
#  ##  compile.make  --  compile each of the TINKER modules  ##
#  ##            (GNU gfortran for Linux Version)            ##
#  ##                                                        ##
#  ############################################################
#
#
gfortran -c -O active.f
gfortran -c -O alchemy.f
gfortran -c -O analysis.f
gfortran -c -O analyze.f
gfortran -c -O angles.f
gfortran -c -O anneal.f
gfortran -c -O archive.f
gfortran -c -O attach.f
gfortran -c -O basefile.f
gfortran -c -O beeman.f
gfortran -c -O bicubic.f
gfortran -c -O bitors.f
gfortran -c -O bonds.f
gfortran -c -O born.f
gfortran -c -O bounds.f
gfortran -c -O bussi.f
gfortran -c -O calendar.f
gfortran -c -O center.f
gfortran -c -O chkpole.f
gfortran -c -O chkring.f
gfortran -c -O chkxyz.f
gfortran -c -O cholesky.f
gfortran -c -O clock.f
gfortran -c -O cluster.f
gfortran -c -O column.f
gfortran -c -O command.f
gfortran -c -O connect.f
gfortran -c -O connolly.f
gfortran -c -O control.f
gfortran -c -O correlate.f
gfortran -c -O crystal.f
gfortran -c -O cspline.f
gfortran -c -O cutoffs.f
gfortran -c -O deflate.f
gfortran -c -O delete.f
gfortran -c -O diagq.f
gfortran -c -O diffeq.f
gfortran -c -O diffuse.f
gfortran -c -O distgeom.f
gfortran -c -O document.f
gfortran -c -O dynamic.f
gfortran -c -O eangang.f
gfortran -c -O eangang1.f
gfortran -c -O eangang2.f
gfortran -c -O eangang3.f
gfortran -c -O eangle.f
gfortran -c -O eangle1.f
gfortran -c -O eangle2.f
gfortran -c -O eangle3.f
gfortran -c -O ebond.f
gfortran -c -O ebond1.f
gfortran -c -O ebond2.f
gfortran -c -O ebond3.f
gfortran -c -O ebuck.f
gfortran -c -O ebuck1.f
gfortran -c -O ebuck2.f
gfortran -c -O ebuck3.f
gfortran -c -O echarge.f
gfortran -c -O echarge1.f
gfortran -c -O echarge2.f
gfortran -c -O echarge3.f
gfortran -c -O echgdpl.f
gfortran -c -O echgdpl1.f
gfortran -c -O echgdpl2.f
gfortran -c -O echgdpl3.f
gfortran -c -O edipole.f
gfortran -c -O edipole1.f
gfortran -c -O edipole2.f
gfortran -c -O edipole3.f
gfortran -c -O egauss.f
gfortran -c -O egauss1.f
gfortran -c -O egauss2.f
gfortran -c -O egauss3.f
gfortran -c -O egeom.f
gfortran -c -O egeom1.f
gfortran -c -O egeom2.f
gfortran -c -O egeom3.f
gfortran -c -O ehal.f
gfortran -c -O ehal1.f
gfortran -c -O ehal2.f
gfortran -c -O ehal3.f
gfortran -c -O eimprop.f
gfortran -c -O eimprop1.f
gfortran -c -O eimprop2.f
gfortran -c -O eimprop3.f
gfortran -c -O eimptor.f
gfortran -c -O eimptor1.f
gfortran -c -O eimptor2.f
gfortran -c -O eimptor3.f
gfortran -c -O elj.f
gfortran -c -O elj1.f
gfortran -c -O elj2.f
gfortran -c -O elj3.f
gfortran -c -O embed.f
gfortran -c -O emetal.f
gfortran -c -O emetal1.f
gfortran -c -O emetal2.f
gfortran -c -O emetal3.f
gfortran -c -O emm3hb.f
gfortran -c -O emm3hb1.f
gfortran -c -O emm3hb2.f
gfortran -c -O emm3hb3.f
gfortran -c -O empole.f
gfortran -c -O empole1.f
gfortran -c -O empole2.f
gfortran -c -O empole3.f
gfortran -c -O energy.f
gfortran -c -O eopbend.f
gfortran -c -O eopbend1.f
gfortran -c -O eopbend2.f
gfortran -c -O eopbend3.f
gfortran -c -O eopdist.f
gfortran -c -O eopdist1.f
gfortran -c -O eopdist2.f
gfortran -c -O eopdist3.f
gfortran -c -O epitors.f
gfortran -c -O epitors1.f
gfortran -c -O epitors2.f
gfortran -c -O epitors3.f
gfortran -c -O erf.f
gfortran -c -O erxnfld.f
gfortran -c -O erxnfld1.f
gfortran -c -O erxnfld2.f
gfortran -c -O erxnfld3.f
gfortran -c -O esolv.f
gfortran -c -O esolv1.f
gfortran -c -O esolv2.f
gfortran -c -O esolv3.f
gfortran -c -O estrbnd.f
gfortran -c -O estrbnd1.f
gfortran -c -O estrbnd2.f
gfortran -c -O estrbnd3.f
gfortran -c -O estrtor.f
gfortran -c -O estrtor1.f
gfortran -c -O estrtor2.f
gfortran -c -O estrtor3.f
gfortran -c -O etors.f
gfortran -c -O etors1.f
gfortran -c -O etors2.f
gfortran -c -O etors3.f
gfortran -c -O etortor.f
gfortran -c -O etortor1.f
gfortran -c -O etortor2.f
gfortran -c -O etortor3.f
gfortran -c -O eurey.f
gfortran -c -O eurey1.f
gfortran -c -O eurey2.f
gfortran -c -O eurey3.f
gfortran -c -O evcorr.f
gfortran -c -O extra.f
gfortran -c -O extra1.f
gfortran -c -O extra2.f
gfortran -c -O extra3.f
gfortran -c -O fatal.f
gfortran -c -O fft3d.f
gfortran -c -O fftpack.f
gfortran -c -O field.f
gfortran -c -O final.f
gfortran -c -O flatten.f
gfortran -c -O freeunit.f
gfortran -c -O gda.f
gfortran -c -O geometry.f
gfortran -c -O getint.f
gfortran -c -O getkey.f
gfortran -c -O getmol.f
gfortran -c -O getmol2.f
gfortran -c -O getnumb.f
gfortran -c -O getpdb.f
gfortran -c -O getprm.f
gfortran -c -O getref.f
gfortran -c -O getstring.f
gfortran -c -O gettext.f
gfortran -c -O getword.f
gfortran -c -O getxyz.f
gfortran -c -O ghmcstep.f
gfortran -c -O gradient.f
gfortran -c -O gradrgd.f
gfortran -c -O gradrot.f
gfortran -c -O groups.f
gfortran -c -O grpline.f
gfortran -c -O gyrate.f
gfortran -c -O hessian.f
gfortran -c -O hessrgd.f
gfortran -c -O hessrot.f
gfortran -c -O hybrid.f
gfortran -c -O image.f
gfortran -c -O impose.f
gfortran -c -O induce.f
gfortran -c -O inertia.f
gfortran -c -O initatom.f
gfortran -c -O initial.f
gfortran -c -O initprm.f
gfortran -c -O initres.f
gfortran -c -O initrot.f
gfortran -c -O insert.f
gfortran -c -O intedit.f
gfortran -c -O intxyz.f
gfortran -c -O invbeta.f
gfortran -c -O invert.f
gfortran -c -O jacobi.f
gfortran -c -O kangang.f
gfortran -c -O kangle.f
gfortran -c -O katom.f
gfortran -c -O kbond.f
gfortran -c -O kcharge.f
gfortran -c -O kdipole.f
gfortran -c -O kewald.f
gfortran -c -O kgeom.f
gfortran -c -O kimprop.f
gfortran -c -O kimptor.f
gfortran -c -O kinetic.f
gfortran -c -O kmetal.f
gfortran -c -O kmpole.f
gfortran -c -O kopbend.f
gfortran -c -O kopdist.f
gfortran -c -O korbit.f
gfortran -c -O kpitors.f
gfortran -c -O kpolar.f
gfortran -c -O ksolv.f
gfortran -c -O kstrbnd.f
gfortran -c -O kstrtor.f
gfortran -c -O ktors.f
gfortran -c -O ktortor.f
gfortran -c -O kurey.f
gfortran -c -O kvdw.f
gfortran -c -O lattice.f
gfortran -c -O lbfgs.f
gfortran -c -O lights.f
gfortran -c -O makeint.f
gfortran -c -O makeref.f
gfortran -c -O makexyz.f
gfortran -c -O maxwell.f
gfortran -c -O mdinit.f
gfortran -c -O mdrest.f
gfortran -c -O mdsave.f
gfortran -c -O mdstat.f
gfortran -c -O mechanic.f
gfortran -c -O merge.f
gfortran -c -O minimize.f
gfortran -c -O minirot.f
gfortran -c -O minrigid.f
gfortran -c -O molecule.f
gfortran -c -O molxyz.f
gfortran -c -O moments.f
gfortran -c -O monte.f
gfortran -c -O mutate.f
gfortran -c -O nblist.f
gfortran -c -O newton.f
gfortran -c -O newtrot.f
gfortran -c -O nextarg.f
gfortran -c -O nexttext.f
gfortran -c -O nose.f
gfortran -c -O nspline.f
gfortran -c -O nucleic.f
gfortran -c -O number.f
gfortran -c -O numeral.f
gfortran -c -O numgrad.f
gfortran -c -O ocvm.f
gfortran -c -O openend.f
gfortran -c -O optimize.f
gfortran -c -O optirot.f
gfortran -c -O optrigid.f
gfortran -c -O optsave.f
gfortran -c -O orbital.f
gfortran -c -O orient.f
gfortran -c -O orthog.f
gfortran -c -O overlap.f
gfortran -c -O path.f
gfortran -c -O pdbxyz.f
gfortran -c -O picalc.f
gfortran -c -O pmestuff.f
gfortran -c -O pmpb.f
gfortran -c -O polarize.f
gfortran -c -O poledit.f
gfortran -c -O polymer.f
gfortran -c -O potential.f
gfortran -c -O precise.f
gfortran -c -O pressure.f
gfortran -c -O prmedit.f
gfortran -c -O prmkey.f
gfortran -c -O promo.f
gfortran -c -O protein.f
gfortran -c -O prtdyn.f
gfortran -c -O prterr.f
gfortran -c -O prtint.f
gfortran -c -O prtmol2.f
gfortran -c -O prtpdb.f
gfortran -c -O prtprm.f
gfortran -c -O prtseq.f
gfortran -c -O prtxyz.f
gfortran -c -O pss.f
gfortran -c -O pssrigid.f
gfortran -c -O pssrot.f
gfortran -c -O quatfit.f
gfortran -c -O radial.f
gfortran -c -O random.f
gfortran -c -O rattle.f
gfortran -c -O readdyn.f
gfortran -c -O readgau.f
gfortran -c -O readint.f
gfortran -c -O readmol.f
gfortran -c -O readmol2.f
gfortran -c -O readpdb.f
gfortran -c -O readprm.f
gfortran -c -O readseq.f
gfortran -c -O readxyz.f
gfortran -c -O replica.f
gfortran -c -O respa.f
gfortran -c -O rgdstep.f
gfortran -c -O rings.f
gfortran -c -O rmsfit.f
gfortran -c -O rotlist.f
gfortran -c -O rotpole.f
gfortran -c -O saddle.f
gfortran -c -O scan.f
gfortran -c -O sdstep.f
gfortran -c -O search.f
gfortran -c -O server.f
gfortran -c -O shakeup.f
gfortran -c -O sigmoid.f
gfortran -c -O sktstuff.f
gfortran -c -O sniffer.f
gfortran -c -O sort.f
gfortran -c -O spacefill.f
gfortran -c -O spectrum.f
gfortran -c -O square.f
gfortran -c -O suffix.f
gfortran -c -O superpose.f
gfortran -c -O surface.f
gfortran -c -O surfatom.f
gfortran -c -O switch.f
gfortran -c -O sybylxyz.f
gfortran -c -O temper.f
gfortran -c -O testgrad.f
gfortran -c -O testhess.f
gfortran -c -O testpair.f
gfortran -c -O testrot.f
gfortran -c -O timer.f
gfortran -c -O timerot.f
gfortran -c -O tncg.f
gfortran -c -O torphase.f
gfortran -c -O torque.f
gfortran -c -O torsfit.f
gfortran -c -O torsions.f
gfortran -c -O trimtext.f
gfortran -c -O unitcell.f
gfortran -c -O valence.f
gfortran -c -O verlet.f
gfortran -c -O version.f
gfortran -c -O vibbig.f
gfortran -c -O vibrate.f
gfortran -c -O vibrot.f
gfortran -c -O volume.f
gfortran -c -O xtalfit.f
gfortran -c -O xtalmin.f
gfortran -c -O xyzatm.f
gfortran -c -O xyzedit.f
gfortran -c -O xyzint.f
gfortran -c -O xyzpdb.f
gfortran -c -O xyzsybyl.f
gfortran -c -O zatom.f
