#
#
#  ################################################################
#  ##                                                            ##
#  ##  debug.make  --  compile Tinker routines with debug flags  ##
#  ##              (GNU gfortran for Linux Version)              ##
#  ##                                                            ##
#  ################################################################
#
#
#  compile all the modules; "sizes" must be first since it
#  sets static array dimensions in many of the other modules
#
#
gfortran -c -Og -g -Wall sizes.f
gfortran -c -Og -g -Wall action.f
gfortran -c -Og -g -Wall alfmol.f
gfortran -c -Og -g -Wall align.f
gfortran -c -Og -g -Wall analyz.f
gfortran -c -Og -g -Wall angang.f
gfortran -c -Og -g -Wall angbnd.f
gfortran -c -Og -g -Wall angpot.f
gfortran -c -Og -g -Wall angtor.f
gfortran -c -Og -g -Wall argue.f
gfortran -c -Og -g -Wall ascii.f
gfortran -c -Og -g -Wall atmlst.f
gfortran -c -Og -g -Wall atomid.f
gfortran -c -Og -g -Wall atoms.f
gfortran -c -Og -g -Wall bath.f
gfortran -c -Og -g -Wall bitor.f
gfortran -c -Og -g -Wall bndpot.f
gfortran -c -Og -g -Wall bndstr.f
gfortran -c -Og -g -Wall bound.f
gfortran -c -Og -g -Wall boxes.f
gfortran -c -Og -g -Wall cell.f
gfortran -c -Og -g -Wall cflux.f
gfortran -c -Og -g -Wall charge.f
gfortran -c -Og -g -Wall chgpen.f
gfortran -c -Og -g -Wall chgpot.f
gfortran -c -Og -g -Wall chgtrn.f
gfortran -c -Og -g -Wall chrono.f
gfortran -c -Og -g -Wall chunks.f
gfortran -c -Og -g -Wall couple.f
gfortran -c -Og -g -Wall ctrpot.f
gfortran -c -Og -g -Wall deriv.f
gfortran -c -Og -g -Wall dipole.f
gfortran -c -Og -g -Wall disgeo.f
gfortran -c -Og -g -Wall disp.f
gfortran -c -Og -g -Wall dma.f
gfortran -c -Og -g -Wall domega.f
gfortran -c -Og -g -Wall dsppot.f
gfortran -c -Og -g -Wall energi.f
gfortran -c -Og -g -Wall ewald.f
gfortran -c -Og -g -Wall expol.f
gfortran -c -Og -g -Wall extfld.f
gfortran -c -Og -g -Wall faces.f
gfortran -c -Og -g -Wall fft.f
gfortran -c -Og -g -Wall fields.f
gfortran -c -Og -g -Wall files.f
gfortran -c -Og -g -Wall fracs.f
gfortran -c -Og -g -Wall freeze.f
gfortran -c -Og -g -Wall gkstuf.f
gfortran -c -Og -g -Wall group.f
gfortran -c -Og -g -Wall hescut.f
gfortran -c -Og -g -Wall hessn.f
gfortran -c -Og -g -Wall hpmf.f
gfortran -c -Og -g -Wall ielscf.f
gfortran -c -Og -g -Wall improp.f
gfortran -c -Og -g -Wall imptor.f
gfortran -c -Og -g -Wall inform.f
gfortran -c -Og -g -Wall inter.f
gfortran -c -Og -g -Wall iounit.f
gfortran -c -Og -g -Wall kanang.f
gfortran -c -Og -g -Wall kangs.f
gfortran -c -Og -g -Wall kantor.f
gfortran -c -Og -g -Wall katoms.f
gfortran -c -Og -g -Wall kbonds.f
gfortran -c -Og -g -Wall kcflux.f
gfortran -c -Og -g -Wall kchrge.f
gfortran -c -Og -g -Wall kcpen.f
gfortran -c -Og -g -Wall kctrn.f
gfortran -c -Og -g -Wall kdipol.f
gfortran -c -Og -g -Wall kdsp.f
gfortran -c -Og -g -Wall kexpl.f
gfortran -c -Og -g -Wall keys.f
gfortran -c -Og -g -Wall khbond.f
gfortran -c -Og -g -Wall kiprop.f
gfortran -c -Og -g -Wall kitors.f
gfortran -c -Og -g -Wall kmulti.f
gfortran -c -Og -g -Wall kopbnd.f
gfortran -c -Og -g -Wall kopdst.f
gfortran -c -Og -g -Wall korbs.f
gfortran -c -Og -g -Wall kpitor.f
gfortran -c -Og -g -Wall kpolpr.f
gfortran -c -Og -g -Wall kpolr.f
gfortran -c -Og -g -Wall krepl.f
gfortran -c -Og -g -Wall ksolut.f
gfortran -c -Og -g -Wall kstbnd.f
gfortran -c -Og -g -Wall ksttor.f
gfortran -c -Og -g -Wall ktorsn.f
gfortran -c -Og -g -Wall ktrtor.f
gfortran -c -Og -g -Wall kurybr.f
gfortran -c -Og -g -Wall kvdwpr.f
gfortran -c -Og -g -Wall kvdws.f
gfortran -c -Og -g -Wall light.f
gfortran -c -Og -g -Wall limits.f
gfortran -c -Og -g -Wall linmin.f
gfortran -c -Og -g -Wall math.f
gfortran -c -Og -g -Wall mdstuf.f
gfortran -c -Og -g -Wall merck.f
gfortran -c -Og -g -Wall minima.f
gfortran -c -Og -g -Wall molcul.f
gfortran -c -Og -g -Wall moldyn.f
gfortran -c -Og -g -Wall moment.f
gfortran -c -Og -g -Wall mplpot.f
gfortran -c -Og -g -Wall mpole.f
gfortran -c -Og -g -Wall mrecip.f
gfortran -c -Og -g -Wall mutant.f
gfortran -c -Og -g -Wall neigh.f
gfortran -c -Og -g -Wall nonpol.f
gfortran -c -Og -g -Wall nucleo.f
gfortran -c -Og -g -Wall omega.f
gfortran -c -Og -g -Wall opbend.f
gfortran -c -Og -g -Wall opdist.f
gfortran -c -Og -g -Wall openmp.f
gfortran -c -Og -g -Wall orbits.f
gfortran -c -Og -g -Wall output.f
gfortran -c -Og -g -Wall params.f
gfortran -c -Og -g -Wall paths.f
gfortran -c -Og -g -Wall pbstuf.f
gfortran -c -Og -g -Wall pdb.f
gfortran -c -Og -g -Wall phipsi.f
gfortran -c -Og -g -Wall piorbs.f
gfortran -c -Og -g -Wall pistuf.f
gfortran -c -Og -g -Wall pitors.f
gfortran -c -Og -g -Wall pme.f
gfortran -c -Og -g -Wall polar.f
gfortran -c -Og -g -Wall polgrp.f
gfortran -c -Og -g -Wall polopt.f
gfortran -c -Og -g -Wall polpcg.f
gfortran -c -Og -g -Wall polpot.f
gfortran -c -Og -g -Wall poltcg.f
gfortran -c -Og -g -Wall potent.f
gfortran -c -Og -g -Wall potfit.f
gfortran -c -Og -g -Wall ptable.f
gfortran -c -Og -g -Wall qmstuf.f
gfortran -c -Og -g -Wall refer.f
gfortran -c -Og -g -Wall repel.f
gfortran -c -Og -g -Wall reppot.f
gfortran -c -Og -g -Wall resdue.f
gfortran -c -Og -g -Wall restrn.f
gfortran -c -Og -g -Wall rgddyn.f
gfortran -c -Og -g -Wall rigid.f
gfortran -c -Og -g -Wall ring.f
gfortran -c -Og -g -Wall rotbnd.f
gfortran -c -Og -g -Wall rxnfld.f
gfortran -c -Og -g -Wall rxnpot.f
gfortran -c -Og -g -Wall scales.f
gfortran -c -Og -g -Wall sequen.f
gfortran -c -Og -g -Wall shapes.f
gfortran -c -Og -g -Wall shunt.f
gfortran -c -Og -g -Wall socket.f
gfortran -c -Og -g -Wall solpot.f
gfortran -c -Og -g -Wall solute.f
gfortran -c -Og -g -Wall stodyn.f
gfortran -c -Og -g -Wall strbnd.f
gfortran -c -Og -g -Wall strtor.f
gfortran -c -Og -g -Wall syntrn.f
gfortran -c -Og -g -Wall tarray.f
gfortran -c -Og -g -Wall tettor.f
gfortran -c -Og -g -Wall titles.f
gfortran -c -Og -g -Wall torpot.f
gfortran -c -Og -g -Wall tors.f
gfortran -c -Og -g -Wall tortor.f
gfortran -c -Og -g -Wall tree.f
gfortran -c -Og -g -Wall tritor.f
gfortran -c -Og -g -Wall units.f
gfortran -c -Og -g -Wall uprior.f
gfortran -c -Og -g -Wall urey.f
gfortran -c -Og -g -Wall urypot.f
gfortran -c -Og -g -Wall usage.f
gfortran -c -Og -g -Wall valfit.f
gfortran -c -Og -g -Wall vdw.f
gfortran -c -Og -g -Wall vdwpot.f
gfortran -c -Og -g -Wall vibs.f
gfortran -c -Og -g -Wall virial.f
gfortran -c -Og -g -Wall warp.f
gfortran -c -Og -g -Wall xtals.f
gfortran -c -Og -g -Wall zclose.f
gfortran -c -Og -g -Wall zcoord.f
#
#  now compile separately each of the Fortran source files
#
gfortran -c -Og -g -Wall active.f
gfortran -c -Og -g -Wall alchemy.f
gfortran -c -Og -g -Wall alterchg.f
gfortran -c -Og -g -Wall alterpol.f
gfortran -c -Og -g -Wall analysis.f
gfortran -c -Og -g -Wall analyze.f
gfortran -c -Og -g -Wall angles.f
gfortran -c -Og -g -Wall anneal.f
gfortran -c -Og -g -Wall arcedit.f
gfortran -c -Og -g -Wall attach.f
gfortran -c -Og -g -Wall baoab.f
gfortran -c -Og -g -Wall bar.f
gfortran -c -Og -g -Wall basefile.f
gfortran -c -Og -g -Wall beeman.f
gfortran -c -Og -g -Wall bicubic.f
gfortran -c -Og -g -Wall bitors.f
gfortran -c -Og -g -Wall bonds.f
gfortran -c -Og -g -Wall born.f
gfortran -c -Og -g -Wall bounds.f
gfortran -c -Og -g -Wall calendar.f
gfortran -c -Og -g -Wall center.f
gfortran -c -Og -g -Wall chkpole.f
gfortran -c -Og -g -Wall chkring.f
gfortran -c -Og -g -Wall chksymm.f
gfortran -c -Og -g -Wall chkxyz.f
gfortran -c -Og -g -Wall cholesky.f
gfortran -c -Og -g -Wall clock.f
gfortran -c -Og -g -Wall cluster.f
gfortran -c -Og -g -Wall column.f
gfortran -c -Og -g -Wall command.f
gfortran -c -Og -g -Wall connect.f
gfortran -c -Og -g -Wall connolly.f
gfortran -c -Og -g -Wall control.f
gfortran -c -Og -g -Wall correlate.f
gfortran -c -Og -g -Wall critical.f
gfortran -c -Og -g -Wall crystal.f
gfortran -c -Og -g -Wall cspline.f
gfortran -c -Og -g -Wall cutoffs.f
gfortran -c -Og -g -Wall damping.f
gfortran -c -Og -g -Wall dcflux.f
gfortran -c -Og -g -Wall deflate.f
gfortran -c -Og -g -Wall delete.f
gfortran -c -Og -g -Wall dexpol.f
gfortran -c -Og -g -Wall diagq.f
gfortran -c -Og -g -Wall diffeq.f
gfortran -c -Og -g -Wall diffuse.f
gfortran -c -Og -g -Wall distgeom.f
gfortran -c -Og -g -Wall document.f
gfortran -c -Og -g -Wall dynamic.f
gfortran -c -Og -g -Wall eangang.f
gfortran -c -Og -g -Wall eangang1.f
gfortran -c -Og -g -Wall eangang2.f
gfortran -c -Og -g -Wall eangang3.f
gfortran -c -Og -g -Wall eangle.f
gfortran -c -Og -g -Wall eangle1.f
gfortran -c -Og -g -Wall eangle2.f
gfortran -c -Og -g -Wall eangle3.f
gfortran -c -Og -g -Wall eangtor.f
gfortran -c -Og -g -Wall eangtor1.f
gfortran -c -Og -g -Wall eangtor2.f
gfortran -c -Og -g -Wall eangtor3.f
gfortran -c -Og -g -Wall ebond.f
gfortran -c -Og -g -Wall ebond1.f
gfortran -c -Og -g -Wall ebond2.f
gfortran -c -Og -g -Wall ebond3.f
gfortran -c -Og -g -Wall ebuck.f
gfortran -c -Og -g -Wall ebuck1.f
gfortran -c -Og -g -Wall ebuck2.f
gfortran -c -Og -g -Wall ebuck3.f
gfortran -c -Og -g -Wall echarge.f
gfortran -c -Og -g -Wall echarge1.f
gfortran -c -Og -g -Wall echarge2.f
gfortran -c -Og -g -Wall echarge3.f
gfortran -c -Og -g -Wall echgdpl.f
gfortran -c -Og -g -Wall echgdpl1.f
gfortran -c -Og -g -Wall echgdpl2.f
gfortran -c -Og -g -Wall echgdpl3.f
gfortran -c -Og -g -Wall echgtrn.f
gfortran -c -Og -g -Wall echgtrn1.f
gfortran -c -Og -g -Wall echgtrn2.f
gfortran -c -Og -g -Wall echgtrn3.f
gfortran -c -Og -g -Wall edipole.f
gfortran -c -Og -g -Wall edipole1.f
gfortran -c -Og -g -Wall edipole2.f
gfortran -c -Og -g -Wall edipole3.f
gfortran -c -Og -g -Wall edisp.f
gfortran -c -Og -g -Wall edisp1.f
gfortran -c -Og -g -Wall edisp2.f
gfortran -c -Og -g -Wall edisp3.f
gfortran -c -Og -g -Wall egauss.f
gfortran -c -Og -g -Wall egauss1.f
gfortran -c -Og -g -Wall egauss2.f
gfortran -c -Og -g -Wall egauss3.f
gfortran -c -Og -g -Wall egeom.f
gfortran -c -Og -g -Wall egeom1.f
gfortran -c -Og -g -Wall egeom2.f
gfortran -c -Og -g -Wall egeom3.f
gfortran -c -Og -g -Wall ehal.f
gfortran -c -Og -g -Wall ehal1.f
gfortran -c -Og -g -Wall ehal2.f
gfortran -c -Og -g -Wall ehal3.f
gfortran -c -Og -g -Wall eimprop.f
gfortran -c -Og -g -Wall eimprop1.f
gfortran -c -Og -g -Wall eimprop2.f
gfortran -c -Og -g -Wall eimprop3.f
gfortran -c -Og -g -Wall eimptor.f
gfortran -c -Og -g -Wall eimptor1.f
gfortran -c -Og -g -Wall eimptor2.f
gfortran -c -Og -g -Wall eimptor3.f
gfortran -c -Og -g -Wall elj.f
gfortran -c -Og -g -Wall elj1.f
gfortran -c -Og -g -Wall elj2.f
gfortran -c -Og -g -Wall elj3.f
gfortran -c -Og -g -Wall embed.f
gfortran -c -Og -g -Wall emetal.f
gfortran -c -Og -g -Wall emetal1.f
gfortran -c -Og -g -Wall emetal2.f
gfortran -c -Og -g -Wall emetal3.f
gfortran -c -Og -g -Wall emm3hb.f
gfortran -c -Og -g -Wall emm3hb1.f
gfortran -c -Og -g -Wall emm3hb2.f
gfortran -c -Og -g -Wall emm3hb3.f
gfortran -c -Og -g -Wall empole.f
gfortran -c -Og -g -Wall empole1.f
gfortran -c -Og -g -Wall empole2.f
gfortran -c -Og -g -Wall empole3.f
gfortran -c -Og -g -Wall energy.f
gfortran -c -Og -g -Wall eopbend.f
gfortran -c -Og -g -Wall eopbend1.f
gfortran -c -Og -g -Wall eopbend2.f
gfortran -c -Og -g -Wall eopbend3.f
gfortran -c -Og -g -Wall eopdist.f
gfortran -c -Og -g -Wall eopdist1.f
gfortran -c -Og -g -Wall eopdist2.f
gfortran -c -Og -g -Wall eopdist3.f
gfortran -c -Og -g -Wall epitors.f
gfortran -c -Og -g -Wall epitors1.f
gfortran -c -Og -g -Wall epitors2.f
gfortran -c -Og -g -Wall epitors3.f
gfortran -c -Og -g -Wall epolar.f
gfortran -c -Og -g -Wall epolar1.f
gfortran -c -Og -g -Wall epolar2.f
gfortran -c -Og -g -Wall epolar3.f
gfortran -c -Og -g -Wall erepel.f
gfortran -c -Og -g -Wall erepel1.f
gfortran -c -Og -g -Wall erepel2.f
gfortran -c -Og -g -Wall erepel3.f
gfortran -c -Og -g -Wall erf.f
gfortran -c -Og -g -Wall erxnfld.f
gfortran -c -Og -g -Wall erxnfld1.f
gfortran -c -Og -g -Wall erxnfld2.f
gfortran -c -Og -g -Wall erxnfld3.f
gfortran -c -Og -g -Wall esolv.f
gfortran -c -Og -g -Wall esolv1.f
gfortran -c -Og -g -Wall esolv2.f
gfortran -c -Og -g -Wall esolv3.f
gfortran -c -Og -g -Wall estrbnd.f
gfortran -c -Og -g -Wall estrbnd1.f
gfortran -c -Og -g -Wall estrbnd2.f
gfortran -c -Og -g -Wall estrbnd3.f
gfortran -c -Og -g -Wall estrtor.f
gfortran -c -Og -g -Wall estrtor1.f
gfortran -c -Og -g -Wall estrtor2.f
gfortran -c -Og -g -Wall estrtor3.f
gfortran -c -Og -g -Wall etors.f
gfortran -c -Og -g -Wall etors1.f
gfortran -c -Og -g -Wall etors2.f
gfortran -c -Og -g -Wall etors3.f
gfortran -c -Og -g -Wall etortor.f
gfortran -c -Og -g -Wall etortor1.f
gfortran -c -Og -g -Wall etortor2.f
gfortran -c -Og -g -Wall etortor3.f
gfortran -c -Og -g -Wall eurey.f
gfortran -c -Og -g -Wall eurey1.f
gfortran -c -Og -g -Wall eurey2.f
gfortran -c -Og -g -Wall eurey3.f
gfortran -c -Og -g -Wall evcorr.f
gfortran -c -Og -g -Wall exfield.f
gfortran -c -Og -g -Wall extra.f
gfortran -c -Og -g -Wall extra1.f
gfortran -c -Og -g -Wall extra2.f
gfortran -c -Og -g -Wall extra3.f
gfortran -c -Og -g -Wall fatal.f
gfortran -c -Og -g -Wall fft3d.f
gfortran -c -Og -g -Wall fftpack.f
gfortran -c -Og -g -Wall field.f
gfortran -c -Og -g -Wall final.f
gfortran -c -Og -g -Wall findnuc.f
gfortran -c -Og -g -Wall findpro.f
gfortran -c -Og -g -Wall findseq.f
gfortran -c -Og -g -Wall flatten.f
gfortran -c -Og -g -Wall freefix.f
gfortran -c -Og -g -Wall freeunit.f
gfortran -c -Og -g -Wall gda.f
gfortran -c -Og -g -Wall geometry.f
gfortran -c -Og -g -Wall getarc.f
gfortran -c -Og -g -Wall getcart.f
gfortran -c -Og -g -Wall getdcd.f
gfortran -c -Og -g -Wall getfloat.f
gfortran -c -Og -g -Wall getint.f
gfortran -c -Og -g -Wall getkey.f
gfortran -c -Og -g -Wall getmol.f
gfortran -c -Og -g -Wall getmol2.f
gfortran -c -Og -g -Wall getnumb.f
gfortran -c -Og -g -Wall getpdb.f
gfortran -c -Og -g -Wall getprm.f
gfortran -c -Og -g -Wall getref.f
gfortran -c -Og -g -Wall getstring.f
gfortran -c -Og -g -Wall gettext.f
gfortran -c -Og -g -Wall getword.f
gfortran -c -Og -g -Wall getxyz.f
gfortran -c -Og -g -Wall ghmcstep.f
gfortran -c -Og -g -Wall gradient.f
gfortran -c -Og -g -Wall gradrgd.f
gfortran -c -Og -g -Wall gradrot.f
gfortran -c -Og -g -Wall groups.f
gfortran -c -Og -g -Wall grpline.f
gfortran -c -Og -g -Wall gyrate.f
gfortran -c -Og -g -Wall hessian.f
gfortran -c -Og -g -Wall hessrgd.f
gfortran -c -Og -g -Wall hessrot.f
gfortran -c -Og -g -Wall hybrid.f
gfortran -c -Og -g -Wall image.f
gfortran -c -Og -g -Wall impose.f
gfortran -c -Og -g -Wall induce.f
gfortran -c -Og -g -Wall inertia.f
gfortran -c -Og -g -Wall initatom.f
gfortran -c -Og -g -Wall initial.f
gfortran -c -Og -g -Wall initneck.f
gfortran -c -Og -g -Wall initprm.f
gfortran -c -Og -g -Wall initres.f
gfortran -c -Og -g -Wall initrot.f
gfortran -c -Og -g -Wall insert.f
gfortran -c -Og -g -Wall intedit.f
gfortran -c -Og -g -Wall intxyz.f
gfortran -c -Og -g -Wall invbeta.f
gfortran -c -Og -g -Wall invert.f
gfortran -c -Og -g -Wall jacobi.f
gfortran -c -Og -g -Wall kangang.f
gfortran -c -Og -g -Wall kangle.f
gfortran -c -Og -g -Wall kangtor.f
gfortran -c -Og -g -Wall katom.f
gfortran -c -Og -g -Wall kbond.f
gfortran -c -Og -g -Wall kcharge.f
gfortran -c -Og -g -Wall kchgflx.f
gfortran -c -Og -g -Wall kchgtrn.f
gfortran -c -Og -g -Wall kdipole.f
gfortran -c -Og -g -Wall kdisp.f
gfortran -c -Og -g -Wall kewald.f
gfortran -c -Og -g -Wall kexpol.f
gfortran -c -Og -g -Wall kextra.f
gfortran -c -Og -g -Wall kgeom.f
gfortran -c -Og -g -Wall kimprop.f
gfortran -c -Og -g -Wall kimptor.f
gfortran -c -Og -g -Wall kinetic.f
gfortran -c -Og -g -Wall kmetal.f
gfortran -c -Og -g -Wall kmpole.f
gfortran -c -Og -g -Wall kopbend.f
gfortran -c -Og -g -Wall kopdist.f
gfortran -c -Og -g -Wall korbit.f
gfortran -c -Og -g -Wall kpitors.f
gfortran -c -Og -g -Wall kpolar.f
gfortran -c -Og -g -Wall krepel.f
gfortran -c -Og -g -Wall ksolv.f
gfortran -c -Og -g -Wall kstrbnd.f
gfortran -c -Og -g -Wall kstrtor.f
gfortran -c -Og -g -Wall ktors.f
gfortran -c -Og -g -Wall ktortor.f
gfortran -c -Og -g -Wall kundrot.f
gfortran -c -Og -g -Wall kurey.f
gfortran -c -Og -g -Wall kvdw.f
gfortran -c -Og -g -Wall lattice.f
gfortran -c -Og -g -Wall lbfgs.f
gfortran -c -Og -g -Wall lights.f
gfortran -c -Og -g -Wall lusolve.f
gfortran -c -Og -g -Wall makeint.f
gfortran -c -Og -g -Wall makeref.f
gfortran -c -Og -g -Wall makexyz.f
gfortran -c -Og -g -Wall maxwell.f
gfortran -c -Og -g -Wall mdavg.f
gfortran -c -Og -g -Wall mdinit.f
gfortran -c -Og -g -Wall mdrest.f
gfortran -c -Og -g -Wall mdsave.f
gfortran -c -Og -g -Wall mdstat.f
gfortran -c -Og -g -Wall mechanic.f
gfortran -c -Og -g -Wall merge.f
gfortran -c -Og -g -Wall minimize.f
gfortran -c -Og -g -Wall minirot.f
gfortran -c -Og -g -Wall minrigid.f
gfortran -c -Og -g -Wall mol2xyz.f
gfortran -c -Og -g -Wall molecule.f
gfortran -c -Og -g -Wall molxyz.f
gfortran -c -Og -g -Wall moments.f
gfortran -c -Og -g -Wall monte.f
gfortran -c -Og -g -Wall mutate.f
gfortran -c -Og -g -Wall nblist.f
gfortran -c -Og -g -Wall neck.f
gfortran -c -Og -g -Wall newton.f
gfortran -c -Og -g -Wall newtrot.f
gfortran -c -Og -g -Wall nextarg.f
gfortran -c -Og -g -Wall nexttext.f
gfortran -c -Og -g -Wall nose.f
gfortran -c -Og -g -Wall nspline.f
gfortran -c -Og -g -Wall nucleic.f
gfortran -c -Og -g -Wall number.f
gfortran -c -Og -g -Wall numeral.f
gfortran -c -Og -g -Wall numgrad.f
gfortran -c -Og -g -Wall ocvm.f
gfortran -c -Og -g -Wall openend.f
gfortran -c -Og -g -Wall optimize.f
gfortran -c -Og -g -Wall optinit.f
gfortran -c -Og -g -Wall optirot.f
gfortran -c -Og -g -Wall optrigid.f
gfortran -c -Og -g -Wall optsave.f
gfortran -c -Og -g -Wall orbital.f
gfortran -c -Og -g -Wall orient.f
gfortran -c -Og -g -Wall orthog.f
gfortran -c -Og -g -Wall overlap.f
gfortran -c -Og -g -Wall path.f
gfortran -c -Og -g -Wall pdbxyz.f
gfortran -c -Og -g -Wall picalc.f
gfortran -c -Og -g -Wall pmestuf.f
gfortran -c -Og -g -Wall pmpb.f
gfortran -c -Og -g -Wall polarize.f
gfortran -c -Og -g -Wall poledit.f
gfortran -c -Og -g -Wall polymer.f
gfortran -c -Og -g -Wall potential.f
gfortran -c -Og -g -Wall predict.f
gfortran -c -Og -g -Wall pressure.f
gfortran -c -Og -g -Wall prmedit.f
gfortran -c -Og -g -Wall prmkey.f
gfortran -c -Og -g -Wall promo.f
gfortran -c -Og -g -Wall protein.f
gfortran -c -Og -g -Wall prtarc.f
gfortran -c -Og -g -Wall prtcif.f
gfortran -c -Og -g -Wall prtdyn.f
gfortran -c -Og -g -Wall prterr.f
gfortran -c -Og -g -Wall prtfrc.f
gfortran -c -Og -g -Wall prtint.f
gfortran -c -Og -g -Wall prtmol2.f
gfortran -c -Og -g -Wall prtpdb.f
gfortran -c -Og -g -Wall prtprm.f
gfortran -c -Og -g -Wall prtseq.f
gfortran -c -Og -g -Wall prtuind.f
gfortran -c -Og -g -Wall prtvel.f
gfortran -c -Og -g -Wall prtxyz.f
gfortran -c -Og -g -Wall pss.f
gfortran -c -Og -g -Wall pssrigid.f
gfortran -c -Og -g -Wall pssrot.f
gfortran -c -Og -g -Wall qrsolve.f
gfortran -c -Og -g -Wall quatfit.f
gfortran -c -Og -g -Wall radial.f
gfortran -c -Og -g -Wall random.f
gfortran -c -Og -g -Wall rattle.f
gfortran -c -Og -g -Wall readcart.f
gfortran -c -Og -g -Wall readcif.f
gfortran -c -Og -g -Wall readdcd.f
gfortran -c -Og -g -Wall readdyn.f
gfortran -c -Og -g -Wall readgau.f
gfortran -c -Og -g -Wall readgdma.f
gfortran -c -Og -g -Wall readint.f
gfortran -c -Og -g -Wall readmbis.f
gfortran -c -Og -g -Wall readmol.f
gfortran -c -Og -g -Wall readmol2.f
gfortran -c -Og -g -Wall readpdb.f
gfortran -c -Og -g -Wall readprm.f
gfortran -c -Og -g -Wall readseq.f
gfortran -c -Og -g -Wall readxyz.f
gfortran -c -Og -g -Wall replica.f
gfortran -c -Og -g -Wall respa.f
gfortran -c -Og -g -Wall rgdstep.f
gfortran -c -Og -g -Wall richmond.f
gfortran -c -Og -g -Wall rings.f
gfortran -c -Og -g -Wall rmsfit.f
gfortran -c -Og -g -Wall rotlist.f
gfortran -c -Og -g -Wall rotpole.f
gfortran -c -Og -g -Wall saddle.f
gfortran -c -Og -g -Wall scan.f
gfortran -c -Og -g -Wall sdstep.f
gfortran -c -Og -g -Wall search.f
gfortran -c -Og -g -Wall server.f
gfortran -c -Og -g -Wall setprm.f
gfortran -c -Og -g -Wall shakeup.f
gfortran -c -Og -g -Wall sigmoid.f
gfortran -c -Og -g -Wall simplex.f
gfortran -c -Og -g -Wall sktstuf.f
gfortran -c -Og -g -Wall sniffer.f
gfortran -c -Og -g -Wall sort.f
gfortran -c -Og -g -Wall spacefill.f
gfortran -c -Og -g -Wall spectrum.f
gfortran -c -Og -g -Wall square.f
gfortran -c -Og -g -Wall suffix.f
gfortran -c -Og -g -Wall superpose.f
gfortran -c -Og -g -Wall surface.f
gfortran -c -Og -g -Wall surfatom.f
gfortran -c -Og -g -Wall switch.f
gfortran -c -Og -g -Wall tcgstuf.f
gfortran -c -Og -g -Wall temper.f
gfortran -c -Og -g -Wall testgrad.f
gfortran -c -Og -g -Wall testhess.f
gfortran -c -Og -g -Wall testpair.f
gfortran -c -Og -g -Wall testpol.f
gfortran -c -Og -g -Wall testrot.f
gfortran -c -Og -g -Wall testsurf.f
gfortran -c -Og -g -Wall testvir.f
gfortran -c -Og -g -Wall tettors.f
gfortran -c -Og -g -Wall timer.f
gfortran -c -Og -g -Wall timerot.f
gfortran -c -Og -g -Wall tncg.f
gfortran -c -Og -g -Wall torphase.f
gfortran -c -Og -g -Wall torque.f
gfortran -c -Og -g -Wall torsfit.f
gfortran -c -Og -g -Wall torsions.f
gfortran -c -Og -g -Wall trimtext.f
gfortran -c -Og -g -Wall tritors.f
gfortran -c -Og -g -Wall unionball.f
gfortran -c -Og -g -Wall unitcell.f
gfortran -c -Og -g -Wall valence.f
gfortran -c -Og -g -Wall verlet.f
gfortran -c -Og -g -Wall version.f
gfortran -c -Og -g -Wall vibbig.f
gfortran -c -Og -g -Wall vibrate.f
gfortran -c -Og -g -Wall vibrot.f
gfortran -c -Og -g -Wall volume.f
gfortran -c -Og -g -Wall xtalfit.f
gfortran -c -Og -g -Wall xtalmin.f
gfortran -c -Og -g -Wall xyzatm.f
gfortran -c -Og -g -Wall xyzedit.f
gfortran -c -Og -g -Wall xyzint.f
gfortran -c -Og -g -Wall xyzmol2.f
gfortran -c -Og -g -Wall xyzpdb.f
gfortran -c -Og -g -Wall zatom.f
