#
#
#  #################################################################
#  ##                                                             ##
#  ##  debug.make  --  compile the TINKER routines for debugging  ##
#  ##               (GNU gfortran for MacOS Version)              ##
#  ##                                                             ##
#  #################################################################
#
#
#  compile all the modules; "sizes" must be first since it is used
#  to set static array dimensions in many of the other modules
#
#
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized sizes.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized action.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized align.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized analyz.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized angang.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized angbnd.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized angpot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized angtor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized argue.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ascii.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized atmlst.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized atomid.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized atoms.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized bath.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized bitor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized bndpot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized bndstr.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized bound.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized boxes.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized cell.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized charge.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized chgpot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized chrono.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized chunks.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized couple.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized deriv.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized dipole.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized disgeo.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized dma.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized domega.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized energi.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ewald.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized faces.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized fft.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized fields.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized files.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized fracs.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized freeze.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized gkstuf.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized group.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized hescut.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized hessn.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized hpmf.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized improp.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized imptor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized inform.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized inter.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized iounit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kanang.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kangs.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kantor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized katoms.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kbonds.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kchrge.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kdipol.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized keys.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized khbond.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kiprop.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kitors.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kmulti.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kopbnd.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kopdst.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized korbs.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kpitor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kpolr.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kstbnd.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ksttor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ktorsn.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ktrtor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kurybr.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kvdwpr.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kvdws.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized light.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized limits.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized linmin.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized math.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized mdstuf.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized merck.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized minima.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized molcul.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized moldyn.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized moment.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized mplpot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized mpole.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized mrecip.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized mutant.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized neigh.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized nonpol.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized nucleo.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized omega.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized opbend.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized opdist.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized openmp.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized orbits.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized output.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized params.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized paths.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized pbstuf.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized pdb.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized phipsi.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized piorbs.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized pistuf.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized pitors.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized pme.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized polar.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized polgrp.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized polpot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized potent.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized potfit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized precis.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ptable.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized qmstuf.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized refer.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized resdue.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized restrn.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized rgddyn.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized rigid.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ring.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized rotbnd.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized rxnfld.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized rxnpot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized scales.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized sequen.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized shunt.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized socket.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized solute.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized stodyn.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized strbnd.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized strtor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized syntrn.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized tarray.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized titles.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized torpot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized tors.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized tortor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized tree.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized units.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized uprior.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized urey.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized urypot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized usage.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized usolve.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized valfit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized vdw.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized vdwpot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized vibs.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized virial.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized warp.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized xtals.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized zclose.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized zcoord.f
#
#  now compile separately each of the Fortran source files
#
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized active.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized alchemy.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized analysis.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized analyze.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized angles.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized anneal.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized archive.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized attach.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized bar.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized basefile.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized beeman.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized bicubic.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized bitors.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized bonds.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized born.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized bounds.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized bussi.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized calendar.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized center.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized chkpole.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized chkring.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized chkxyz.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized cholesky.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized clock.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized cluster.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized column.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized command.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized connect.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized connolly.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized control.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized correlate.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized crystal.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized cspline.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized cutoffs.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized deflate.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized delete.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized diagq.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized diffeq.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized diffuse.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized distgeom.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized document.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized dynamic.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eangang.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eangang1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eangang2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eangang3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eangle.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eangle1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eangle2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eangle3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eangtor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eangtor1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eangtor2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eangtor3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ebond.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ebond1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ebond2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ebond3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ebuck.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ebuck1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ebuck2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ebuck3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized echarge.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized echarge1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized echarge2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized echarge3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized echgdpl.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized echgdpl1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized echgdpl2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized echgdpl3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized edipole.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized edipole1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized edipole2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized edipole3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized egauss.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized egauss1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized egauss2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized egauss3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized egeom.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized egeom1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized egeom2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized egeom3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ehal.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ehal1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ehal2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ehal3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eimprop.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eimprop1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eimprop2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eimprop3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eimptor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eimptor1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eimptor2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eimptor3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized elj.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized elj1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized elj2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized elj3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized embed.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized emetal.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized emetal1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized emetal2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized emetal3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized emm3hb.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized emm3hb1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized emm3hb2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized emm3hb3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized empole.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized empole1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized empole2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized empole3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized energy.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eopbend.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eopbend1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eopbend2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eopbend3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eopdist.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eopdist1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eopdist2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eopdist3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized epitors.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized epitors1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized epitors2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized epitors3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized epolar.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized epolar1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized epolar2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized epolar3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized erf.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized erxnfld.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized erxnfld1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized erxnfld2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized erxnfld3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized esolv.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized esolv1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized esolv2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized esolv3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized estrbnd.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized estrbnd1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized estrbnd2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized estrbnd3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized estrtor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized estrtor1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized estrtor2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized estrtor3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized etors.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized etors1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized etors2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized etors3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized etortor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized etortor1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized etortor2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized etortor3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eurey.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eurey1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eurey2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized eurey3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized evcorr.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized extra.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized extra1.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized extra2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized extra3.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized fatal.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized fft3d.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized fftpack.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized field.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized final.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized flatten.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized freeunit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized gda.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized geometry.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized getint.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized getkey.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized getmol.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized getmol2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized getnumb.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized getpdb.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized getprm.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized getref.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized getstring.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized gettext.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized getword.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized getxyz.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ghmcstep.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized gradient.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized gradrgd.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized gradrot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized groups.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized grpline.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized gyrate.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized hessian.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized hessrgd.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized hessrot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized hybrid.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized image.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized impose.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized induce.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized inertia.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized initatom.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized initial.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized initprm.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized initres.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized initrot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized insert.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized intedit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized intxyz.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized invbeta.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized invert.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized jacobi.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kangang.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kangle.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kangtor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized katom.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kbond.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kcharge.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kdipole.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kewald.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kextra.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kgeom.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kimprop.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kimptor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kinetic.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kmetal.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kmpole.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kopbend.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kopdist.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized korbit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kpitors.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kpolar.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ksolv.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kstrbnd.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kstrtor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ktors.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ktortor.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kurey.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized kvdw.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized lattice.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized lbfgs.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized lights.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized makeint.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized makeref.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized makexyz.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized maxwell.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized mdinit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized mdrest.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized mdsave.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized mdstat.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized mechanic.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized merge.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized minimize.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized minirot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized minrigid.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized molecule.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized molxyz.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized moments.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized monte.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized mutate.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized nblist.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized newton.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized newtrot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized nextarg.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized nexttext.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized nose.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized nspline.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized nucleic.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized number.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized numeral.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized numgrad.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized ocvm.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized openend.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized optimize.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized optirot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized optrigid.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized optsave.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized orbital.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized orient.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized orthog.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized overlap.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized path.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized pdbxyz.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized picalc.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized pmestuff.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized pmpb.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized polarize.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized poledit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized polymer.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized potential.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized precise.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized pressure.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized prmedit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized prmkey.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized promo.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized protein.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized prtdyn.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized prterr.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized prtint.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized prtmol2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized prtpdb.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized prtprm.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized prtseq.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized prtxyz.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized pss.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized pssrigid.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized pssrot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized qrfact.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized quatfit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized radial.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized random.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized rattle.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized readdyn.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized readgau.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized readint.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized readmol.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized readmol2.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized readpdb.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized readprm.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized readseq.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized readxyz.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized replica.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized respa.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized rgdstep.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized rings.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized rmsfit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized rotlist.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized rotpole.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized saddle.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized scan.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized sdstep.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized search.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized server.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized shakeup.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized sigmoid.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized simplex.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized sktstuff.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized sniffer.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized sort.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized spacefill.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized spectrum.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized square.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized suffix.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized superpose.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized surface.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized surfatom.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized switch.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized sybylxyz.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized temper.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized testgrad.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized testhess.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized testpair.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized testpol.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized testrot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized timer.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized timerot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized tncg.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized torphase.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized torque.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized torsfit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized torsions.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized trimtext.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized unitcell.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized valence.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized verlet.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized version.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized vibbig.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized vibrate.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized vibrot.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized volume.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized xtalfit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized xtalmin.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized xyzatm.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized xyzedit.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized xyzint.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized xyzpdb.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized xyzsybyl.f
gfortran -c -Og -g -fbacktrace -Warray-bounds -Wmaybe-uninitialized zatom.f
