#
#
#  ################################################################
#  ##                                                            ##
#  ##  convert.make  --  conversion of TINKER from Fortran to C  ##
#  ##                   (Generic Unix Version)                   ##
#  ##                                                            ##
#  ################################################################
#
#
f2c  -A -s  active.f
f2c  -A -s  alchemy.f
f2c  -A -s  analysis.f
f2c  -A -s  analyze.f
f2c  -A -s  angles.f
f2c  -A -s  anneal.f
f2c  -A -s  archive.f
f2c  -A -s  attach.f
f2c  -A -s  basefile.f
f2c  -A -s  beeman.f
f2c  -A -s  bicubic.f
f2c  -A -s  bitors.f
f2c  -A -s  bonds.f
f2c  -A -s  born.f
f2c  -A -s  bounds.f
f2c  -A -s  bspline.f
f2c  -A -s  center.f
f2c  -A -s  chkpole.f
f2c  -A -s  chkring.f
f2c  -A -s  chkxyz.f
f2c  -A -s  cholesky.f
f2c  -A -s  cluster.f
f2c  -A -s  column.f
f2c  -A -s  command.f
f2c  -A -s  connect.f
f2c  -A -s  connolly.f
f2c  -A -s  control.f
f2c  -A -s  correlate.f
f2c  -A -s  crystal.f
f2c  -A -s  cspline.f
f2c  -A -s  cutoffs.f
f2c  -A -s  deflate.f
f2c  -A -s  delete.f
f2c  -A -s  diagq.f
f2c  -A -s  diffeq.f
f2c  -A -s  diffuse.f
f2c  -A -s  distgeom.f
f2c  -A -s  document.f
f2c  -A -s  dynamic.f
f2c  -A -s  eangang.f
f2c  -A -s  eangang1.f
f2c  -A -s  eangang2.f
f2c  -A -s  eangang3.f
f2c  -A -s  eangle.f
f2c  -A -s  eangle1.f
f2c  -A -s  eangle2.f
f2c  -A -s  eangle3.f
f2c  -A -s  ebond.f
f2c  -A -s  ebond1.f
f2c  -A -s  ebond2.f
f2c  -A -s  ebond3.f
f2c  -A -s  ebuck.f
f2c  -A -s  ebuck1.f
f2c  -A -s  ebuck2.f
f2c  -A -s  ebuck3.f
f2c  -A -s  echarge.f
f2c  -A -s  echarge1.f
f2c  -A -s  echarge2.f
f2c  -A -s  echarge3.f
f2c  -A -s  echgdpl.f
f2c  -A -s  echgdpl1.f
f2c  -A -s  echgdpl2.f
f2c  -A -s  echgdpl3.f
f2c  -A -s  edipole.f
f2c  -A -s  edipole1.f
f2c  -A -s  edipole2.f
f2c  -A -s  edipole3.f
f2c  -A -s  egauss.f
f2c  -A -s  egauss1.f
f2c  -A -s  egauss2.f
f2c  -A -s  egauss3.f
f2c  -A -s  egeom.f
f2c  -A -s  egeom1.f
f2c  -A -s -Nn1000  egeom2.f
f2c  -A -s  egeom3.f
f2c  -A -s  ehal.f
f2c  -A -s  ehal1.f
f2c  -A -s  ehal2.f
f2c  -A -s  ehal3.f
f2c  -A -s  eimprop.f
f2c  -A -s  eimprop1.f
f2c  -A -s  eimprop2.f
f2c  -A -s  eimprop3.f
f2c  -A -s  eimptor.f
f2c  -A -s  eimptor1.f
f2c  -A -s  eimptor2.f
f2c  -A -s  eimptor3.f
f2c  -A -s  elj.f
f2c  -A -s  elj1.f
f2c  -A -s  elj2.f
f2c  -A -s  elj3.f
f2c  -A -s  embed.f
f2c  -A -s  emetal.f
f2c  -A -s  emetal1.f
f2c  -A -s  emetal2.f
f2c  -A -s  emetal3.f
f2c  -A -s  emm3hb.f
f2c  -A -s  emm3hb1.f
f2c  -A -s  emm3hb2.f
f2c  -A -s  emm3hb3.f
f2c  -A -s  empole.f
f2c  -A -s -Nn 1000  empole1.f
f2c  -A -s  empole2.f
f2c  -A -s  empole3.f
f2c  -A -s  energy.f
f2c  -A -s  eopbend.f
f2c  -A -s  eopbend1.f
f2c  -A -s  eopbend2.f
f2c  -A -s  eopbend3.f
f2c  -A -s  eopdist.f
f2c  -A -s  eopdist1.f
f2c  -A -s  eopdist2.f
f2c  -A -s  eopdist3.f
f2c  -A -s  epitors.f
f2c  -A -s  epitors1.f
f2c  -A -s  epitors2.f
f2c  -A -s  epitors3.f
f2c  -A -s  erf.f
f2c  -A -s  erxnfld.f
f2c  -A -s  erxnfld1.f
f2c  -A -s  erxnfld2.f
f2c  -A -s  erxnfld3.f
f2c  -A -s  esolv.f
f2c  -A -s  esolv1.f
f2c  -A -s  esolv2.f
f2c  -A -s  esolv3.f
f2c  -A -s  estrbnd.f
f2c  -A -s  estrbnd1.f
f2c  -A -s  estrbnd2.f
f2c  -A -s  estrbnd3.f
f2c  -A -s  estrtor.f
f2c  -A -s  estrtor1.f
f2c  -A -s  estrtor2.f
f2c  -A -s  estrtor3.f
f2c  -A -s  etors.f
f2c  -A -s  etors1.f
f2c  -A -s  etors2.f
f2c  -A -s  etors3.f
f2c  -A -s  etortor.f
f2c  -A -s  etortor1.f
f2c  -A -s -Nn1000  etortor2.f
f2c  -A -s  etortor3.f
f2c  -A -s  eurey.f
f2c  -A -s  eurey1.f
f2c  -A -s  eurey2.f
f2c  -A -s  eurey3.f
f2c  -A -s  extra.f
f2c  -A -s  extra1.f
f2c  -A -s  extra2.f
f2c  -A -s  extra3.f
f2c  -A -s  fatal.f
f2c  -A -s  fft3d.f
f2c  -A -s  field.f
f2c  -A -s  final.f
f2c  -A -s  flatten.f
f2c  -A -s  freeunit.f
f2c  -A -s  gda.f
f2c  -A -s  geometry.f
f2c  -A -s  getint.f
f2c  -A -s  getkey.f
f2c  -A -s  getmol2.f
f2c  -A -s  getnumb.f
f2c  -A -s  getpdb.f
f2c  -A -s  getprm.f
f2c  -A -s  getref.f
f2c  -A -s  getstring.f
f2c  -A -s  gettext.f
f2c  -A -s  getword.f
f2c  -A -s  getxyz.f
f2c  -A -s  gradient.f
f2c  -A -s  gradrgd.f
f2c  -A -s  gradrot.f
f2c  -A -s  groups.f
f2c  -A -s  grpline.f
f2c  -A -s  gyrate.f
f2c  -A -s  hessian.f
f2c  -A -s  hessrgd.f
f2c  -A -s  hessrot.f
f2c  -A -s  hybrid.f
f2c  -A -s  image.f
f2c  -A -s  impose.f
f2c  -A -s  induce.f
f2c  -A -s  inertia.f
f2c  -A -s  initial.f
f2c  -A -s  initprm.f
f2c  -A -s  initres.f
f2c  -A -s  initrot.f
f2c  -A -s  insert.f
f2c  -A -s  intedit.f
f2c  -A -s  intxyz.f
f2c  -A -s  invbeta.f
f2c  -A -s  invert.f
f2c  -A -s  jacobi.f
f2c  -A -s  kangang.f
f2c  -A -s  kangle.f
f2c  -A -s  katom.f
f2c  -A -s  kbond.f
f2c  -A -s  kcharge.f
f2c  -A -s  kdipole.f
f2c  -A -s  kewald.f
f2c  -A -s  kgeom.f
f2c  -A -s  kimprop.f
f2c  -A -s  kimptor.f
f2c  -A -s  kinetic.f
f2c  -A -s  kmetal.f
f2c  -A -s  kmpole.f
f2c  -A -s  kopbend.f
f2c  -A -s  kopdist.f
f2c  -A -s  korbit.f
f2c  -A -s  kpitors.f
f2c  -A -s  kpolar.f
f2c  -A -s  ksolv.f
f2c  -A -s  kstrbnd.f
f2c  -A -s  kstrtor.f
f2c  -A -s  ktors.f
f2c  -A -s  ktortor.f
f2c  -A -s  kurey.f
f2c  -A -s  kvdw.f
f2c  -A -s  lattice.f
f2c  -A -s  lbfgs.f
f2c  -A -s  lights.f
f2c  -A -s  makeint.f
f2c  -A -s  makepdb.f
f2c  -A -s  makeref.f
f2c  -A -s  makexyz.f
f2c  -A -s  maxwell.f
f2c  -A -s  mdinit.f
f2c  -A -s  mdrest.f
f2c  -A -s  mdsave.f
f2c  -A -s  mdstat.f
f2c  -A -s  mechanic.f
f2c  -A -s  merge.f
f2c  -A -s  minimize.f
f2c  -A -s  minirot.f
f2c  -A -s  minrigid.f
f2c  -A -s  molecule.f
f2c  -A -s  moments.f
f2c  -A -s  monte.f
f2c  -A -s  mutate.f
f2c  -A -s  nblist.f
f2c  -A -s  newton.f
f2c  -A -s  newtrot.f
f2c  -A -s  nextarg.f
f2c  -A -s  nexttext.f
f2c  -A -s  nspline.f
f2c  -A -s -NL400  nucleic.f
f2c  -A -s  number.f
f2c  -A -s  numeral.f
f2c  -A -s  numgrad.f
f2c  -A -s  ocvm.f
f2c  -A -s  openend.f
f2c  -A -s  optimize.f
f2c  -A -s  optirot.f
f2c  -A -s  optrigid.f
f2c  -A -s  optsave.f
f2c  -A -s  orbital.f
f2c  -A -s  orient.f
f2c  -A -s  orthog.f
f2c  -A -s  overlap.f
f2c  -A -s  path.f
f2c  -A -s -NL400  pdbxyz.f
f2c  -A -s  piscf.f
f2c  -A -s  pmepol.f
f2c  -A -s  pmpb.f
f2c  -A -s  polarize.f
f2c  -A -s  poledit.f
f2c  -A -s  polymer.f
f2c  -A -s  potential.f
f2c  -A -s  precise.f
f2c  -A -s  pressure.f
f2c  -A -s  prmedit.f
f2c  -A -s  prmkey.f
f2c  -A -s  promo.f
f2c  -A -s -NL400  protein.f
f2c  -A -s  prtdyn.f
f2c  -A -s  prterr.f
f2c  -A -s  prtint.f
f2c  -A -s  prtmol2.f
f2c  -A -s  prtpdb.f
f2c  -A -s  prtprm.f
f2c  -A -s  prtseq.f
f2c  -A -s  prtxyz.f
f2c  -A -s  pss.f
f2c  -A -s  pssrigid.f
f2c  -A -s  pssrot.f
f2c  -A -s  quatfit.f
f2c  -A -s  radial.f
f2c  -A -s  random.f
f2c  -A -s  rattle.f
f2c  -A -s  readdyn.f
f2c  -A -s  readgau.f
f2c  -A -s  readint.f
f2c  -A -s  readmol2.f
f2c  -A -s  readpdb.f
f2c  -A -s  readprm.f
f2c  -A -s  readseq.f
f2c  -A -s  readxyz.f
f2c  -A -s  replica.f
f2c  -A -s  rgdstep.f
f2c  -A -s  rings.f
f2c  -A -s  rmsfit.f
f2c  -A -s  rotlist.f
f2c  -A -s  rotpole.f
f2c  -A -s  saddle.f
f2c  -A -s  scan.f
f2c  -A -s  sdstep.f
f2c  -A -s  search.f
f2c  -A -s  server.f
f2c  -A -s  shakeup.f
f2c  -A -s  sigmoid.f
f2c  -A -s  sktstuff.f
f2c  -A -s  sniffer.f
f2c  -A -s  sort.f
f2c  -A -s  spacefill.f
f2c  -A -s  spectrum.f
f2c  -A -s  square.f
f2c  -A -s  suffix.f
f2c  -A -s  superpose.f
f2c  -A -s  surface.f
f2c  -A -s  surfatom.f
f2c  -A -s  switch.f
f2c  -A -s  sybylxyz.f
f2c  -A -s  temper.f
f2c  -A -s  testgrad.f
f2c  -A -s  testhess.f
f2c  -A -s  testpair.f
f2c  -A -s  testrot.f
f2c  -A -s  timer.f
f2c  -A -s  timerot.f
f2c  -A -s  tncg.f
f2c  -A -s  torphase.f
f2c  -A -s  torque.f
f2c  -A -s  torsions.f
f2c  -A -s  trimtext.f
f2c  -A -s  unitcell.f
f2c  -A -s  valence.f
f2c  -A -s  verlet.f
f2c  -A -s  version.f
f2c  -A -s  vibbig.f
f2c  -A -s  vibrate.f
f2c  -A -s  vibrot.f
f2c  -A -s  volume.f
f2c  -A -s  xtalfit.f
f2c  -A -s  xtalmin.f
f2c  -A -s  xyzatm.f
f2c  -A -s  xyzedit.f
f2c  -A -s  xyzint.f
f2c  -A -s  xyzpdb.f
f2c  -A -s  xyzsybyl.f
f2c  -A -s  zatom.f
