#
#
#  ############################################################
#  ##                                                        ##
#  ##  compile.make  --  compile each of the TINKER modules  ##
#  ##            (Windows/Cygwin/GNU g77 Version)            ##
#  ##                                                        ##
#  ############################################################
#
#
g77 -c -O3 -ffast-math -mno-cygwin active.f
g77 -c -O3 -ffast-math -mno-cygwin alchemy.f
g77 -c -O3 -ffast-math -mno-cygwin analysis.f
g77 -c -O3 -ffast-math -mno-cygwin analyze.f
g77 -c -O3 -ffast-math -mno-cygwin angles.f
g77 -c -O3 -ffast-math -mno-cygwin anneal.f
g77 -c -O3 -ffast-math -mno-cygwin archive.f
g77 -c -O3 -ffast-math -mno-cygwin attach.f
g77 -c -O3 -ffast-math -mno-cygwin basefile.f
g77 -c -O3 -ffast-math -mno-cygwin beeman.f
g77 -c -O3 -ffast-math -mno-cygwin bicubic.f
g77 -c -O3 -ffast-math -mno-cygwin bitors.f
g77 -c -O3 -ffast-math -mno-cygwin bonds.f
g77 -c -O3 -ffast-math -mno-cygwin born.f
g77 -c -O3 -ffast-math -mno-cygwin bounds.f
g77 -c -O3 -ffast-math -mno-cygwin calendar.f
g77 -c -O3 -ffast-math -mno-cygwin center.f
g77 -c -O3 -ffast-math -mno-cygwin chkpole.f
g77 -c -O3 -ffast-math -mno-cygwin chkring.f
g77 -c -O3 -ffast-math -mno-cygwin chkxyz.f
g77 -c -O3 -ffast-math -mno-cygwin cholesky.f
g77 -c -O3 -ffast-math -mno-cygwin clock.f
g77 -c -O3 -ffast-math -mno-cygwin cluster.f
g77 -c -O3 -ffast-math -mno-cygwin column.f
g77 -c -O3 -ffast-math -mno-cygwin command.f
g77 -c -O3 -ffast-math -mno-cygwin connect.f
g77 -c -O3 -ffast-math -mno-cygwin connolly.f
g77 -c -O3 -ffast-math -mno-cygwin control.f
g77 -c -O3 -ffast-math -mno-cygwin correlate.f
g77 -c -O3 -ffast-math -mno-cygwin crystal.f
g77 -c -O3 -ffast-math -mno-cygwin cspline.f
g77 -c -O3 -ffast-math -mno-cygwin cutoffs.f
g77 -c -O3 -ffast-math -mno-cygwin deflate.f
g77 -c -O3 -ffast-math -mno-cygwin delete.f
g77 -c -O3 -ffast-math -mno-cygwin diagq.f
g77 -c -O3 -ffast-math -mno-cygwin diffeq.f
g77 -c -O3 -ffast-math -mno-cygwin diffuse.f
g77 -c -O3 -ffast-math -mno-cygwin distgeom.f
g77 -c -O3 -ffast-math -mno-cygwin document.f
g77 -c -O3 -ffast-math -mno-cygwin dynamic.f
g77 -c -O3 -ffast-math -mno-cygwin eangang.f
g77 -c -O3 -ffast-math -mno-cygwin eangang1.f
g77 -c -O3 -ffast-math -mno-cygwin eangang2.f
g77 -c -O3 -ffast-math -mno-cygwin eangang3.f
g77 -c -O3 -ffast-math -mno-cygwin eangle.f
g77 -c -O3 -ffast-math -mno-cygwin eangle1.f
g77 -c -O3 -ffast-math -mno-cygwin eangle2.f
g77 -c -O3 -ffast-math -mno-cygwin eangle3.f
g77 -c -O3 -ffast-math -mno-cygwin ebond.f
g77 -c -O3 -ffast-math -mno-cygwin ebond1.f
g77 -c -O3 -ffast-math -mno-cygwin ebond2.f
g77 -c -O3 -ffast-math -mno-cygwin ebond3.f
g77 -c -O3 -ffast-math -mno-cygwin ebuck.f
g77 -c -O3 -ffast-math -mno-cygwin ebuck1.f
g77 -c -O3 -ffast-math -mno-cygwin ebuck2.f
g77 -c -O3 -ffast-math -mno-cygwin ebuck3.f
g77 -c -O3 -ffast-math -mno-cygwin echarge.f
g77 -c -O3 -ffast-math -mno-cygwin echarge1.f
g77 -c -O3 -ffast-math -mno-cygwin echarge2.f
g77 -c -O3 -ffast-math -mno-cygwin echarge3.f
g77 -c -O3 -ffast-math -mno-cygwin echgdpl.f
g77 -c -O3 -ffast-math -mno-cygwin echgdpl1.f
g77 -c -O3 -ffast-math -mno-cygwin echgdpl2.f
g77 -c -O3 -ffast-math -mno-cygwin echgdpl3.f
g77 -c -O3 -ffast-math -mno-cygwin edipole.f
g77 -c -O3 -ffast-math -mno-cygwin edipole1.f
g77 -c -O3 -ffast-math -mno-cygwin edipole2.f
g77 -c -O3 -ffast-math -mno-cygwin edipole3.f
g77 -c -O3 -ffast-math -mno-cygwin egauss.f
g77 -c -O3 -ffast-math -mno-cygwin egauss1.f
g77 -c -O3 -ffast-math -mno-cygwin egauss2.f
g77 -c -O3 -ffast-math -mno-cygwin egauss3.f
g77 -c -O3 -ffast-math -mno-cygwin egeom.f
g77 -c -O3 -ffast-math -mno-cygwin egeom1.f
g77 -c -O3 -ffast-math -mno-cygwin egeom2.f
g77 -c -O3 -ffast-math -mno-cygwin egeom3.f
g77 -c -O3 -ffast-math -mno-cygwin ehal.f
g77 -c -O3 -ffast-math -mno-cygwin ehal1.f
g77 -c -O3 -ffast-math -mno-cygwin ehal2.f
g77 -c -O3 -ffast-math -mno-cygwin ehal3.f
g77 -c -O3 -ffast-math -mno-cygwin eimprop.f
g77 -c -O3 -ffast-math -mno-cygwin eimprop1.f
g77 -c -O3 -ffast-math -mno-cygwin eimprop2.f
g77 -c -O3 -ffast-math -mno-cygwin eimprop3.f
g77 -c -O3 -ffast-math -mno-cygwin eimptor.f
g77 -c -O3 -ffast-math -mno-cygwin eimptor1.f
g77 -c -O3 -ffast-math -mno-cygwin eimptor2.f
g77 -c -O3 -ffast-math -mno-cygwin eimptor3.f
g77 -c -O3 -ffast-math -mno-cygwin elj.f
g77 -c -O3 -ffast-math -mno-cygwin elj1.f
g77 -c -O3 -ffast-math -mno-cygwin elj2.f
g77 -c -O3 -ffast-math -mno-cygwin elj3.f
g77 -c -O3 -ffast-math -mno-cygwin embed.f
g77 -c -O3 -ffast-math -mno-cygwin emetal.f
g77 -c -O3 -ffast-math -mno-cygwin emetal1.f
g77 -c -O3 -ffast-math -mno-cygwin emetal2.f
g77 -c -O3 -ffast-math -mno-cygwin emetal3.f
g77 -c -O3 -ffast-math -mno-cygwin emm3hb.f
g77 -c -O3 -ffast-math -mno-cygwin emm3hb1.f
g77 -c -O3 -ffast-math -mno-cygwin emm3hb2.f
g77 -c -O3 -ffast-math -mno-cygwin emm3hb3.f
g77 -c -O3 -ffast-math -mno-cygwin empole.f
g77 -c -O3 -ffast-math -mno-cygwin empole1.f
g77 -c -O3 -ffast-math -mno-cygwin empole2.f
g77 -c -O3 -ffast-math -mno-cygwin empole3.f
g77 -c -O3 -ffast-math -mno-cygwin energy.f
g77 -c -O3 -ffast-math -mno-cygwin eopbend.f
g77 -c -O3 -ffast-math -mno-cygwin eopbend1.f
g77 -c -O3 -ffast-math -mno-cygwin eopbend2.f
g77 -c -O3 -ffast-math -mno-cygwin eopbend3.f
g77 -c -O3 -ffast-math -mno-cygwin eopdist.f
g77 -c -O3 -ffast-math -mno-cygwin eopdist1.f
g77 -c -O3 -ffast-math -mno-cygwin eopdist2.f
g77 -c -O3 -ffast-math -mno-cygwin eopdist3.f
g77 -c -O3 -ffast-math -mno-cygwin epitors.f
g77 -c -O3 -ffast-math -mno-cygwin epitors1.f
g77 -c -O3 -ffast-math -mno-cygwin epitors2.f
g77 -c -O3 -ffast-math -mno-cygwin epitors3.f
g77 -c -O3 -ffast-math -mno-cygwin erf.f
g77 -c -O3 -ffast-math -mno-cygwin erxnfld.f
g77 -c -O3 -ffast-math -mno-cygwin erxnfld1.f
g77 -c -O3 -ffast-math -mno-cygwin erxnfld2.f
g77 -c -O3 -ffast-math -mno-cygwin erxnfld3.f
g77 -c -O3 -ffast-math -mno-cygwin esolv.f
g77 -c -O3 -ffast-math -mno-cygwin esolv1.f
g77 -c -O3 -ffast-math -mno-cygwin esolv2.f
g77 -c -O3 -ffast-math -mno-cygwin esolv3.f
g77 -c -O3 -ffast-math -mno-cygwin estrbnd.f
g77 -c -O3 -ffast-math -mno-cygwin estrbnd1.f
g77 -c -O3 -ffast-math -mno-cygwin estrbnd2.f
g77 -c -O3 -ffast-math -mno-cygwin estrbnd3.f
g77 -c -O3 -ffast-math -mno-cygwin estrtor.f
g77 -c -O3 -ffast-math -mno-cygwin estrtor1.f
g77 -c -O3 -ffast-math -mno-cygwin estrtor2.f
g77 -c -O3 -ffast-math -mno-cygwin estrtor3.f
g77 -c -O3 -ffast-math -mno-cygwin etors.f
g77 -c -O3 -ffast-math -mno-cygwin etors1.f
g77 -c -O3 -ffast-math -mno-cygwin etors2.f
g77 -c -O3 -ffast-math -mno-cygwin etors3.f
g77 -c -O3 -ffast-math -mno-cygwin etortor.f
g77 -c -O3 -ffast-math -mno-cygwin etortor1.f
g77 -c -O3 -ffast-math -mno-cygwin etortor2.f
g77 -c -O3 -ffast-math -mno-cygwin etortor3.f
g77 -c -O3 -ffast-math -mno-cygwin eurey.f
g77 -c -O3 -ffast-math -mno-cygwin eurey1.f
g77 -c -O3 -ffast-math -mno-cygwin eurey2.f
g77 -c -O3 -ffast-math -mno-cygwin eurey3.f
g77 -c -O3 -ffast-math -mno-cygwin evcorr.f
g77 -c -O3 -ffast-math -mno-cygwin extra.f
g77 -c -O3 -ffast-math -mno-cygwin extra1.f
g77 -c -O3 -ffast-math -mno-cygwin extra2.f
g77 -c -O3 -ffast-math -mno-cygwin extra3.f
g77 -c -O3 -ffast-math -mno-cygwin fatal.f
g77 -c -O3 -ffast-math -mno-cygwin fft3d.f
g77 -c -O3 -ffast-math -mno-cygwin fftpack.f
g77 -c -O3 -ffast-math -mno-cygwin field.f
g77 -c -O3 -ffast-math -mno-cygwin final.f
g77 -c -O3 -ffast-math -mno-cygwin flatten.f
g77 -c -O3 -ffast-math -mno-cygwin freeunit.f
g77 -c -O3 -ffast-math -mno-cygwin gda.f
g77 -c -O3 -ffast-math -mno-cygwin geometry.f
g77 -c -O3 -ffast-math -mno-cygwin getime.f
g77 -c -O3 -ffast-math -mno-cygwin getint.f
g77 -c -O3 -ffast-math -mno-cygwin getkey.f
g77 -c -O3 -ffast-math -mno-cygwin getmol2.f
g77 -c -O3 -ffast-math -mno-cygwin getnumb.f
g77 -c -O3 -ffast-math -mno-cygwin getpdb.f
g77 -c -O3 -ffast-math -mno-cygwin getprm.f
g77 -c -O3 -ffast-math -mno-cygwin getref.f
g77 -c -O3 -ffast-math -mno-cygwin getstring.f
g77 -c -O3 -ffast-math -mno-cygwin gettext.f
g77 -c -O3 -ffast-math -mno-cygwin getword.f
g77 -c -O3 -ffast-math -mno-cygwin getxyz.f
g77 -c -O3 -ffast-math -mno-cygwin gradient.f
g77 -c -O3 -ffast-math -mno-cygwin gradrgd.f
g77 -c -O3 -ffast-math -mno-cygwin gradrot.f
g77 -c -O3 -ffast-math -mno-cygwin groups.f
g77 -c -O3 -ffast-math -mno-cygwin grpline.f
g77 -c -O3 -ffast-math -mno-cygwin gyrate.f
g77 -c -O3 -ffast-math -mno-cygwin hessian.f
g77 -c -O3 -ffast-math -mno-cygwin hessrgd.f
g77 -c -O3 -ffast-math -mno-cygwin hessrot.f
g77 -c -O3 -ffast-math -mno-cygwin hybrid.f
g77 -c -O3 -ffast-math -mno-cygwin image.f
g77 -c -O3 -ffast-math -mno-cygwin impose.f
g77 -c -O3 -ffast-math -mno-cygwin induce.f
g77 -c -O3 -ffast-math -mno-cygwin inertia.f
g77 -c -O3 -ffast-math -mno-cygwin initial.f
g77 -c -O3 -ffast-math -mno-cygwin initprm.f
g77 -c -O3 -ffast-math -mno-cygwin initres.f
g77 -c -O3 -ffast-math -mno-cygwin initrot.f
g77 -c -O3 -ffast-math -mno-cygwin insert.f
g77 -c -O3 -ffast-math -mno-cygwin intedit.f
g77 -c -O3 -ffast-math -mno-cygwin intxyz.f
g77 -c -O3 -ffast-math -mno-cygwin invbeta.f
g77 -c -O3 -ffast-math -mno-cygwin invert.f
g77 -c -O3 -ffast-math -mno-cygwin jacobi.f
g77 -c -O3 -ffast-math -mno-cygwin kangang.f
g77 -c -O3 -ffast-math -mno-cygwin kangle.f
g77 -c -O3 -ffast-math -mno-cygwin katom.f
g77 -c -O3 -ffast-math -mno-cygwin kbond.f
g77 -c -O3 -ffast-math -mno-cygwin kcharge.f
g77 -c -O3 -ffast-math -mno-cygwin kdipole.f
g77 -c -O3 -ffast-math -mno-cygwin kewald.f
g77 -c -O3 -ffast-math -mno-cygwin kgeom.f
g77 -c -O3 -ffast-math -mno-cygwin kimprop.f
g77 -c -O3 -ffast-math -mno-cygwin kimptor.f
g77 -c -O3 -ffast-math -mno-cygwin kinetic.f
g77 -c -O3 -ffast-math -mno-cygwin kmetal.f
g77 -c -O3 -ffast-math -mno-cygwin kmpole.f
g77 -c -O3 -ffast-math -mno-cygwin kopbend.f
g77 -c -O3 -ffast-math -mno-cygwin kopdist.f
g77 -c -O3 -ffast-math -mno-cygwin korbit.f
g77 -c -O3 -ffast-math -mno-cygwin kpitors.f
g77 -c -O3 -ffast-math -mno-cygwin kpolar.f
g77 -c -O3 -ffast-math -mno-cygwin ksolv.f
g77 -c -O3 -ffast-math -mno-cygwin kstrbnd.f
g77 -c -O3 -ffast-math -mno-cygwin kstrtor.f
g77 -c -O3 -ffast-math -mno-cygwin ktors.f
g77 -c -O3 -ffast-math -mno-cygwin ktortor.f
g77 -c -O3 -ffast-math -mno-cygwin kurey.f
g77 -c -O3 -ffast-math -mno-cygwin kvdw.f
g77 -c -O3 -ffast-math -mno-cygwin lattice.f
g77 -c -O3 -ffast-math -mno-cygwin lbfgs.f
g77 -c -O3 -ffast-math -mno-cygwin lights.f
g77 -c -O3 -ffast-math -mno-cygwin makeint.f
g77 -c -O3 -ffast-math -mno-cygwin makepdb.f
g77 -c -O3 -ffast-math -mno-cygwin makeref.f
g77 -c -O3 -ffast-math -mno-cygwin makexyz.f
g77 -c -O3 -ffast-math -mno-cygwin maxwell.f
g77 -c -O3 -ffast-math -mno-cygwin mdinit.f
g77 -c -O3 -ffast-math -mno-cygwin mdrest.f
g77 -c -O3 -ffast-math -mno-cygwin mdsave.f
g77 -c -O3 -ffast-math -mno-cygwin mdstat.f
g77 -c -O3 -ffast-math -mno-cygwin mechanic.f
g77 -c -O3 -ffast-math -mno-cygwin merge.f
g77 -c -O3 -ffast-math -mno-cygwin minimize.f
g77 -c -O3 -ffast-math -mno-cygwin minirot.f
g77 -c -O3 -ffast-math -mno-cygwin minrigid.f
g77 -c -O3 -ffast-math -mno-cygwin molecule.f
g77 -c -O3 -ffast-math -mno-cygwin moments.f
g77 -c -O3 -ffast-math -mno-cygwin monte.f
g77 -c -O3 -ffast-math -mno-cygwin mutate.f
g77 -c -O3 -ffast-math -mno-cygwin nblist.f
g77 -c -O3 -ffast-math -mno-cygwin newton.f
g77 -c -O3 -ffast-math -mno-cygwin newtrot.f
g77 -c -O3 -ffast-math -mno-cygwin nextarg.f
g77 -c -O3 -ffast-math -mno-cygwin nexttext.f
g77 -c -O3 -ffast-math -mno-cygwin nspline.f
g77 -c -O3 -ffast-math -mno-cygwin nucleic.f
g77 -c -O3 -ffast-math -mno-cygwin number.f
g77 -c -O3 -ffast-math -mno-cygwin numeral.f
g77 -c -O3 -ffast-math -mno-cygwin numgrad.f
g77 -c -O3 -ffast-math -mno-cygwin ocvm.f
g77 -c -O3 -ffast-math -mno-cygwin openend.f
g77 -c -O3 -ffast-math -mno-cygwin optimize.f
g77 -c -O3 -ffast-math -mno-cygwin optirot.f
g77 -c -O3 -ffast-math -mno-cygwin optrigid.f
g77 -c -O3 -ffast-math -mno-cygwin optsave.f
g77 -c -O3 -ffast-math -mno-cygwin orbital.f
g77 -c -O3 -ffast-math -mno-cygwin orient.f
g77 -c -O3 -ffast-math -mno-cygwin orthog.f
g77 -c -O3 -ffast-math -mno-cygwin overlap.f
g77 -c -O3 -ffast-math -mno-cygwin path.f
g77 -c -O3 -ffast-math -mno-cygwin pdbxyz.f
g77 -c -O3 -ffast-math -mno-cygwin piscf.f
g77 -c -O3 -ffast-math -mno-cygwin pmestuff.f
g77 -c -O3 -ffast-math -mno-cygwin pmpb.f
g77 -c -O3 -ffast-math -mno-cygwin polarize.f
g77 -c -O3 -ffast-math -mno-cygwin poledit.f
g77 -c -O3 -ffast-math -mno-cygwin polymer.f
g77 -c -O3 -ffast-math -mno-cygwin potential.f
g77 -c -O3 -ffast-math -mno-cygwin precise.f
g77 -c -O3 -ffast-math -mno-cygwin pressure.f
g77 -c -O3 -ffast-math -mno-cygwin prmedit.f
g77 -c -O3 -ffast-math -mno-cygwin prmkey.f
g77 -c -O3 -ffast-math -mno-cygwin promo.f
g77 -c -O3 -ffast-math -mno-cygwin protein.f
g77 -c -O3 -ffast-math -mno-cygwin prtdyn.f
g77 -c -O3 -ffast-math -mno-cygwin prterr.f
g77 -c -O3 -ffast-math -mno-cygwin prtint.f
g77 -c -O3 -ffast-math -mno-cygwin prtmol2.f
g77 -c -O3 -ffast-math -mno-cygwin prtpdb.f
g77 -c -O3 -ffast-math -mno-cygwin prtprm.f
g77 -c -O3 -ffast-math -mno-cygwin prtseq.f
g77 -c -O3 -ffast-math -mno-cygwin prtxyz.f
g77 -c -O3 -ffast-math -mno-cygwin pss.f
g77 -c -O3 -ffast-math -mno-cygwin pssrigid.f
g77 -c -O3 -ffast-math -mno-cygwin pssrot.f
g77 -c -O3 -ffast-math -mno-cygwin quatfit.f
g77 -c -O3 -ffast-math -mno-cygwin radial.f
g77 -c -O3 -ffast-math -mno-cygwin random.f
g77 -c -O3 -ffast-math -mno-cygwin rattle.f
g77 -c -O3 -ffast-math -mno-cygwin readdyn.f
g77 -c -O3 -ffast-math -mno-cygwin readgau.f
g77 -c -O3 -ffast-math -mno-cygwin readint.f
g77 -c -O3 -ffast-math -mno-cygwin readmol2.f
g77 -c -O3 -ffast-math -mno-cygwin readpdb.f
g77 -c -O3 -ffast-math -mno-cygwin readprm.f
g77 -c -O3 -ffast-math -mno-cygwin readseq.f
g77 -c -O3 -ffast-math -mno-cygwin readxyz.f
g77 -c -O3 -ffast-math -mno-cygwin replica.f
g77 -c -O3 -ffast-math -mno-cygwin rgdstep.f
g77 -c -O3 -ffast-math -mno-cygwin rings.f
g77 -c -O3 -ffast-math -mno-cygwin rmsfit.f
g77 -c -O3 -ffast-math -mno-cygwin rotlist.f
g77 -c -O3 -ffast-math -mno-cygwin rotpole.f
g77 -c -O3 -ffast-math -mno-cygwin saddle.f
g77 -c -O3 -ffast-math -mno-cygwin scan.f
g77 -c -O3 -ffast-math -mno-cygwin sdstep.f
g77 -c -O3 -ffast-math -mno-cygwin search.f
g77 -c -O3 -ffast-math -mno-cygwin server.f
g77 -c -O3 -ffast-math -mno-cygwin setime.f
g77 -c -O3 -ffast-math -mno-cygwin shakeup.f
g77 -c -O3 -ffast-math -mno-cygwin sigmoid.f
g77 -c -O3 -ffast-math -mno-cygwin sktstuff.f
g77 -c -O3 -ffast-math -mno-cygwin sniffer.f
g77 -c -O3 -ffast-math -mno-cygwin sort.f
g77 -c -O3 -ffast-math -mno-cygwin spacefill.f
g77 -c -O3 -ffast-math -mno-cygwin spectrum.f
g77 -c -O3 -ffast-math -mno-cygwin square.f
g77 -c -O3 -ffast-math -mno-cygwin suffix.f
g77 -c -O3 -ffast-math -mno-cygwin superpose.f
g77 -c -O3 -ffast-math -mno-cygwin surface.f
g77 -c -O3 -ffast-math -mno-cygwin surfatom.f
g77 -c -O3 -ffast-math -mno-cygwin switch.f
g77 -c -O3 -ffast-math -mno-cygwin sybylxyz.f
g77 -c -O3 -ffast-math -mno-cygwin temper.f
g77 -c -O3 -ffast-math -mno-cygwin testgrad.f
g77 -c -O3 -ffast-math -mno-cygwin testhess.f
g77 -c -O3 -ffast-math -mno-cygwin testpair.f
g77 -c -O3 -ffast-math -mno-cygwin testrot.f
g77 -c -O3 -ffast-math -mno-cygwin timer.f
g77 -c -O3 -ffast-math -mno-cygwin timerot.f
g77 -c -O3 -ffast-math -mno-cygwin tncg.f
g77 -c -O3 -ffast-math -mno-cygwin torphase.f
g77 -c -O3 -ffast-math -mno-cygwin torque.f
g77 -c -O3 -ffast-math -mno-cygwin torsfit.f
g77 -c -O3 -ffast-math -mno-cygwin torsions.f
g77 -c -O3 -ffast-math -mno-cygwin trimtext.f
g77 -c -O3 -ffast-math -mno-cygwin unitcell.f
g77 -c -O3 -ffast-math -mno-cygwin valence.f
g77 -c -O3 -ffast-math -mno-cygwin verlet.f
g77 -c -O3 -ffast-math -mno-cygwin version.f
g77 -c -O3 -ffast-math -mno-cygwin vibbig.f
g77 -c -O3 -ffast-math -mno-cygwin vibrate.f
g77 -c -O3 -ffast-math -mno-cygwin vibrot.f
g77 -c -O3 -ffast-math -mno-cygwin volume.f
g77 -c -O3 -ffast-math -mno-cygwin xtalfit.f
g77 -c -O3 -ffast-math -mno-cygwin xtalmin.f
g77 -c -O3 -ffast-math -mno-cygwin xyzatm.f
g77 -c -O3 -ffast-math -mno-cygwin xyzedit.f
g77 -c -O3 -ffast-math -mno-cygwin xyzint.f
g77 -c -O3 -ffast-math -mno-cygwin xyzpdb.f
g77 -c -O3 -ffast-math -mno-cygwin xyzsybyl.f
g77 -c -O3 -ffast-math -mno-cygwin zatom.f
