#
#
#  ##################################################################
#  ##                                                              ##
#  ##  compserial.make  --  compile the TINKER modules for serial  ##
#  ##         (Intel Fortran Compiler for Mac OSX Version)         ##
#  ##                                                              ##
#  ##################################################################
#
#
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 active.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 alchemy.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 analysis.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 analyze.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 angles.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 anneal.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 archive.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 attach.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 basefile.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 beeman.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 bicubic.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 bitors.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 bonds.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 born.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 bounds.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 bspline.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 calendar.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 center.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 chkpole.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 chkring.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 chkxyz.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 cholesky.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 clock.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 cluster.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 column.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 command.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 connect.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 connolly.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 control.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 correlate.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 crystal.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 cspline.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 cutoffs.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 deflate.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 delete.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 diagq.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 diffeq.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 diffuse.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 distgeom.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 document.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 dynamic.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eangang.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eangang1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eangang2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eangang3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eangle.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eangle1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eangle2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eangle3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ebond.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ebond1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ebond2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ebond3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ebuck.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ebuck1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ebuck2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ebuck3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 echarge.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 echarge1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 echarge2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 echarge3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 echgdpl.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 echgdpl1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 echgdpl2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 echgdpl3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 edipole.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 edipole1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 edipole2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 edipole3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 egauss.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 egauss1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 egauss2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 egauss3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 egeom.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 egeom1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 egeom2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 egeom3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ehal.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ehal1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ehal2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ehal3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eimprop.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eimprop1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eimprop2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eimprop3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eimptor.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eimptor1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eimptor2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eimptor3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 elj.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 elj1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 elj2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 elj3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 embed.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 emetal.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 emetal1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 emetal2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 emetal3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 emm3hb.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 emm3hb1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 emm3hb2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 emm3hb3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 empole.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 empole1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 empole2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 empole3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 energy.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eopbend.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eopbend1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eopbend2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eopbend3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eopdist.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eopdist1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eopdist2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eopdist3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 epitors.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 epitors1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 epitors2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 epitors3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 erf.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 erxnfld.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 erxnfld1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 erxnfld2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 erxnfld3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 esolv.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 esolv1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 esolv2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 esolv3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 estrbnd.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 estrbnd1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 estrbnd2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 estrbnd3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 estrtor.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 estrtor1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 estrtor2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 estrtor3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 etors.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 etors1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 etors2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 etors3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 etortor.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 etortor1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 etortor2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 etortor3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eurey.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eurey1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eurey2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 eurey3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 evcorr.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 extra.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 extra1.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 extra2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 extra3.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 fatal.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 fft3d.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 fftpack.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 field.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 final.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 flatten.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 freeunit.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 gda.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 geometry.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 getime.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 getint.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 getkey.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 getmol2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 getnumb.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 getpdb.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 getprm.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 getref.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 getstring.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 gettext.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 getword.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 getxyz.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 gradient.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 gradrgd.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 gradrot.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 groups.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 grpline.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 gyrate.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 hessian.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 hessrgd.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 hessrot.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 hybrid.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 image.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 impose.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 induce.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 inertia.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 initial.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 initprm.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 initres.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 initrot.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 insert.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 intedit.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 intxyz.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 invbeta.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 invert.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 jacobi.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kangang.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kangle.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 katom.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kbond.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kcharge.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kdipole.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kewald.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kgeom.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kimprop.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kimptor.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kinetic.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kmetal.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kmpole.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kopbend.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kopdist.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 korbit.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kpitors.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kpolar.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ksolv.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kstrbnd.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kstrtor.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ktors.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ktortor.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kurey.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 kvdw.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 lattice.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 lbfgs.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 lights.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 makeint.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 makepdb.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 makeref.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 makexyz.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 maxwell.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 mdinit.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 mdrest.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 mdsave.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 mdstat.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 mechanic.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 merge.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 minimize.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 minirot.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 minrigid.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 molecule.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 moments.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 monte.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 mutate.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 nblist.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 newton.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 newtrot.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 nextarg.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 nexttext.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 nspline.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 nucleic.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 number.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 numeral.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 numgrad.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 ocvm.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 openend.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 optimize.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 optirot.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 optrigid.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 optsave.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 orbital.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 orient.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 orthog.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 overlap.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 path.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 pdbxyz.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 piscf.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 pmepol.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 pmpb.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 polarize.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 poledit.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 polymer.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 potential.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 precise.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 pressure.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 prmedit.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 prmkey.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 promo.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 protein.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 prtdyn.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 prterr.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 prtint.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 prtmol2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 prtpdb.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 prtprm.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 prtseq.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 prtxyz.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 pss.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 pssrigid.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 pssrot.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 quatfit.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 radial.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 random.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 rattle.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 readdyn.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 readgau.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 readint.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 readmol2.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 readpdb.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 readprm.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 readseq.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 readxyz.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 replica.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 rgdstep.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 rings.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 rmsfit.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 rotlist.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 rotpole.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 saddle.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 scan.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 sdstep.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 search.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 server.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 setime.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 shakeup.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 sigmoid.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 sktstuff.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 sniffer.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 sort.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 spacefill.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 spectrum.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 square.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 suffix.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 superpose.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 surface.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 surfatom.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 switch.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 sybylxyz.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 temper.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 testgrad.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 testhess.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 testpair.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 testrot.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 timer.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 timerot.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 tncg.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 torphase.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 torque.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 torsions.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 trimtext.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 unitcell.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 valence.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 verlet.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 version.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 vibbig.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 vibrate.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 vibrot.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 volume.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 xtalfit.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 xtalmin.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 xyzatm.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 xyzedit.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 xyzint.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 xyzpdb.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 xyzsybyl.f
ifort -c -fast -axSSSE3 -no-ipo -vec-report0 zatom.f
