#
#
#  ############################################################
#  ##                                                        ##
#  ##  compile.make  --  compile each of the TINKER modules  ##
#  ##                 (IBM AIX Unix Version)                 ##
#  ##                                                        ##
#  ############################################################
#
#
xlf -c -O active.f
xlf -c -O alchemy.f
xlf -c -O analysis.f
xlf -c -O analyze.f
xlf -c -O angles.f
xlf -c -O anneal.f
xlf -c -O archive.f
xlf -c -O attach.f
xlf -c -O basefile.f
xlf -c -O beeman.f
xlf -c -O bicubic.f
xlf -c -O bitors.f
xlf -c -O bonds.f
xlf -c -O born.f
xlf -c -O bounds.f
xlf -c -O calendar.f
xlf -c -O center.f
xlf -c -O chkpole.f
xlf -c -O chkring.f
xlf -c -O chkxyz.f
xlf -c -O cholesky.f
xlf -c -O clock.f
xlf -c -O cluster.f
xlf -c -O column.f
xlf -c -O command.f
xlf -c -O connect.f
xlf -c -O connolly.f
xlf -c -O control.f
xlf -c -O correlate.f
xlf -c -O crystal.f
xlf -c -O cspline.f
xlf -c -O cutoffs.f
xlf -c -O deflate.f
xlf -c -O delete.f
xlf -c -O diagq.f
xlf -c -O diffeq.f
xlf -c -O diffuse.f
xlf -c -O distgeom.f
xlf -c -O document.f
xlf -c -O dynamic.f
xlf -c -O eangang.f
xlf -c -O eangang1.f
xlf -c -O eangang2.f
xlf -c -O eangang3.f
xlf -c -O eangle.f
xlf -c -O eangle1.f
xlf -c -O eangle2.f
xlf -c -O eangle3.f
xlf -c -O ebond.f
xlf -c -O ebond1.f
xlf -c -O ebond2.f
xlf -c -O ebond3.f
xlf -c -O ebuck.f
xlf -c -O ebuck1.f
xlf -c -O ebuck2.f
xlf -c -O ebuck3.f
xlf -c -O echarge.f
xlf -c -O echarge1.f
xlf -c -O echarge2.f
xlf -c -O echarge3.f
xlf -c -O echgdpl.f
xlf -c -O echgdpl1.f
xlf -c -O echgdpl2.f
xlf -c -O echgdpl3.f
xlf -c -O edipole.f
xlf -c -O edipole1.f
xlf -c -O edipole2.f
xlf -c -O edipole3.f
xlf -c -O egauss.f
xlf -c -O egauss1.f
xlf -c -O egauss2.f
xlf -c -O egauss3.f
xlf -c -O egeom.f
xlf -c -O egeom1.f
xlf -c -O egeom2.f
xlf -c -O egeom3.f
xlf -c -O ehal.f
xlf -c -O ehal1.f
xlf -c -O ehal2.f
xlf -c -O ehal3.f
xlf -c -O eimprop.f
xlf -c -O eimprop1.f
xlf -c -O eimprop2.f
xlf -c -O eimprop3.f
xlf -c -O eimptor.f
xlf -c -O eimptor1.f
xlf -c -O eimptor2.f
xlf -c -O eimptor3.f
xlf -c -O elj.f
xlf -c -O elj1.f
xlf -c -O elj2.f
xlf -c -O elj3.f
xlf -c -O embed.f
xlf -c -O emetal.f
xlf -c -O emetal1.f
xlf -c -O emetal2.f
xlf -c -O emetal3.f
xlf -c -O emm3hb.f
xlf -c -O emm3hb1.f
xlf -c -O emm3hb2.f
xlf -c -O emm3hb3.f
xlf -c -O empole.f
xlf -c -O empole1.f
xlf -c -O empole2.f
xlf -c -O empole3.f
xlf -c -O energy.f
xlf -c -O eopbend.f
xlf -c -O eopbend1.f
xlf -c -O eopbend2.f
xlf -c -O eopbend3.f
xlf -c -O eopdist.f
xlf -c -O eopdist1.f
xlf -c -O eopdist2.f
xlf -c -O eopdist3.f
xlf -c -O epitors.f
xlf -c -O epitors1.f
xlf -c -O epitors2.f
xlf -c -O epitors3.f
xlf -c -O erf.f
xlf -c -O erxnfld.f
xlf -c -O erxnfld1.f
xlf -c -O erxnfld2.f
xlf -c -O erxnfld3.f
xlf -c -O esolv.f
xlf -c -O esolv1.f
xlf -c -O esolv2.f
xlf -c -O esolv3.f
xlf -c -O estrbnd.f
xlf -c -O estrbnd1.f
xlf -c -O estrbnd2.f
xlf -c -O estrbnd3.f
xlf -c -O estrtor.f
xlf -c -O estrtor1.f
xlf -c -O estrtor2.f
xlf -c -O estrtor3.f
xlf -c -O etors.f
xlf -c -O etors1.f
xlf -c -O etors2.f
xlf -c -O etors3.f
xlf -c -O etortor.f
xlf -c -O etortor1.f
xlf -c -O etortor2.f
xlf -c -O etortor3.f
xlf -c -O eurey.f
xlf -c -O eurey1.f
xlf -c -O eurey2.f
xlf -c -O eurey3.f
xlf -c -O evcorr.f
xlf -c -O extra.f
xlf -c -O extra1.f
xlf -c -O extra2.f
xlf -c -O extra3.f
xlf -c -O fatal.f
xlf -c -O fft3d.f
xlf -c -O fftpack.f
xlf -c -O field.f
xlf -c -O final.f
xlf -c -O flatten.f
xlf -c -O freeunit.f
xlf -c -O gda.f
xlf -c -O geometry.f
xlf -c -O getint.f
xlf -c -O getkey.f
xlf -c -O getmol2.f
xlf -c -O getnumb.f
xlf -c -O getpdb.f
xlf -c -O getprm.f
xlf -c -O getref.f
xlf -c -O getstring.f
xlf -c -O gettext.f
xlf -c -O getword.f
xlf -c -O getxyz.f
xlf -c -O gradient.f
xlf -c -O gradrgd.f
xlf -c -O gradrot.f
xlf -c -O groups.f
xlf -c -O grpline.f
xlf -c -O gyrate.f
xlf -c -O hessian.f
xlf -c -O hessrgd.f
xlf -c -O hessrot.f
xlf -c -O hybrid.f
xlf -c -O image.f
xlf -c -O impose.f
xlf -c -O induce.f
xlf -c -O inertia.f
xlf -c -O initial.f
xlf -c -O initprm.f
xlf -c -O initres.f
xlf -c -O initrot.f
xlf -c -O insert.f
xlf -c -O intedit.f
xlf -c -O intxyz.f
xlf -c -O invbeta.f
xlf -c -O invert.f
xlf -c -O jacobi.f
xlf -c -O kangang.f
xlf -c -O kangle.f
xlf -c -O katom.f
xlf -c -O kbond.f
xlf -c -O kcharge.f
xlf -c -O kdipole.f
xlf -c -O kewald.f
xlf -c -O kgeom.f
xlf -c -O kimprop.f
xlf -c -O kimptor.f
xlf -c -O kinetic.f
xlf -c -O kmetal.f
xlf -c -O kmpole.f
xlf -c -O kopbend.f
xlf -c -O kopdist.f
xlf -c -O korbit.f
xlf -c -O kpitors.f
xlf -c -O kpolar.f
xlf -c -O ksolv.f
xlf -c -O kstrbnd.f
xlf -c -O kstrtor.f
xlf -c -O ktors.f
xlf -c -O ktortor.f
xlf -c -O kurey.f
xlf -c -O kvdw.f
xlf -c -O lattice.f
xlf -c -O lbfgs.f
xlf -c -O lights.f
xlf -c -O makeint.f
xlf -c -O makepdb.f
xlf -c -O makeref.f
xlf -c -O makexyz.f
xlf -c -O maxwell.f
xlf -c -O mdinit.f
xlf -c -O mdrest.f
xlf -c -O mdsave.f
xlf -c -O mdstat.f
xlf -c -O mechanic.f
xlf -c -O merge.f
xlf -c -O minimize.f
xlf -c -O minirot.f
xlf -c -O minrigid.f
xlf -c -O molecule.f
xlf -c -O moments.f
xlf -c -O monte.f
xlf -c -O mutate.f
xlf -c -O nblist.f
xlf -c -O newton.f
xlf -c -O newtrot.f
xlf -c -O nextarg.f
xlf -c -O nexttext.f
xlf -c -O nspline.f
xlf -c -O nucleic.f
xlf -c -O number.f
xlf -c -O numeral.f
xlf -c -O numgrad.f
xlf -c -O ocvm.f
xlf -c -O openend.f
xlf -c -O optimize.f
xlf -c -O optirot.f
xlf -c -O optrigid.f
xlf -c -O optsave.f
xlf -c -O orbital.f
xlf -c -O orient.f
xlf -c -O orthog.f
xlf -c -O overlap.f
xlf -c -O path.f
xlf -c -O -qmaxmem=-1 pdbxyz.f
xlf -c -O piscf.f
xlf -c -O pmestuff.f
xlf -c -O pmpb.f
xlf -c -O polarize.f
xlf -c -O poledit.f
xlf -c -O polymer.f
xlf -c -O potential.f
xlf -c -O precise.f
xlf -c -O pressure.f
xlf -c -O prmedit.f
xlf -c -O prmkey.f
xlf -c -O promo.f
xlf -c -O -qmaxmem=-1 protein.f
xlf -c -O prtdyn.f
xlf -c -O prterr.f
xlf -c -O prtint.f
xlf -c -O prtmol2.f
xlf -c -O prtpdb.f
xlf -c -O prtprm.f
xlf -c -O prtseq.f
xlf -c -O prtxyz.f
xlf -c -O pss.f
xlf -c -O pssrigid.f
xlf -c -O pssrot.f
xlf -c -O quatfit.f
xlf -c -O radial.f
xlf -c -O random.f
xlf -c -O rattle.f
xlf -c -O readdyn.f
xlf -c -O readgau.f
xlf -c -O readint.f
xlf -c -O readmol2.f
xlf -c -O readpdb.f
xlf -c -O readprm.f
xlf -c -O readseq.f
xlf -c -O readxyz.f
xlf -c -O replica.f
xlf -c -O rgdstep.f
xlf -c -O rings.f
xlf -c -O rmsfit.f
xlf -c -O rotlist.f
xlf -c -O rotpole.f
xlf -c -O saddle.f
xlf -c -O scan.f
xlf -c -O sdstep.f
xlf -c -O search.f
xlf -c -O server.f
xlf -c -O shakeup.f
xlf -c -O sigmoid.f
xlf -c -O sktstuff.f
xlf -c -O sniffer.f
xlf -c -O sort.f
xlf -c -O spacefill.f
xlf -c -O spectrum.f
xlf -c -O square.f
xlf -c -O suffix.f
xlf -c -O superpose.f
xlf -c -O surface.f
xlf -c -O surfatom.f
xlf -c -O switch.f
xlf -c -O sybylxyz.f
xlf -c -O temper.f
xlf -c -O testgrad.f
xlf -c -O testhess.f
xlf -c -O testpair.f
xlf -c -O testrot.f
xlf -c -O timer.f
xlf -c -O timerot.f
xlf -c -O tncg.f
xlf -c -O torphase.f
xlf -c -O torque.f
xlf -c -O torsfit.f
xlf -c -O torsions.f
xlf -c -O trimtext.f
xlf -c -O unitcell.f
xlf -c -O valence.f
xlf -c -O verlet.f
xlf -c -O version.f
xlf -c -O vibbig.f
xlf -c -O vibrate.f
xlf -c -O vibrot.f
xlf -c -O volume.f
xlf -c -O xtalfit.f
xlf -c -O xtalmin.f
xlf -c -O xyzatm.f
xlf -c -O xyzedit.f
xlf -c -O xyzint.f
xlf -c -O xyzpdb.f
xlf -c -O xyzsybyl.f
xlf -c -O zatom.f
