@echo off
rem
rem
rem  ###########################################################
rem  ##                                                       ##
rem  ##  compile.bat  --  compile each of the TINKER modules  ##
rem  ##      (Intel Fortran Compiler for Windows Version)     ##
rem  ##                                                       ##
rem  ###########################################################
rem
rem
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp active.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp alchemy.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp analysis.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp analyze.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp angles.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp anneal.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp archive.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp attach.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp bar.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp basefile.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp beeman.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp bicubic.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp bitors.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp bonds.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp born.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp bounds.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp bussi.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp calendar.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp center.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp chkpole.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp chkring.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp chkxyz.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp cholesky.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp clock.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp cluster.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp column.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp /4Yportlib command.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp connect.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp connolly.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp control.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp correlate.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp crystal.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp cspline.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp cutoffs.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp deflate.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp delete.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp diagq.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp diffeq.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp diffuse.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp distgeom.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp document.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp dynamic.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eangang.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eangang1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eangang2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eangang3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eangle.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eangle1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eangle2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eangle3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ebond.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ebond1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ebond2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ebond3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ebuck.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ebuck1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ebuck2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ebuck3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp echarge.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp echarge1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp echarge2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp echarge3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp echgdpl.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp echgdpl1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp echgdpl2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp echgdpl3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp edipole.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp edipole1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp edipole2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp edipole3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp egauss.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp egauss1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp egauss2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp egauss3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp egeom.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp egeom1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp egeom2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp egeom3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ehal.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ehal1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ehal2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ehal3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eimprop.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eimprop1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eimprop2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eimprop3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eimptor.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eimptor1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eimptor2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eimptor3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp elj.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp elj1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp elj2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp elj3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp embed.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp emetal.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp emetal1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp emetal2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp emetal3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp emm3hb.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp emm3hb1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp emm3hb2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp emm3hb3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp empole.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp empole1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp empole2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp empole3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp energy.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eopbend.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eopbend1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eopbend2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eopbend3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eopdist.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eopdist1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eopdist2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eopdist3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp epitors.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp epitors1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp epitors2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp epitors3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp erf.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp erxnfld.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp erxnfld1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp erxnfld2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp erxnfld3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp esolv.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp esolv1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp esolv2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp esolv3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp estrbnd.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp estrbnd1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp estrbnd2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp estrbnd3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp estrtor.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp estrtor1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp estrtor2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp estrtor3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp etors.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp etors1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp etors2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp etors3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp etortor.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp etortor1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp etortor2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp etortor3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eurey.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eurey1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eurey2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp eurey3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp evcorr.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp extra.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp extra1.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp extra2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp extra3.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp fatal.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp fft3d.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp fftpack.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp field.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp final.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp flatten.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp freeunit.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp gda.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp geometry.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp getint.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp getkey.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp getmol.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp getmol2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp getnumb.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp getpdb.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp getprm.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp getref.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp getstring.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp gettext.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp getword.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp getxyz.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ghmcstep.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp gradient.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp gradrgd.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp gradrot.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp groups.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp grpline.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp gyrate.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp hessian.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp hessrgd.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp hessrot.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp hybrid.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp image.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp impose.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp induce.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp inertia.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp initatom.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp initial.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp initprm.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp initres.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp initrot.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp insert.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp intedit.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp intxyz.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp invbeta.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp invert.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp jacobi.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kangang.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kangle.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp katom.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kbond.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kcharge.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kdipole.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kewald.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kextra.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kgeom.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kimprop.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kimptor.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kinetic.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kmetal.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kmpole.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kopbend.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kopdist.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp korbit.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kpitors.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kpolar.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ksolv.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kstrbnd.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kstrtor.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ktors.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ktortor.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kurey.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp kvdw.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp lattice.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp lbfgs.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp lights.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp makeint.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp makeref.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp makexyz.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp maxwell.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp mdinit.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp mdrest.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp mdsave.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp mdstat.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp mechanic.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp merge.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp minimize.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp minirot.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp minrigid.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp molecule.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp molxyz.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp moments.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp monte.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp mutate.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp nblist.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp newton.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp newtrot.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp nextarg.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp nexttext.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp nose.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp nspline.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp nucleic.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp number.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp numeral.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp numgrad.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp ocvm.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp openend.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp optimize.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp optirot.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp optrigid.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp optsave.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp orbital.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp orient.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp orthog.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp overlap.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp path.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp pdbxyz.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp picalc.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp pmestuff.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp pmpb.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp polarize.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp poledit.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp polymer.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp potential.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp precise.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp pressure.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp prmedit.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp prmkey.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp promo.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp protein.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp prtdyn.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp prterr.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp prtint.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp prtmol2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp prtpdb.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp prtprm.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp prtseq.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp prtxyz.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp pss.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp pssrigid.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp pssrot.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp quatfit.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp radial.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp random.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp rattle.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp readdyn.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp readgau.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp readint.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp readmol.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp readmol2.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp readpdb.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp readprm.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp readseq.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp readxyz.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp replica.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp respa.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp rgdstep.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp rings.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp rmsfit.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp rotlist.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp rotpole.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp saddle.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp scan.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp sdstep.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp search.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp server.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp shakeup.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp sigmoid.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp sktstuff.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp sniffer.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp sort.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp spacefill.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp spectrum.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp square.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp suffix.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp superpose.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp surface.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp surfatom.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp switch.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp sybylxyz.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp temper.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp testgrad.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp testhess.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp testpair.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp testpol.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp testrot.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp timer.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp timerot.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp tncg.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp torphase.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp torque.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp torsfit.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp torsions.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp trimtext.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp unitcell.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp valence.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp verlet.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp version.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp vibbig.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp vibrate.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp vibrot.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp volume.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp xtalfit.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp xtalmin.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp xyzatm.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp xyzedit.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp xyzint.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp xyzpdb.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp xyzsybyl.f
ifort /c /O3 /QaxSSE3 /Qip- /Qprec-div- /w /Qopenmp zatom.f
